{ question: 'Qu’est-ce que l’histologie ?', answer: 'La science des tissus biologiques, anciennement appelée anatomie microscopique.', },
{ question: 'Quels progrès techniques ont rendu l’histologie possible ?', answer: 'La microscopie et les méthodes de préparation des tissus.', },
{ question: 'À quelle période la cellule devient-elle reconnue comme unité de la matière vivante ?', answer: 'Entre 1838 et 1839.', },
{ question: 'Quels microscopes apparaissent au milieu du XXe siècle ?', answer: 'Les microscopes électroniques à transmission puis à balayage.', },
{ question: 'Quels sont les objectifs de l’histologie ?', answer: 'Approfondir la structure du vivant, relier morphologie et fonction, et comprendre la spécialisation cellulaire.', },
{ question: 'Quels sont les niveaux d’organisation structurale du corps humain ?', answer: 'Systèmes, organes, tissus, cellules, organites, molécules.', },
{ question: 'Quelles sont les deux grandes subdivisions de l’histologie ?', answer: 'Histologie générale et histologie spéciale.', },
{ question: 'Quelle est la définition d’un tissu ?', answer: 'Un ensemble coopératif de cellules différenciées formant une triple association territoriale, fonctionnelle et biologique.', },
{ question: 'Qu’est-ce que l’association territoriale d’un tissu ?', answer: 'Un ensemble de cellules topographiquement individualisé, parfois délimité par une membrane basale.', },
{ question: 'Qu’est-ce que l’association fonctionnelle d’un tissu ?', answer: 'Des cellules spécialisées collaborant pour assurer une fonction précise.', },
{ question: 'Qu’est-ce que l’association biologique d’un tissu ?', answer: 'Chaque tissu ayant des propriétés biologiques propres.', },
{ question: 'Quels sont les deux composants d’un tissu ?', answer: 'Les cellules et la matrice extracellulaire.', },
{ question: 'Qu’est-ce qui varie entre les tissus ?', answer: 'La nature des cellules, la composition de la MEC et la proportion relative cellules/MEC.', },
{ question: 'Quels sont les moyens de communication entre cellules eucaryotes ?', answer: 'Contact direct, courant électrique, molécules chimiques et signaux agissant sur des récepteurs.', },
{ question: 'Quelles sont les quatre grandes familles de tissus ?', answer: 'Épithéliums, conjonctifs et squelettiques, musculaires, nerveux.', },
{ question: 'Où trouve-t-on les épithéliums de revêtement ?', answer: 'Sur les cavités internes et à la surface du corps.', },
{ question: 'Qu’est-ce que la lumière en histologie ?', answer: 'L’espace intérieur d’un organe creux circonscrit par ses parois.', },
{ question: 'Quelles sont les deux catégories d’épithéliums glandulaires ?', answer: 'Exocrines et endocrines.', },
{ question: 'Quel est le produit des glandes exocrines ?', answer: 'Une sécrétion véhiculée par un canal excréteur.', },
{ question: 'Quel est le produit des glandes endocrines ?', answer: 'Une sécrétion libérée dans le sang.', },
{ question: 'Qu’est-ce qu’un tissu conjonctif lâche ?', answer: 'Un tissu riche en MEC et pauvre en cellules non jointives.', },
{ question: 'Qu’est-ce qu’un tissu conjonctif dense ?', answer: 'Un tissu riche en fibres de collagène et pauvre en cellules.', },
{ question: 'Qu’est-ce qu’un tissu conjonctif réticulaire ?', answer: 'Un tissu riche en fibres de réticuline.', },
{ question: 'De quoi est constitué un tissu adipeux ?', answer: 'D’adipocytes.', },
{ question: 'Quels sont les deux types de tissus squelettiques ?', answer: 'Osseux et cartilagineux.', },
{ question: 'Quelles cellules composent le muscle strié squelettique ?', answer: 'Des rhabdomyocytes plurinucléés.', },
{ question: 'Quel muscle est autonome ?', answer: 'Le muscle lisse.', },
{ question: 'Quelle est la caractéristique du muscle strié cardiaque ?', answer: 'Il possède une innervation intrinsèque et des cellules mononucléées.', },
{ question: 'Quels sont les deux composants du système nerveux ?', answer: 'Système nerveux central et périphérique.', },
{ question: 'Quelles cellules accompagnent les neurones dans les tissus nerveux ?', answer: 'Les cellules gliales, comme les astrocytes.', },
{ question: 'Que sont les populations cellulaires libres ?', answer: 'Des cellules indépendantes distribuées dans l’organisme.', },
{ question: 'Quels éléments figurés du sang font partie des populations cellulaires libres ?', answer: 'Hématies, granulocytes, plaquettes, mastocytes, lymphocytes, plasmocytes, monocytes.', },
{ question: 'Où circule-t-on les populations cellulaires libres ?', answer: 'Dans le sang, la lymphe, le LCR, les tissus immunitaires et le tissu conjonctif lâche.', },
{ question: 'Où se trouvent les cellules de la lignée germinale ?', answer: 'Dans les gonades.', },
{ question: 'Quels sont les stades de la lignée germinale ?', answer: 'Gonocytes, gonies, spermatocytes, spermatides, spermatozoïdes, ovocytes I.', },
{ question: 'Qu’est-ce que la MEC ?', answer: 'Un réseau complexe de macromolécules sécrétées par les cellules.', },
{ question: 'Quels rôles remplit la MEC ?', answer: 'Architecture, soutien, nutrition, stockage moléculaire, migration cellulaire.', },
{ question: 'Où la MEC est-elle très abondante ?', answer: 'Dans les tissus conjonctifs lâches.', },
{ question: 'Qu’est-ce que le collagène ?', answer: 'Une protéine fibreuse structurelle de la MEC.', },
{ question: 'Quels sont les trois types de collagènes fibrillaires ?', answer: 'Collagène I, II et III.', },
{ question: 'Où trouve-t-on du collagène de type I ?', answer: 'Tissus conjonctifs denses, lâches, os et cornée.', },
{ question: 'Quel est le rôle de l’élastine ?', answer: 'Conférer l’élasticité aux tissus.', },
{ question: 'Quels sont les polysaccharides de la MEC ?', answer: 'Glycosaminoglycanes et protéoglycanes.', },
{ question: 'Quel est le rôle des glycoprotéines d’adhérence ?', answer: 'Assurer l’ancrage cellulaire, ex: laminines et fibronectines.', },
{ question: 'Qu’est-ce que la membrane basale ?', answer: 'Une organisation particulière de la MEC entourant certaines cellules.', },
{ question: 'Quels sont ses constituants principaux ?', answer: 'Collagène IV et laminines.', },
{ question: 'Quelles cellules sont entourées d’une membrane basale ?', answer: 'Cellules épithéliales, musculaires, adipocytes et cellules de Schwann.', },
{ question: 'Quels rôles assure la membrane basale ?', answer: 'Ancrage cellulaire, barrière, filtration, polarisation, maintien, réparation.', },
{ question: 'Quel est le pouvoir de résolution de la microscopie optique ?', answer: '0,5 à 0,2 µm.', },
{ question: 'Quel est le grandissement maximal en microscopie optique ?', answer: 'x1000.', },
{ question: 'Quels sont les avantages de la microscopie confocale ?', answer: 'Images de faible profondeur et reconstruction 3D.', },
{ question: 'Quel est le pouvoir de résolution de la microscopie électronique ?', answer: '0,3 nm.', },
{ question: 'Quel est le grandissement maximal en MET ?', answer: 'x100 000.', },
{ question: 'Que permet le MET ?', answer: 'L’étude des ultrastructures grâce aux métaux lourds.', },
{ question: 'Que montre le MEB ?', answer: 'La surface des structures en 3D.', },
{ question: 'Quel est le principe d’une préparation histologique ?', answer: 'Prélever, fixer, inclure, couper, colorer puis observer.', },
{ question: 'Quel est le but de la fixation ?', answer: 'Conserver le tissu proche du vivant et durcir le prélèvement.', },
{ question: 'Quel est le rôle de la paraffine ?', answer: 'Permettre l’inclusion après déshydratation.', },
{ question: 'Pourquoi réhydrate-t-on les coupes avant coloration ?', answer: 'Parce que les colorants sont hydrophiles.', },
{ question: 'Quels sont les deux colorants du bichrome HES ?', answer: 'Hématoxyline (noyaux) et éosine (cytoplasme).', },
{ question: 'Quelle troisième couleur est ajoutée dans un trichrome ?', answer: 'Le safran pour le tissu conjonctif.', },
{ question: 'Qu’est-ce que la coloration PAS ?', answer: 'Une coloration des polysaccharides.', },
{ question: 'Quel est le principe de l’immunohistochimie ?', answer: 'Des anticorps couplés à une enzyme produisant une couleur.', },
{ question: 'Quels paramètres doivent être identifiés avant l’analyse d’une coupe ?', answer: 'Microscopie, grossissement, coloration, type d’organe, incidence de coupe.', },
{ question: 'Que montre une coupe transversale ?', answer: 'Une lumière centrale et une paroi circulaire.', },
{ question: 'Que montre une coupe longitudinale ?', answer: 'Deux traits représentant la paroi et une lumière entre les deux.', },
{ question: 'Qu’indique une coupe oblique ?', answer: 'Une structure pouvant apparaître en rond, en traits ou oblongue.', },
