{ question: 'Quelle est la définition d’un épithélium ?', answer: 'Ensemble coordonné de cellules juxtaposées et jointives.', },
{ question: 'Quel est l’espace extracellulaire des épithéliums ?', answer: 'L’espace para-cellulaire, restreint ou absent.', },
{ question: 'Les épithéliums possèdent-ils une MEC abondante ?', answer: 'Non, la MEC est peu abondante et peu visible au MO.', },
{ question: 'Sur quoi repose un épithélium ?', answer: 'Sur une lame basale.', },
{ question: 'Les épithéliums sont-ils vascularisés ?', answer: 'Non, ils sont dépourvus de vascularisation.', },
{ question: 'Quand le terme épithélium a-t-il été inventé ?', answer: 'Au début du XVIIIe siècle.', },
{ question: 'Quels sont les deux grands groupes d’épithéliums ?', answer: 'Épithéliums de revêtement et épithéliums glandulaires.', },
{ question: 'Que revêt un épithélium de revêtement ?', answer: 'Une surface corporelle ou une cavité.', },
{ question: 'Quel est l’épithélium de la peau ?', answer: 'L’épiderme.', },
{ question: 'Quels organes ouverts vers l’extérieur sont revêtus par un épithélium ?', answer: 'Tube digestif, appareil respiratoire, voies urinaires et génitales.', },
{ question: 'Quels organes clos sont revêtus par un épithélium ?', answer: 'Vaisseaux sanguins, lymphatiques et séreuses.', },
{ question: 'Que voit-on en coupe transversale d’un épithélium ?', answer: 'Une rangée de cellules tassées bordant une lumière.', },
{ question: 'Que voit-on en coupe longitudinale d’un épithélium ?', answer: 'Un pavage de cellules jointives.', },
{ question: 'Quelle est la différence générale entre épithélium et tissu conjonctif ?', answer: 'Épithélium : cellules tassées. Conjonctif : cellules séparées par une MEC.', },
{ question: 'Quelle protéine forme les lamelles de la peau dépourvues de noyaux ?', answer: 'La kératine.', },
{ question: 'Qu’est-ce qu’un épithélium simple ?', answer: 'Un épithélium composé d’une seule couche de cellules.', },
{ question: 'Quelle est la caractéristique de l’épithélium simple en MO ?', answer: 'Une seule rangée de noyaux.', },
{ question: 'Donner un exemple d’épithélium simple.', answer: 'L’épithélium des tubules rénaux.', },
{ question: 'Qu’est-ce qu’un épithélium stratifié ?', answer: 'Un épithélium à plusieurs couches de cellules.', },
{ question: 'Quelle protéine se trouve dans les épithéliums kératinisés ?', answer: 'La kératine.', },
{ question: 'Quelle est la différence entre kératine et cytokératine ?', answer: 'La kératine est une protéine fibreuse de surface, la cytokératine un filament intermédiaire du cytosquelette.', },
{ question: 'Qu’est-ce qu’un épithélium pseudostratifié ?', answer: 'Épithélium où toutes les cellules contactent la lame basale mais pas toutes la lumière.', },
{ question: 'Quelle est l’exception à la classification des épithéliums ?', answer: 'L’urothélium ou épithélium polymorphe.', },
{ question: 'Selon quoi classe-t-on aussi les épithéliums ?', answer: 'Selon la forme des cellules superficielles.', },
{ question: 'Que sont des cellules pavimenteuses ?', answer: 'Des cellules plus larges que hautes.', },
{ question: 'Où trouve-t-on des cellules pavimenteuses simples ?', answer: 'Dans la paroi interne des vaisseaux sanguins et lymphatiques.', },
{ question: 'Que sont des cellules cubiques ?', answer: 'Des cellules aussi larges que hautes.', },
{ question: 'Que sont des cellules prismatiques ?', answer: 'Des cellules plus hautes que larges.', },
{ question: 'Quels sont les trois types de formes cellulaires en épithélium ?', answer: 'Pavimenteuses, cubiques, prismatiques.', },
{ question: 'Quels sont les trois types selon la multiplicité des couches ?', answer: 'Simple, stratifié, pseudostratifié.', },
{ question: 'Les jonctions intercellulaires assurent-elles la cohésion des épithéliums ?', answer: 'Oui, via des dispositifs spécialisés.', },
{ question: 'Quels tissus présentent des jonctions intercellulaires ?', answer: 'Tous, mais elles sont particulièrement développées dans les épithéliums.', },
{ question: 'Quels sont les deux rôles des jonctions communicantes ?', answer: 'Passage de petites molécules et communication cellulaire.', },
{ question: 'De quoi sont constituées les jonctions communicantes ?', answer: 'De connexons formés de connexines.', },
{ question: 'Quel est le rôle principal des jonctions serrées ?', answer: 'Former un scellage étanche empêchant le passage paracellulaire.', },
{ question: 'Quel épithélium est imperméable à l’eau grâce aux jonctions serrées ?', answer: 'L’épiderme.', },
{ question: 'Quels sont les trois types de jonctions d’ancrage ?', answer: 'Zonula adhaerens, macula adhaerens (desmosomes) et macula ponctuelles.', },
{ question: 'Quelles molécules composent les jonctions d’ancrage ?', answer: 'Les cadhérines.', },
{ question: 'Les cadhérines sont-elles calcium dépendantes ?', answer: 'Oui, ce sont des molécules homophiliques calcium dépendantes.', },
{ question: 'Quelles pathologies sont liées à des anomalies de jonctions ?', answer: 'Les maladies bulleuses de l’épiderme.', },
{ question: 'Qu’est-ce que la polarité apico-basale ?', answer: 'La différence entre pôle apical et pôle basal dans la cellule épithéliale.', },
{ question: 'Où se situe la face apicale ?', answer: 'Au contact de la lumière.', },
{ question: 'Où se situe la face basale ?', answer: 'En contact avec la lame basale.', },
{ question: 'Quels types d’épithéliums présentent clairement une polarité apico-basale ?', answer: 'Les épithéliums simples et pseudostratifiés.', },
{ question: 'Quel est le rôle du domaine basolatéral ?', answer: 'Transduction du signal et interactions cellule-cellule et cellule-MEC.', },
{ question: 'Quelles structures assurent la cohésion cellule-MEC ?', answer: 'Hémidesmosomes et contacts focaux.', },
{ question: 'Qu’est-ce qu’un labyrinthe basal ?', answer: 'Une zone basale avec invaginations membranaires et mitochondries abondantes.', },
{ question: 'Où observe-t-on un labyrinthe basal ?', answer: 'Dans le tube contourné du rein et les plexus choroïdes.', },
{ question: 'Que permet le domaine apical ?', answer: 'L’interaction avec l’extérieur et la présence de différenciations apicales.', },
{ question: 'Quelles sont les deux grandes familles de différenciations apicales ?', answer: 'Celles à microtubules et celles à actine.', },
{ question: 'Qu’est-ce qu’un cil vibratile ?', answer: 'Une structure apicale motile visible en MO, composée de microtubules.', },
{ question: 'Quelle est la structure axonémique du cil motile ?', answer: '9 doublets périphériques + 1 doublet central (9+2).', },
{ question: 'Quelle est la structure du cil non motile ?', answer: '9 doublets périphériques sans doublet central (9+0).', },
{ question: 'Où trouve-t-on des cils vibratiles ?', answer: 'Arbre bronchique, trachée, trompe utérine, épendyme.', },
{ question: 'Quel est le rôle du cil non motile ?', answer: 'Transduction mécanique via mobilisation par des flux liquidiens.', },
{ question: 'Qu’est-ce qu’une microvillosité simple ?', answer: 'Une evagination apicale contenant de l’actine, non visible en MO.', },
{ question: 'Qu’est-ce qu’un plateau strié ?', answer: 'Ensemble de microvillosités parallèles du pôle apical intestinal.', },
{ question: 'Qu’est-ce qu’une bordure en brosse ?', answer: 'Microvillosités longues, moins parallèles, dans le tube contourné proximal.', },
{ question: 'Qu’est-ce qu’un stéréocil ?', answer: 'Microvillosité très longue contenant de l’actine, visible en MO.', },
{ question: 'Où trouve-t-on des stéréocils ?', answer: 'Cochlée et épididyme.', },
{ question: 'Quel défaut peut provoquer une surdité dans les stéréocils ?', answer: 'L’absence d’une protéine des ponts apicaux.', },
{ question: 'Qu’est-ce que la polarité planaire ?', answer: 'Organisation polarisée dans le plan de la surface apicale.', },
{ question: 'Quel est l’exemple classique de polarité planaire ?', answer: 'Cils localisés en région postérieure.', },
{ question: 'Quelle est l’origine scientifique majeure de la découverte de la polarité planaire ?', answer: 'Les travaux sur la drosophile.', },
{ question: 'Quelles anomalies de développement sont liées à un défaut de polarité planaire ?', answer: 'Spina bifida et anencéphalie.', },
