{ question: 'Quelle est la définition actuelle d’une glande ?', answer: 'Structure dont le rôle est centré sur la sécrétion d’un produit élaboré par les cellules de la glande.', },
{ question: 'Les cellules glandulaires sont-elles toujours de nature épithéliale ?', answer: 'Non, elles peuvent être épithéliales ou non épithéliales.', },
{ question: 'Donner trois exemples de glandes épithéliales.', answer: 'Foie, pancréas, glandes salivaires.', },
{ question: 'Donner trois exemples de glandes non épithéliales.', answer: 'Rein (érythropoïétine), cœur (myoendocrines), tissu adipeux.', },
{ question: 'Quel type de cellules du cœur sécrète des hormones ?', answer: 'Les cellules myoendocrines.', },
{ question: 'Quelle hormone est sécrétée par le rein pour stimuler la production de globules rouges ?', answer: 'L’érythropoïétine.', },
{ question: 'Quel est le rôle de la rénine sécrétée par le rein ?', answer: 'Réguler la tension artérielle.', },
{ question: 'Selon quoi sont classées les glandes ?', answer: 'Selon leur mode de sécrétion.', },
{ question: 'Quelle est la définition d’une glande exocrine ?', answer: 'Glande exportant son produit vers l’extérieur de l’organisme.', },
{ question: 'Quelle structure contient les grains de sécrétion dans les glandes exocrines ?', answer: 'Le pôle apical.', },
{ question: 'Quel organite est particulièrement développé dans les glandes exocrines ?', answer: 'Le réticulum endoplasmique.', },
{ question: 'Où trouve-t-on des glandes exocrines ?', answer: 'Dans la peau, l’appareil digestif, respiratoire, uro-génital.', },
{ question: 'Quel est le mode de sécrétion des glandes endocrines ?', answer: 'Elles sécrètent leurs produits dans les capillaires sanguins.', },
{ question: 'Comment agit une hormone endocrinienne ?', answer: 'En atteignant un tissu cible porteur d’un récepteur spécifique.', },
{ question: 'Quel est l’exemple donné de glande endocrine avec IHC ?', answer: 'Îlot de Langerhans avec cellules à insuline et à somatostatine.', },
{ question: 'Qu’est-ce qu’une glande amphicrine ?', answer: 'Une glande ayant une fonction exocrine et endocrine.', },
{ question: 'Donner un exemple de glande amphicrine homotypique.', answer: 'Les hépatocytes du foie.', },
{ question: 'Donner un exemple de glande amphicrine hétérotypique.', answer: 'Le pancréas.', },
{ question: 'Qu’est-ce qu’une glande unicellulaire ?', answer: 'Une glande composée d’une seule cellule sécrétrice isolée.', },
{ question: 'Donner un exemple de glande unicellulaire.', answer: 'La cellule caliciforme.', },
{ question: 'Qu’est-ce qu’une glande intraépithéliale ?', answer: 'Des cellules glandulaires groupées dans l’épithélium sans canal excréteur.', },
{ question: 'Donner un exemple de localisation de glandes intraépithéliales.', answer: 'Les fosses nasales.', },
{ question: 'Qu’est-ce qu’un épithélium sécrétoire ?', answer: 'Épithélium dont toutes les cellules sont sécrétrices.', },
{ question: 'Quel est l’exemple d’un épithélium sécrétoire ?', answer: 'L’épithélium gastrique prismatique simple à pôle muqueux fermé.', },
{ question: 'Selon quels critères classifie-t-on les glandes exocrines ?', answer: 'Canal excréteur, forme des unités sécrétrices, nature du produit, mode d’extrusion.', },
{ question: 'Qu’est-ce qu’une glande sans canal excréteur ?', answer: 'Une glande qui s’abouche directement, comme les glandes gastriques.', },
{ question: 'Qu’est-ce qu’une glande simple ?', answer: 'Glande avec un seul canal excréteur.', },
{ question: 'Qu’est-ce qu’une glande composée ?', answer: 'Glande dont le canal excréteur est ramifié.', },
{ question: 'Qu’est-ce qu’une glande tubuleuse ?', answer: 'Glande dont la portion sécrétrice a la forme d’un tube.', },
{ question: 'Quel exemple correspond à une glande tubuleuse ?', answer: 'Les glandes sudoripares.', },
{ question: 'Quelle est la différence entre glande eccrine et apocrine ?', answer: 'Eccrine : pore propre. Apocrine : s’ouvre dans un poil.', },
{ question: 'Qu’est-ce qu’une glande acineuse ?', answer: 'Glande à portion sécrétrice en forme de petit sac (acinus).', },
{ question: 'Qu’est-ce qu’une glande alvéolaire ?', answer: 'Glande avec une vésicule à grande lumière.', },
{ question: 'Qu’est-ce qu’une glande mixte ?', answer: 'Glande combinant tubule et acinus.', },
{ question: 'Quelle est la sécrétion des cellules séreuses ?', answer: 'Sécrétion liquide riche en protéines.', },
{ question: 'Comment est l’histologie des cellules séreuses ?', answer: 'Noyau arrondi basal, cytoplasme riche en organites et vésicules apicales.', },
{ question: 'Quand les sécrétions séreuses augmentent-elles ?', answer: 'En cas d’allergie.', },
{ question: 'Quelle est la sécrétion des cellules muqueuses ?', answer: 'Sécrétion visqueuse riche en mucus.', },
{ question: 'Quelle est l’histologie des cellules muqueuses ?', answer: 'Noyau aplati basal, cytoplasme clair.', },
{ question: 'Quelles cellules sécrètent des lipoprotéines ?', answer: 'Les cellules sécrétrices de lipides ou lipoprotéiques.', },
{ question: 'Comment mettre en évidence les lipides en histologie ?', answer: 'Par coupe à congélation.', },
{ question: 'Qu’est-ce qu’une glande mérocrine ?', answer: 'Glande dont la sécrétion est excrétée par exocytose.', },
{ question: 'Qu’est-ce qu’une glande apocrine ?', answer: 'Glande dont la sécrétion inclut une partie du cytoplasme apical.', },
{ question: 'Donner un exemple de glande apocrine.', answer: 'Glande mammaire ou glande sudoripare apocrine.', },
{ question: 'Qu’est-ce qu’une glande holocrine ?', answer: 'Glande dont la cellule entière est éliminée avec la sécrétion.', },
{ question: 'Quel exemple correspond à une glande holocrine ?', answer: 'La glande sébacée.', },
{ question: 'Comment se définit le système endocrinien ?', answer: 'Sécrétion d’hormones déversées dans le sang vers des organes cibles.', },
{ question: 'Que fait une hormone hydrophile ?', answer: 'Elle agit via un récepteur membranaire.', },
{ question: 'Comment une hormone hydrophobe circule-t-elle dans le sang ?', answer: 'Liée à une protéine cargo.', },
{ question: 'Où agit une hormone hydrophobe ?', answer: 'Sur un récepteur nucléaire.', },
{ question: 'Quels sont les deux types de diabète ?', answer: 'Type 1 (jeune) et type 2 (mature).', },
{ question: 'Quel est le problème majeur du diabète de type 2 ?', answer: 'Lien avec excès de lipides et glucides ; enjeu de santé publique.', },
{ question: 'Que sont les cellules endocrines isolées ?', answer: 'Cellules situées dans un épithélium dont la sécrétion est basale vers les capillaires.', },
{ question: 'Quelle est la seule glande dont le modèle d’invagination s’applique ?', answer: 'La thyroïde (et l’adénohypophyse).', },
{ question: 'Qu’est-ce qui caractérise la thyroïde ?', answer: 'Glande épithéliale composée de follicules sans canal excréteur.', },
{ question: 'Que contient le follicule thyroïdien ?', answer: 'Une lumière remplie de substance colloïde.', },
{ question: 'Comment varie l’aspect des cellules folliculaires ?', answer: 'Selon le degré d’activation de la glande.', },
{ question: 'Comment sont organisées les autres glandes endocrines ?', answer: 'En travées rectilignes ou cordons arrondis.', },
{ question: 'Comment leurs hormones rejoignent-elles les tissus cibles ?', answer: 'Via un réseau riche en capillaires.', },
