{ question: 'En fin de 3ème semaine / début de 4ème semaine, combien de couches comporte l’embryon ?', answer: 'Trois couches : ectoblaste, entoblaste et mésoblaste.', },
{ question: 'Quels sont les trois territoires du mésoblaste à ce stade ?', answer: 'Mésoblaste latéral, mésoblaste intermédiaire et mésoblaste para-axial.', },
{ question: 'Quelle structure sépare le mésoblaste en deux et donnera le tube neural ?', answer: 'La gouttière neurale.', },
{ question: 'De quel feuillet embryonnaire provient l’appareil génital masculin ?', answer: 'Du mésoblaste intermédiaire.', },
{ question: 'Pourquoi dit-on que le développement génital et le développement urinaire sont liés ?', answer: 'Parce qu’ils se développent de façon concomitante à partir du mésoblaste intermédiaire.', },
{ question: 'À quelle période des cellules du mésoblaste intermédiaire migrent-elles vers la région du rein intermédiaire ?', answer: 'Vers la 4e-5e semaine de développement.', },
{ question: 'Quelle structure se forme d’abord dans la région du mésonéphros ?', answer: 'La gonade primitive indifférenciée.', },
{ question: 'La gonade primitive indifférenciée correspond-elle déjà à un testicule ou un ovaire ?', answer: 'Non, elle n’est ni un testicule ni un ovaire.', },
{ question: 'Que nécessite la gonade primitive pour choisir sa voie sexuelle ?', answer: 'Certains signaux spécifiques.', },
{ question: 'Comment la gonade primitive commence-t-elle à s’organiser ?', answer: 'En cordons sexuels primaires.', },
{ question: 'Comment est qualifié le tractus génital primitif ?', answer: 'Il est double, formé de deux systèmes canalaires.', },
{ question: 'Quels sont les deux canaux du tractus génital primitif ?', answer: 'Le canal de Wolff et le canal de Müller.', },
{ question: 'Que représente le canal de Wolff ?', answer: 'Le système excréteur du mésonéphros.', },
{ question: 'Comment se forme le canal de Müller ?', answer: 'Par invagination en gouttière de l’épithélium de surface du cœlome interne.', },
{ question: 'Que deviennent les canaux de Müller en présence d’une gonade féminine ?', answer: 'Ils se développent.', },
{ question: 'Que deviennent les canaux de Müller en présence d’une gonade masculine ?', answer: 'Ils régressent.', },
{ question: 'À quelle semaine apparaît le déterminisme testiculaire ?', answer: 'Vers la 7e semaine.', },
{ question: 'Quel gène initie le développement testiculaire ?', answer: 'Le gène SRY porté par le chromosome Y.', },
{ question: 'Quel est le rôle du gène SRY ?', answer: 'Il agit comme interrupteur initial pour orienter la gonade vers la formation d’un testicule.', },
{ question: 'Que se passe-t-il en absence de SRY ?', answer: 'Le développement se fait vers le sexe féminin par défaut.', },
{ question: 'Quelles sont les deux hormones majeures produites par le testicule durant l’embryogenèse ?', answer: 'La testostérone et l’AMH.', },
{ question: 'Quel est le rôle essentiel de la testostérone sur le canal de Wolff ?', answer: 'Elle favorise sa transformation en tractus génital masculin.', },
{ question: 'Quel dérivé de la testostérone agit sur la formation des organes génitaux externes ?', answer: 'La di-hydroxy-testostérone (DHT).', },
{ question: 'Quelle enzyme transforme la testostérone en DHT ?', answer: 'La 5α-réductase.', },
{ question: 'Que se passe-t-il en absence de 5α-réductase ?', answer: 'Les OGE ne se masculinisent pas malgré la présence de testicules.', },
{ question: 'Quel est le rôle de l’AMH durant l’embryogenèse ?', answer: 'Induire la régression du canal de Müller.', },
{ question: 'Quels organes ne se développent pas sous l’effet de l’AMH ?', answer: 'Trompes utérines, utérus et partie supérieure du vagin.', },
{ question: 'Comment agit globalement le gène SRY ?', answer: 'Il déclenche une cascade de transcription favorisant les gènes masculinisants et inhibant ceux du développement féminin.', },
{ question: 'Quelle est la taille moyenne d’un testicule ?', answer: '4 cm de long.', },
{ question: 'Quel est le poids moyen d’un testicule ?', answer: '10 à 15 g.', },
{ question: 'Pourquoi les testicules ont-ils une couleur blanchâtre ?', answer: 'À cause de l’albuginée, enveloppe conjonctive qui les entoure.', },
{ question: 'Où sont situés les testicules ?', answer: 'Dans les bourses (scrotum).', },
{ question: 'Quel ligament fixe le pôle inférieur du testicule au scrotum ?', answer: 'Le gubernaculum testis.', },
{ question: 'Que contient le cordon spermatique ?', answer: 'Des vaisseaux et des nerfs.', },
{ question: 'Quels sont les trois plans qui entourent les testicules de dedans en dehors ?', answer: 'La tunique vaginale, le tissu sous-cutané, puis la peau.', },
{ question: 'Qu’est-ce que l’albuginée ?', answer: 'Une capsule conjonctive blanche, épaisse et résistante entourant le testicule.', },
{ question: 'Quel épaississement de l’albuginée forme une structure interne ?', answer: 'Le corps de Highmore.', },
{ question: 'Quel est le rôle du corps de Highmore ?', answer: 'Former une charpente interne en éponge.', },
{ question: 'Combien de lobules un testicule contient-il environ ?', answer: '200 à 300 lobules.', },
{ question: 'Où se forment initialement les testicules ?', answer: 'Dans la région dorso-lombaire, para-mésonéphrotique.', },
{ question: 'Quand migrent les testicules dans le scrotum ?', answer: 'Au 5e-6e mois de vie utérine.', },
{ question: 'Comment s’appelle l’épanchement liquidien dans la vaginale ?', answer: 'L’hydrocèle.', },
{ question: 'Qu’est-ce que la cryptorchidie ?', answer: 'Une anomalie de la descente testiculaire.', },
{ question: 'Qu’est-ce qu’une ectopie testiculaire ?', answer: 'Un testicule resté en position intra-abdominale ou inguinale.', },
{ question: 'Pourquoi faut-il traiter rapidement une cryptorchidie ?', answer: 'Pour éviter l’altération définitive de la production future de spermatozoïdes.', },
{ question: 'Quel risque tumoral concerne les testicules restés en position abdominale ?', answer: 'Le gonadoblastome.', },
{ question: 'Quelle artère vascularise principalement le testicule ?', answer: 'L’artère spermatique.', },
{ question: 'Qu’est-ce que le plexus pampiniforme ?', answer: 'Un réseau veineux au pôle supérieur du testicule.', },
{ question: 'Comment s’appelle la dilatation pathologique des veines testiculaires ?', answer: 'La varicocèle.', },
{ question: 'Combien de tubes séminifères contient un lobule ?', answer: '2 à 3 tubes séminifères.', },
{ question: 'Quelle est la longueur d’un tube séminifère complètement déplié ?', answer: '80 cm à 1 m.', },
{ question: 'Quel est leur diamètre ?', answer: '150 à 300 μm selon la section.', },
{ question: 'Quelle double fonction assurent les tubes séminifères ?', answer: 'Fonction exocrine (production des spermatozoïdes) et fonction endocrine (production de testostérone).', },
{ question: 'Comment se nomment les segments rectilignes reliant les tubes séminifères au rete testis ?', answer: 'Les tubes droits.', },
{ question: 'Quel réseau forme le rete testis ?', answer: 'Le réseau du testicule.', },
{ question: 'Quelle pathologie résulte d’une agénésie du canal déférent ?', answer: 'Une infertilité par absence de spermatozoïdes dans l’éjaculat.', },
{ question: 'Quelles structures sont présentes dans le tissu interstitiel entre les tubes séminifères ?', answer: 'Tissu conjonctif, vaisseaux, lymphatiques, nerfs et cellules de Leydig.', },
{ question: 'Comment s’appelle la paroi conjonctive entourant les tubes séminifères ?', answer: 'La gaine péritubulaire.', },
{ question: 'Quels sont les deux types cellulaires constituant l’épithélium séminal ?', answer: 'Les cellules germinales et les cellules de Sertoli.', },
{ question: 'Les cellules de Sertoli sont-elles germinales ?', answer: 'Non, ce sont des cellules somatiques.', },
{ question: 'Les cellules de Sertoli se divisent-elles chez l’adulte ?', answer: 'Non.', },
{ question: 'Quels types de jonctions unissent les cellules de Sertoli entre elles et aux cellules germinales ?', answer: 'Des Gap Junction.', },
{ question: 'Quel syndrome est caractérisé par la présence exclusive de cellules de Sertoli dans les tubes séminifères ?', answer: 'Le syndrome SCO (Sertoli Cells Only).', },
{ question: 'Quels sont les rôles généraux des cellules de Sertoli ?', answer: 'Support, cohésion, nutrition, maturation des cellules germinales et spermiation.', },
{ question: 'Pourquoi les cellules germinales dépendent-elles des Sertoli pour leur nutrition ?', answer: 'Parce que l’épithélium séminal n’est pas vascularisé.', },
{ question: 'Quel est le rôle de l’ABP synthétisée par les Sertoli ?', answer: 'Transporter les androgènes vers la lumière des tubes séminifères.', },
{ question: 'Quel est le rôle de l’inhibine et de l’activine ?', answer: 'Participer à la régulation hormonale de la spermatogenèse.', },
{ question: 'Par quelles cellules l’AMH est-elle synthétisée pendant l’embryogenèse ?', answer: 'Les cellules de Sertoli et pré-sertoliennes.', },
{ question: 'Quel type de jonctions forme la barrière hématotesticulaire ?', answer: 'Des jonctions serrées continues entre cellules de Sertoli.', },
{ question: 'Quels sont les deux compartiments séparés par la barrière hématotesticulaire ?', answer: 'Compartiment basal et compartiment adluminal.', },
{ question: 'Quels éléments du cytosquelette des Sertoli participent à la progression des cellules germinales ?', answer: 'Microtubules, microfilaments d’actine et filaments intermédiaires de vimentine.', },
{ question: 'Comment les corps résiduels sont-ils éliminés ?', answer: 'Par phagocytose des cellules de Sertoli.', },
{ question: 'Comment s’appelle la libération des spermatozoïdes dans la lumière ?', answer: 'La spermiation.', },
{ question: 'Quelle protéase intervient dans la spermiation ?', answer: 'L’activateur du plasminogène.', },
{ question: 'Que sont les complexes tubulo-bulbaires ?', answer: 'Des structures d’ancrage des cellules germinales dans le cytoplasme des Sertoli.', },
{ question: 'Où se situe le tissu interstitiel testiculaire ?', answer: 'Dans les espaces compris entre les tubes séminifères.', },
{ question: 'Quel est le type principal de tissu constituant le tissu interstitiel ?', answer: 'Du tissu conjonctif lâche.', },
{ question: 'Quels types cellulaires conjonctifs retrouve-t-on dans le tissu interstitiel ?', answer: 'Fibroblastes, lymphocytes et macrophages.', },
{ question: 'Quel rôle joue le tissu interstitiel dans la régulation intragonadique ?', answer: 'Une fonction de régulation paracrine.', },
{ question: 'Quels vaisseaux sont présents dans le tissu interstitiel ?', answer: 'Des vaisseaux sanguins et lymphatiques.', },
{ question: 'Quel réseau cellulaire entoure les vaisseaux sanguins proches de la gaine péritubulaire ?', answer: 'Les Co-cells (fibroblastes).', },
{ question: 'Quel est le rôle des Co-cells ?', answer: 'Pousser les vaisseaux à se rapprocher de la gaine péritubulaire.', },
{ question: 'Quelles cellules endocrines sont présentes dans le tissu interstitiel ?', answer: 'Les cellules de Leydig.', },
{ question: 'Que sécrètent les cellules de Leydig ?', answer: 'Les androgènes testiculaires, principalement la testostérone.', },
{ question: 'Quel type de cellule sont les cellules de Leydig ?', answer: 'Des cellules endocrines.', },
{ question: 'Où les cellules de Leydig libèrent-elles la testostérone ?', answer: 'Dans la circulation sanguine.', },
{ question: 'Quelle est la taille des cellules de Leydig ?', answer: 'Entre 15 μm et 20 μm de diamètre.', },
{ question: 'Sous quelle forme les cellules de Leydig peuvent-elles se présenter ?', answer: 'Isolées ou groupées en amas autour des capillaires sanguins et lymphatiques.', },
{ question: 'Quelles sont les caractéristiques cytologiques des cellules élaborant des stéroïdes ?', answer: 'Noyau rond excentré avec nucléole volumineux, REL très développé, nombreuses mitochondries à crêtes tubulaires.', },
{ question: 'Quelles inclusions peut contenir le cytoplasme des cellules de Leydig ?', answer: 'Des inclusions lipidiques, pigmentaires ou protidiques comme le cristalloïde de Reinke.', },
{ question: 'Quel est le rôle du cristalloïde de Reinke ?', answer: 'La sécrétion de testostérone.', },
{ question: 'Quel est le rôle des voies génitales excrétrices ?', answer: 'Transporter les spermatozoïdes des tubes séminifères jusqu’à l’urètre et au méat urinaire lors de l’éjaculation.', },
{ question: 'Quelles structures comprennent les voies génitales excrétrices ?', answer: 'Les voies spermatiques intra-testiculaires, les canaux efférents, le canal épididymaire et le canal déférent.', },
{ question: 'Que sont les tubes droits ?', answer: 'De courts segments faisant suite aux tubes séminifères, d’environ 25 µm de diamètre.', },
{ question: 'À quoi correspondent les tubes droits dans chaque lobule ?', answer: 'À la confluence des 2 ou 3 tubes séminifères.', },
{ question: 'Quel type d’épithélium tapisse les tubes droits ?', answer: 'Une seule assise de cellules cubiques (cellules de Sertoli transformées).', },
{ question: 'Quel est le rôle des tubes droits ?', answer: 'Assurer la jonction entre les tubes séminifères et le rete testis.', },
{ question: 'Qu’est-ce que le rete testis ?', answer: 'Un réseau de canalicules anastomosés dans le corps de Highmore.', },
{ question: 'Quel type de cellules tapisse le rete testis ?', answer: 'Des cellules épithéliales aplaties reposant sur une membrane basale.', },
{ question: 'Que sont les canaux efférents ?', answer: 'Des canaux émergeant de la partie supérieure du rete testis, traversant l’albuginée.', },
{ question: 'Comment est la morphologie d’un canal efférent ?', answer: 'Un canal enroulé en spirale, formant un cône.', },
{ question: 'Que forme la confluence des canaux efférents ?', answer: 'Le segment initial du canal épididymaire.', },
{ question: 'Quel épithélium borde les canaux efférents ?', answer: 'Un épithélium prismatique simple.', },
{ question: 'Quels sont les types de cellules des canaux efférents ?', answer: 'Cellules ciliées, cellules glandulaires et cellules basales sporadiques.', },
{ question: 'Comment les spermatozoïdes sont-ils transportés dans les canaux efférents ?', answer: 'Par la pression intra-testiculaire, le mouvement des cils et le péristaltisme des cellules musculaires lisses.', },
{ question: 'Quel rôle chimique jouent les cellules glandulaires des canaux efférents ?', answer: 'Modifier la composition biochimique du liquide séminal par sécrétion et réabsorption.', },
{ question: 'Quelle est la longueur du canal épididymaire ?', answer: '3 à 6 mètres.', },
{ question: 'Quels sont les trois segments du canal épididymaire ?', answer: 'La tête, le corps et la queue.', },
{ question: 'Quel type d’épithélium borde le canal épididymaire ?', answer: 'Un épithélium prismatique pseudostratifié.', },
{ question: 'Quels sont les deux types cellulaires de l’épithélium épididymaire ?', answer: 'Les cellules principales à stéréocils et les cellules basales.', },
{ question: 'Quel est le rôle des stéréocils ?', answer: 'Permettre les échanges avec les spermatozoïdes (pinocytose/endocytose).', },
{ question: 'Comment évolue la couche musculaire lisse du canal épididymaire ?', answer: 'Elle s’épaissit de la tête vers la queue.', },
{ question: 'Quelle est la durée du transit épididymaire ?', answer: '1 jour dans la tête et 5 jours dans le corps et la queue.', },
{ question: 'Qu’est-ce que la maturation épididymaire des spermatozoïdes ?', answer: 'L’acquisition du pouvoir fécondant par modifications biochimiques.', },
{ question: 'Quels paramètres membranaires sont modifiés durant la maturation ?', answer: 'Mobilité, reconnaissance, fixation à la pellucide et protection de la chromatine.', },
{ question: 'Quels ions diminuent dans la lumière épididymaire ?', answer: 'Na+ et Cl−.', },
{ question: 'Quels ions augmentent dans la lumière épididymaire ?', answer: 'K+ et phosphate.', },
{ question: 'Comment évolue le pH dans l’épididyme ?', answer: 'Il diminue de 7,3 à 6,5 (acidification).', },
{ question: 'Quel pourcentage du fluide testiculaire est réabsorbé dans la tête de l’épididyme ?', answer: '90%.', },
{ question: 'Quels éléments sont réabsorbés dans la tête ?', answer: 'H2O, protéines spécifiques, ABP-androgènes, 5α-réductase, transferrine.', },
{ question: 'Quels éléments sont synthétisés dans la tête et le corps ?', answer: 'Protéines et glycoprotéines impliquées dans la fixation à la pellucide, prévention de la réaction acrosomique et mobilité.', },
{ question: 'Que concentre le corps de l’épididyme ?', answer: 'Carnitine et acétyl-carnitine.', },
{ question: 'Que synthétise la queue de l’épididyme ?', answer: 'Des lipides provenant des acides gras sanguins.', },
{ question: 'Quel est le rôle principal des protéines du fluide épididymaire ?', answer: 'Protection et maturation des spermatozoïdes.', },
{ question: 'Quels antioxydants protègeant les spermatozoïdes trouvent-on dans le fluide épididymaire ?', answer: 'GPX5, SOD1, beta-défensine.', },
{ question: 'Quels transporteurs hydrophobes figurent dans le fluide épididymaire ?', answer: 'SHBG et VitD binding protein.', },
{ question: 'Quels changements lipidiques assurent la stabilité membranaire ?', answer: 'Augmentation des stérols et diminution des phospholipides.', },
{ question: 'Quel mécanisme nucléaire se produit durant la maturation ?', answer: 'Condensation de la chromatine par ponts disulfures.', },
{ question: 'Quel est le rôle des enzymes acrosomiques ?', answer: 'Elles maturent de proacrosine en acrosine.', },
{ question: 'Quels mécanismes assurent l’acquisition de la mobilité ?', answer: 'Maturation de la machinerie du flagelle, augmentation d’AMPc, activation de la PKA et spiralisation des mitochondries.', },
{ question: 'Quel épithélium borde la lumière du canal déférent ?', answer: 'Un épithélium prismatique pseudostratifié à stéréocils.', },
{ question: 'Combien de couches comporte la tunique musculaire du canal déférent ?', answer: 'Trois couches : longitudinale interne, circulaire moyenne et longitudinale externe.', },
{ question: 'Qu’est-ce que l’ampoule déférentielle ?', answer: 'Une dilatation terminale du canal déférent recevant les vésicules séminales.', },
{ question: 'Qu’est-ce que la vasectomie ?', answer: 'La section et la ligature des deux canaux déférents.', },
{ question: 'Où sont stockés les spermatozoïdes entre deux éjaculations ?', answer: 'Dans les ampoules déférentielles.', },
{ question: 'Quelle est la fonction du canal déférent ?', answer: 'Le transport et le stockage des spermatozoïdes.', },
{ question: 'Quel est le rôle de l’urètre dans la reproduction ?', answer: 'Expulser l’urine et le sperme.', },
{ question: 'Quels sont les trois segments de l’urètre masculin ?', answer: 'Urètre prostatique, urètre membraneux et urètre spongieux.', },
{ question: 'Comment évolue l’épithélium urétral ?', answer: 'Urinaire en haut, cubique stratifié, puis pavimenteux stratifié non kératinisé.', },
{ question: 'Quelles glandes sont présentes dans le chorion urétral ?', answer: 'Les glandes de Littré.', },
{ question: 'Quelle est la composition du pénis ?', answer: 'Un corps spongieux médian et deux corps caverneux.', },
{ question: 'Quels sont les renflements du corps spongieux ?', answer: 'Le bulbe et le gland.', },
{ question: 'Quel tissu entoure les corps érectiles ?', answer: 'L’albuginée.', },
{ question: 'Quels phénomènes permettent l’érection ?', answer: 'Un phénomène vasculaire et un phénomène musculaire.', },
{ question: 'Où se branchent les vésicules séminales ?', answer: 'Sur la partie terminale du canal déférent au niveau du canal éjaculateur.', },
{ question: 'Quel est le rôle principal des vésicules séminales ?', answer: 'Élaborer une grande partie du plasma séminal.', },
{ question: 'Quel nutriment essentiel du sperme est sécrété par les vésicules séminales ?', answer: 'Le fructose.', },
{ question: 'Quelles protéines importantes sont sécrétées par les vésicules séminales ?', answer: 'Lactoferrine et prostaglandines.', },
{ question: 'Où est située la prostate ?', answer: 'Sous la vessie, autour de l’urètre prostatique.', },
{ question: 'Quelle est la masse approximative de la prostate ?', answer: 'Environ 20 g.', },
{ question: 'Combien de glandes tubulo-alvéolaires comprend la prostate ?', answer: 'Environ 50.', },
{ question: 'Quels sont les trois groupes concentriques de glandes prostatiques ?', answer: 'Glandes de la muqueuse, de la sous-muqueuse et glandes principales.', },
{ question: 'Quelles formations peuvent apparaître dans la lumière des glandes prostatiques ?', answer: 'Les concrétions prostatiques ou sympexions de Robin.', },
{ question: 'Quelle enzyme est un marqueur de la fonction prostatique ?', answer: 'La phosphatase acide.', },
{ question: 'Quel est le rôle de la sécrétion prostatique ?', answer: 'Assurer des éléments nécessaires à la survie des spermatozoïdes.', },
{ question: 'Quelle proportion de l’éjaculat représente la sécrétion prostatique ?', answer: 'Environ 1/6e.', },
{ question: 'Quels ions importants sont sécrétés par la prostate ?', answer: 'Zn, Mg et Ca.', },
{ question: 'Quelles sont les glandes de Cowper ?', answer: 'Des glandes tubulo-alvéolaires situées sur le trajet de l’urètre.', },
{ question: 'Quelle est la fonction des glandes de Cowper ?', answer: 'La lubrification de l’urètre et la protection des spermatozoïdes contre l’urine acide.', },