{ question: 'Qu’existe-t-il entre le développement des cellules germinales primordiales et celui des gonades ?', answer: 'Une séparation spatiotemporelle.', },
{ question: 'Que signifie l’abréviation CGP ?', answer: 'Primordial Germ Cell ou gonocyte.', },
{ question: 'De quel feuillet embryonnaire naissent les cellules germinales primordiales ?', answer: 'De l’épiblaste (ectoderme embryonnaire).', },
{ question: 'À quel moment apparaissent les CGP ?', answer: 'Vers 22 à 24 jours.', },
{ question: 'Quel phénomène caractérise la formation des CGP au moment de leur apparition ?', answer: 'Beaucoup de mitoses.', },
{ question: 'Où les CGP s’isolent-elles initialement ?', answer: 'Dans la paroi de la vésicule vitelline, dans la splanchnopleure extra-embryonnaire.', },
{ question: 'À quel moment les CGP s’isolent-elles dans la vésicule vitelline ?', answer: 'Vers la 3e semaine.', },
{ question: 'Quel trajet effectuent les CGP pour rejoindre leur futur site ?', answer: 'Elles remontent le long du tube digestif postérieur.', },
{ question: 'Où migrent les CGP en fin de trajet ?', answer: 'Dans la région du mésonéphros (rein intermédiaire).', },
{ question: 'À quel moment les CGP atteignent-elles le mésonéphros ?', answer: 'Vers la 5e semaine.', },
{ question: 'Quelle structure les CGP envahissent-elles après migration ?', answer: 'Les crêtes génitales.', },
{ question: 'Quand apparaissent les crêtes génitales ?', answer: 'Dès la 4e semaine.', },
{ question: 'De quels tissus dérivent les crêtes génitales ?', answer: 'Du mésenchyme et de l’épithélium cœlomique.', },
{ question: 'Que se passe-t-il à la 6e semaine au niveau de l’épithélium cœlomique ?', answer: 'Les cellules forment des agrégats de cellules somatiques de soutien entourant totalement les cellules germinales.', },
{ question: 'Comment s’appellent les structures formées à la 6e semaine par les cellules somatiques et les gonocytes ?', answer: 'Les cordons sexuels primitifs (CSP).', },
{ question: 'Quel déterminisme oriente la différenciation testiculaire ?', answer: 'Le chromosome Y et le gène SRY.', },
{ question: 'Que font les cordons sexuels primitifs après formation ?', answer: 'Ils prolifèrent, envahissent la zone médullaire et se détachent de l’épithélium cœlomique.', },
{ question: 'Que deviendront les cordons sexuels primitifs détachés du cœlome ?', answer: 'Des cordons testiculaires.', },
{ question: 'Que permet la différenciation de la gonade primitive en testicule ?', answer: 'La formation de cordons séminifères primitifs.', },
{ question: 'Quels types cellulaires composent les cordons séminifères primitifs ?', answer: 'CGPs et cellules de Sertoli.', },
{ question: 'Quel devient l’état de maturation des CGP dans les cordons séminifères primitifs ?', answer: 'Elles bloquent leur maturation au stade de futures cellules souches de la spermatogenèse.', },
{ question: 'Que trouve-t-on entre les cordons primitifs ?', answer: 'Du mésenchyme contenant des cellules de Leydig et des fibroblastes.', },
{ question: 'Quel aspect prennent les cordons testiculaires au 4e mois ?', answer: 'Un aspect de fer à cheval.', },
{ question: 'Avec quoi les extrémités des cordons testiculaires sont-elles en continuité ?', answer: 'Avec des cordons cellulaires du rete testis.', },
{ question: 'Que se passe-t-il au moment de la puberté concernant les cordons testiculaires ?', answer: 'Ils se creusent d’une lumière et deviennent des tubes séminifères.', },
{ question: 'Que reprend à la puberté au niveau des cellules germinales ?', answer: 'La maturation des cellules germinales.', },
{ question: 'Quel processus débute à la puberté et devient continu ?', answer: 'La spermatogenèse ou production de gamètes matures.', },
{ question: 'Quel est l’évènement clé de la différenciation des cellules germinales ?', answer: 'La méiose.', },
{ question: 'Qu’est-ce que la spermatogenèse ?', answer: 'La gamétogenèse mâle, processus de multiplication et de différenciation aboutissant aux spermatozoïdes.', },
{ question: 'Quand débute la spermatogenèse ?', answer: 'Après la puberté.', },
{ question: 'À partir de quelles cellules débute la spermatogenèse ?', answer: 'À partir des spermatogonies (cellules souches germinales).', },
{ question: 'Quelle est la durée de la spermatogenèse chez l’homme ?', answer: '74 jours.', },
{ question: 'De quel type est la spermatogenèse ?', answer: 'Un phénomène continu à partir de la puberté.', },
{ question: 'Où se déroule la spermatogenèse ?', answer: 'Dans les testicules, dans la paroi des tubes séminifères, dans l’épithélium germinal.', },
{ question: 'Quel sens suit la différenciation germinale dans les tubes séminifères ?', answer: 'Un mode centripète, de la base vers la lumière.', },
{ question: 'Quelle est la fonction exocrine du testicule ?', answer: 'La production des gamètes mâles.', },
{ question: 'Quels types cellulaires composent l’épithélium séminifère ?', answer: 'Cellules de Sertoli et cellules germinales à tous les stades.', },
{ question: 'Quelles sont les trois phases de la spermatogenèse ?', answer: 'Multiplication spermatogoniale, méiose, spermiogenèse.', },
{ question: 'Quels sont les trois types cellulaires de la lignée germinale masculine ?', answer: 'Spermatogonies, spermatocytes, spermatides.', },
{ question: 'Où se situent les spermatogonies ?', answer: 'À la périphérie du tube séminifère, près de la membrane basale.', },
{ question: 'Où se situent les spermatocytes ?', answer: 'À l’étage moyen du tube.', },
{ question: 'Où se situent les spermatides ?', answer: 'Autour de la lumière du tube.', },
{ question: 'Quelle est la durée de la phase de prolifération des spermatogonies ?', answer: 'Environ 27 jours.', },
{ question: 'Que forment les divisions spermatogoniales ?', answer: 'Les précurseurs des spermatocytes I.', },
{ question: 'Quels types de divisions effectuent les spermatogonies ?', answer: 'Symétriques (auto-renouvellement) et asymétriques (différenciation).', },
{ question: 'Qu’assure l’homéostasie du pool spermatogonial ?', answer: 'L’équilibre mitose/apoptose.', },
{ question: 'Pourquoi la cytocinèse des spermatogonies est-elle incomplète ?', answer: 'Car les cellules restent reliées par des ponts cytoplasmiques formant un syncytium.', },
{ question: 'Quel est l’intérêt du syncytium spermatogonial ?', answer: 'Assurer la synchronisation des divisions et de la méiose.', },
{ question: 'Quels sont les trois types de spermatogonies observables en microscopie photonique ?', answer: 'Ad (dark), Ap (pale), B.', },
{ question: 'Quel est l’aspect du noyau des spermatogonies Ad ?', answer: 'Noyau arrondi, chromatine fine très colorable.', },
{ question: 'Quelle est la caractéristique des spermatogonies Ad ?', answer: 'Division symétrique.', },
{ question: 'Quel est l’aspect du noyau des spermatogonies Ap ?', answer: 'Ovalaire, elles se différencient en B.', },
{ question: 'Quel est l’aspect des spermatogonies B ?', answer: 'Noyau arrondi et foncé, chromatine en amas.', },
{ question: 'Que donnent directement les spermatogonies B ?', answer: 'Les spermatocytes I.', },
{ question: 'Quelle est la définition générale de la méiose ?', answer: 'Processus aboutissant à des gamètes haploïdes.', },
{ question: 'Quelle est la conséquence chromosomique de la méiose ?', answer: 'Réduction de 2n à n, 1 chromosome de chaque paire.', },
{ question: 'Combien de divisions comporte la méiose ?', answer: 'Deux : méiose I et méiose II.', },
{ question: 'Quel est le rôle global de la méiose ?', answer: 'Transmission génétique et brassage génétique par crossing-over.', },
{ question: 'Quelle est la durée de la méiose I ?', answer: 'Longue, 23 jours.', },
{ question: 'Quel type de division est la méiose I ?', answer: 'Une division réductionnelle.', },
{ question: 'Quel est l’état chromosomique avant et après la méiose I ?', answer: 'De 2×23 chromosomes 4n ADN à 1×23 chromosomes 2n ADN.', },
{ question: 'Quels sont les quatre stades de la division ?', answer: 'Prophase, métaphase, anaphase, télophase.', },
{ question: 'Quelles cellules effectuent la méiose I ?', answer: 'Les spermatocytes I.', },
{ question: 'Quel type de division est la méiose II ?', answer: 'Une division équationnelle.', },
{ question: 'Quelle transformation se produit en méiose II ?', answer: 'Séparation des chromatides sœurs.', },
{ question: 'Quelle cellule effectue la méiose II ?', answer: 'Le spermatocyte II.', },
{ question: 'Quels sont les trois aspects d’analyse de la méiose ?', answer: 'Cytologique, chromosomique et génétique.', },
{ question: 'Quelle est la durée de la prophase I ?', answer: 'Très longue, environ 15 jours.', },
{ question: 'Quels sont les cinq stades de la prophase I ?', answer: 'Leptotène, zygotène, pachytène, diplotène, diacinèse.', },
{ question: 'Que se passe-t-il lors de l’appariement des chromosomes homologues ?', answer: 'Formation de synapsis par complexes synaptonémaux et crossing-over.', },
{ question: 'Quelle structure mime une fermeture éclair durant la prophase I ?', answer: 'Le complexe synaptonémal.', },
{ question: 'À quel stade le complexe synaptonémal est-il complet ?', answer: 'Au pachytène.', },
{ question: 'Quels éléments composent le complexe synaptonémal ?', answer: 'Éléments latéraux, élément central et filaments transverses.', },
{ question: 'Quelle famille protéique participe aux éléments latéraux ?', answer: 'Les SMCs, dont les cohésines.', },
{ question: 'À quoi servent les recombinaisons génétiques ?', answer: 'À créer de nouvelles combinaisons de gènes soumises à la sélection naturelle.', },
{ question: 'Quel est le stade le plus visible des spermatocytes en coupe ?', answer: 'Le pachytène.', },
{ question: 'Où sont situés les spermatocytes I en coupe ?', answer: 'À distance de la membrane basale.', },
{ question: 'Quel passage accompagne l’entrée en méiose au niveau des compartiments ?', answer: 'Le passage du compartiment basal au compartiment adluminal.', },
{ question: 'À quel stade a lieu ce passage de compartiment ?', answer: 'Au leptotène précoce.', },
{ question: 'Que doivent faire les jonctions serrées de Sertoli lors du passage ?', answer: 'S’ouvrir pour laisser passer les cellules germinales puis se refermer.', },
{ question: 'Quels éléments constituent la barrière hématotesticulaire ?', answer: 'Endothélium des capillaires, cellules péritubulaires, membrane basale, jonctions serrées entre Sertoli.', },
{ question: 'Quel est le rôle de la barrière hématotesticulaire ?', answer: 'Isoler les cellules germinales post-méiotiques du système immunitaire.', },
{ question: 'Quelles cellules subissent la spermiogenèse ?', answer: 'Les spermatides, cellules haploïdes issues des spermatocytes II.', },
{ question: 'La spermiogenèse implique-t-elle encore des divisions cellulaires ?', answer: 'Non, il n’y a plus de division cellulaire.', },
{ question: 'En quoi les spermatocytes II se transforment-ils avant de devenir des spermatozoïdes ?', answer: 'Ils deviennent d’abord des spermatides puis des spermatozoïdes.', },
{ question: 'Quelles sont les trois familles de spermatides ?', answer: 'Spermatides jeunes ou rondes, spermatides intermédiaires en cours d’élongation, spermatides matures ou allongées.', },
{ question: 'Combien de stades de division des spermatides existe-t-il chez l’homme ?', answer: 'Huit stades.', },
{ question: 'Quelle est la durée de la spermiogenèse ?', answer: '23 jours.', },
{ question: 'Quels sont les grands types de modifications subies par les spermatides ?', answer: 'Formation de l’acrosome, remaniements nucléaires, développement du flagelle, réduction cytoplasmique et spermiation.', },
{ question: 'De quoi dérive l’acrosome ?', answer: 'De la fusion de vésicules golgiennes contenant des enzymes hydrolytiques.', },
{ question: 'Quelles membranes possède l’acrosome ?', answer: 'Une membrane acrosomique interne et une externe.', },
{ question: 'À quoi sert l’acrosome ?', answer: 'À permettre au spermatozoïde de traverser les cellules entourant l’ovocyte.', },
{ question: 'Comment se forme la vésicule acrosomale ?', answer: 'Par fusion de vacuoles issues de l’appareil de Golgi contenant des granules pro-acrosomiaux.', },
{ question: 'Quelle portion du noyau est coiffée par l’acrosome ?', answer: 'Les deux tiers antérieurs du noyau.', },
{ question: 'Quand ont lieu les remaniements nucléaires durant la spermiogenèse ?', answer: 'Dans la deuxième moitié de la spermiogenèse.', },
{ question: 'À quoi est due l’élongation du noyau ?', answer: 'À l’accrochage de microtubules formant la manchette à l’enveloppe nucléaire.', },
{ question: 'Quelles protéines remplacent les histones lors de la condensation du génome ?', answer: 'Les protamines.', },
{ question: 'Quel est le rôle des protamines ?', answer: 'Permettre la condensation de l’ADN déroulé.', },
{ question: 'Que devient le complexe d’histones lors de la spermiogenèse ?', answer: 'Son organisation change complètement, différente de celle des protamines.', },
{ question: 'Quel événement marque le début du développement du flagelle ?', answer: 'Le déplacement des deux centrioles au pôle postérieur du noyau.', },
{ question: 'Quelle structure assemble l’axonème ?', answer: 'Le centriole distal.', },
{ question: 'Comment se réorganise le cytoplasme durant la spermiogenèse ?', answer: 'Il glisse vers l’arrière du flagelle en formation et diminue de volume.', },
{ question: 'Qu’advient-il des corps résiduels formés durant la spermiogenèse ?', answer: 'Ils sont phagocytés par les cellules de Sertoli.', },
{ question: 'Comment se disposent les mitochondries dans le spermatozoïde en formation ?', answer: 'En gaine mitochondriale autour de la partie initiale du flagelle.', },
{ question: 'Quelle structure marque la limite de la gaine mitochondriale ?', answer: 'L’annulus.', },
{ question: 'Combien existe-t-il de stades dans le cycle de l’épithélium séminal chez l’homme ?', answer: 'Six stades.', },
{ question: 'À quoi correspondent les différents stades de l’épithélium séminal ?', answer: 'À des associations préférentielles de cellules germinales observées en coupe.', },
{ question: 'Quelles variations expliquent les six stades de l’épithélium séminal ?', answer: 'L’entrée en mitose cyclique des spermatogonies et la durée variable d’existence de chaque type cellulaire.', },
{ question: 'Quelle est la définition d’un spermatozoïde ?', answer: 'Le gamète mâle mature libéré dans la lumière des tubes séminifères.', },
{ question: 'Quelle est la fonction générale d’un spermatozoïde ?', answer: 'Atteindre le gamète femelle dans les voies génitales féminines.', },
{ question: 'Quels sont les deux grands pôles du spermatozoïde ?', answer: 'La tête et la queue, séparées par la pièce connective ou col.', },
{ question: 'Quelle est la taille approximative d’un spermatozoïde ?', answer: 'Environ 60 μm de long.', },
{ question: 'Quels sont les éléments majeurs que contient la tête du spermatozoïde ?', answer: 'Le noyau contenant le génome haploïde et l’acrosome.', },
{ question: 'Quelles sont les trois grandes régions du flagelle ?', answer: 'Le col, la pièce intermédiaire et la pièce principale.', },
{ question: 'Quelles structures entourent l’axonème au niveau du col ?', answer: 'De nombreuses mitochondries.', },
{ question: 'Quelles sont les structures présentes dans la pièce principale du flagelle ?', answer: 'Une gaine fibreuse mais plus de mitochondries.', },
{ question: 'Quelle est la structure de base de l’axonème ?', answer: '2 microtubules centraux et 9 doublets périphériques.', },
{ question: 'Quelles protéines assurent le mouvement flagellaire ?', answer: 'Les bras de dynéine internes et externes.', },
{ question: 'Quels liens stabilisent l’axonème ?', answer: 'Les liens de nexine.', },
{ question: 'Quelle hormone hypothalamique initie la régulation endocrine de la spermatogenèse ?', answer: 'La GnRH.', },
{ question: 'Quel est l’effet de la GnRH sur l’hypophyse ?', answer: 'Elle stimule de façon pulsatile la libération de FSH et LH.', },
{ question: 'Quel événement majeur la GnRH initie-t-elle à la puberté ?', answer: 'La différenciation des cellules germinales et l’enclenchement de la spermatogenèse.', },
{ question: 'Quel est le rôle de la FSH dans la spermatogenèse ?', answer: 'Elle agit sur les cellules de Sertoli pour stimuler inhibine B, activine et la spermatogenèse.', },
{ question: 'Quel type de rétrocontrôle assurent les cellules de Sertoli ?', answer: 'Feed-back négatif via inhibine ou positif via activine.', },
{ question: 'Quel est l’effet de la LH sur les cellules de Leydig ?', answer: 'Elle stimule la synthèse et la sécrétion de testostérone.', },
{ question: 'Quel est le type d’hypogonadisme dû à un défaut de l’axe hypothalamo-hypophysaire ?', answer: 'L’hypogonadisme hypogonadotrope.', },
{ question: 'Que caractérise l’hypogonadisme hypergonadotrope ?', answer: 'FSH et LH élevées mais mauvaise perception par les gonades.', },
{ question: 'Quelles sont les causes possibles d’une spermatogenèse déficiente ?', answer: 'Causes toxiques, environnementales, chromosomiques ou idiopathiques.', },
{ question: 'Que régule localement l’activité des cellules de Sertoli et Leydig ?', answer: 'Les cellules germinales.', },
{ question: 'Comment les cellules de Sertoli modulent-elles la testostérone ?', answer: 'En l’aromatisant en œstrogènes, en l’inhibant via TGFβ ou en la stimulant via IGF1.', },
{ question: 'Quel rôle ont les cellules péritubulaires sur les Sertoli ?', answer: 'Elles sécrètent P-Mod-S qui active la sécrétion d’ABP.', },
{ question: 'Quels facteurs médiateurs agissent entre Sertoli et cellules germinales ?', answer: 'Facteurs de croissance (EGF, NGF) et interleukines (IL1, IL6).', },
{ question: 'Quels gènes peuvent altérer la spermatogenèse lorsqu’ils sont mutés ?', answer: 'Les gènes situés dans les régions AZF a, b, c du chromosome Y.', },
{ question: 'Quels antécédents personnels peuvent nuire à la spermatogenèse ?', answer: 'Diabète, surpoids, infections (mycoplasmes, chlamydiae, oreillons), torsion testiculaire, varicocèle, cryptorchidie.', },
{ question: 'Quelles habitudes de vie peuvent altérer la spermatogenèse ?', answer: 'Tabac, alcool, drogues, chaleur.', },
{ question: 'Quels agents professionnels exposent à une altération de la spermatogenèse ?', answer: 'Chaleur, radiations ionisantes, métaux, herbicides, pesticides, solvants.', },
{ question: 'Quels traitements médicaux peuvent perturber la spermatogenèse ?', answer: 'Radiothérapie, chimiothérapie (alkylants+++, intercalants, antimétabolites, alcaloïdes) et certains médicaments.', },
