{ question: 'Quels sont les constituants de l’appareil génital féminin ?', answer: 'Les ovaires, les trompes de Fallope, l’utérus, le vagin, les organes génitaux externes (vulve) et les glandes annexes.', },
{ question: 'Quels organes représentent les gonades chez la femme ?', answer: 'Les ovaires.', },
{ question: 'Quels sont les organes des voies génitales internes féminines ?', answer: 'Les trompes de Fallope, l’utérus et le vagin.', },
{ question: 'Quels organes composent la vulve ?', answer: 'Les petites lèvres et les grandes lèvres.', },
{ question: 'Quelles sont les glandes annexes vulvo-vaginales ?', answer: 'Les glandes vulvo-vaginales.', },
{ question: 'Quelles sont les dimensions d’un ovaire ?', answer: '4 cm × 1,5 cm.', },
{ question: 'Quelle est la longueur des trompes de Fallope ?', answer: '10 à 12 cm.', },
{ question: 'Quelles sont les dimensions de l’utérus ?', answer: '4 à 5 cm de large et 7 à 8 cm de long.', },
{ question: 'Comment les ovaires sont-ils reliés à l’utérus ?', answer: 'Par les ligaments utéro-ovariens.', },
{ question: 'Quel méso relie l’ovaire à la trompe ?', answer: 'Le mésovarium.', },
{ question: 'De quoi est constitué le mésovarium ?', answer: 'De feuillets du péritoine recouvrant l’ovaire.', },
{ question: 'Quelles variations subissent les organes génitaux féminins entre puberté et ménopause ?', answer: 'Des modifications morphologiques et fonctionnelles liées au cycle ovulatoire.', },
{ question: 'Quelle est la durée moyenne du cycle menstruel ?', answer: '28 jours.', },
{ question: 'Quelle est la fonction exocrine des ovaires ?', answer: 'La production des gamètes (ovocytes).', },
{ question: 'Quelle est la fonction endocrine des ovaires ?', answer: 'La production de stéroïdes sexuels.', },
{ question: 'Quels rôles assurent les voies génitales féminines ?', answer: 'Accueil et transport des spermatozoïdes, fécondation, transit et implantation de l’œuf fécondé, développement de l’embryon puis du fœtus.', },
{ question: 'Combien d’ovaires possède une femme ?', answer: 'Deux.', },
{ question: 'Où sont situés les ovaires ?', answer: 'Latéralement, à droite et à gauche dans la cavité pelvienne.', },
{ question: 'Quelle est la fonction exocrine de l’ovaire ?', answer: 'La production d’ovocytes matures par la folliculogénèse.', },
{ question: 'Quelle est la fonction endocrine de l’ovaire ?', answer: 'La sécrétion d’hormones stéroïdes sexuelles.', },
{ question: 'Quel est l’unité morphologique fonctionnelle de l’ovaire ?', answer: 'Le follicule ovarien.', },
{ question: 'Les ovocytes sont-ils jamais isolés ?', answer: 'Non, ils sont toujours entourés de cellules folliculaires.', },
{ question: 'Sans ovocyte, y a-t-il sécrétion hormonale dans l’ovaire ?', answer: 'Non.', },
{ question: 'Quelles sont les trois composantes histologiques de l’ovaire ?', answer: 'Épithélium ovarien superficiel, albuginée ovarienne, cortex et médullaire.', },
{ question: 'Qu’est-ce que l’épithélium ovarien superficiel ?', answer: 'Un épithélium simple recouvrant la surface de l’ovaire.', },
{ question: 'Qu’est-ce que l’albuginée ovarienne ?', answer: 'Une couche de tissu conjonctif dense sous l’épithélium.', },
{ question: 'Quelles structures trouve-t-on dans le cortex ovarien ?', answer: 'Le stroma conjonctif et les follicules ovariens.', },
{ question: 'Que contient la médullaire ovarienne ?', answer: 'Tissu conjonctif, fibres musculaires lisses, vaisseaux sanguins et fibres nerveuses.', },
{ question: 'Comment se caractérise la zone corticale ?', answer: 'Zone dense, épaisseur variable, zone fonctionnelle contenant les follicules.', },
{ question: 'Comment est l’épithélium ovarien du cortex ?', answer: 'Cubique simple, improprement appelé épithélium germinatif.', },
{ question: 'Où se trouve l’albuginée dans le cortex ?', answer: 'Directement sous l’épithélium.', },
{ question: 'Quel tissu constitue le stroma conjonctif du cortex ?', answer: 'Un tissu conjonctif dense.', },
{ question: 'Où se trouvent les follicules primordiaux ?', answer: 'Dans la zone folliculaire du cortex.', },
{ question: 'Comment est organisé le tissu conjonctif de la médullaire ?', answer: 'En zone parenchymateuse lâche et zone hilaire dense.', },
{ question: 'Qu’est-ce que la zone hilaire ?', answer: 'Une zone dense contenant vaisseaux et nerfs, lieu d’ancrage de l’ovaire.', },
{ question: 'Quelle est la première cause d’infertilité féminine en âge de procréer ?', answer: 'Le syndrome des ovaires polykystiques (SOPK).', },
{ question: 'Quels sont les trois critères de Rotterdam du SOPK ?', answer: 'Oligo-anovulation, hyperandrogénie clinique ou biologique, ovaires polykystiques à l’échographie.', },
{ question: 'Quels troubles métaboliques peuvent accompagner le SOPK ?', answer: 'Obésité, insulino-résistance, syndrome métabolique, graisse viscérale, AMH et LH élevées.', },
{ question: 'Qu’est-ce que l’insuffisance ovarienne prématurée ?', answer: 'Peu de follicules en croissance et d’ovocytes, ménopause précoce, aménorrhée et infertilité.', },
{ question: 'Quels autres problèmes peuvent toucher l’ovaire ?', answer: 'Kystes, tumeurs borderlines, cancers.', },
{ question: 'Quelle est la longueur d’une trompe de Fallope ?', answer: '10 à 12 cm.', },
{ question: 'Quelles sont les quatre régions d’une trompe de Fallope ?', answer: 'Pavillon, ampoule, isthme, portion interstitielle.', },
{ question: 'Où a lieu la fécondation ?', answer: 'Dans l’ampoule tubaire, au tiers externe de la trompe.', },
{ question: 'Quel est le rôle du pavillon ?', answer: 'Aspirer l’ovocyte lors de l’ovulation grâce aux franges.', },
{ question: 'Quels mouvements permettent le transport tubaire ?', answer: 'Mouvements péristaltiques, activité des cellules ciliées et sécrétrices.', },
{ question: 'Quelles pathologies peuvent altérer les trompes ?', answer: 'Salpingites, obstructions, hydrosalpinx, grossesses extra-utérines.', },
{ question: 'Quelles sont les trois couches histologiques de la trompe ?', answer: 'Muqueuse, musculeuse, séreuse.', },
{ question: 'Quels types cellulaires composent la muqueuse tubaire ?', answer: 'Cellules ciliées, cellules sécrétrices, cellules basales.', },
{ question: 'Quand les cellules ciliées sont-elles les plus nombreuses ?', answer: 'En phase folliculaire (J4 à J14).', },
{ question: 'Quel est l’effet de la progestérone sur les cils tubaires ?', answer: 'Elle induit un mouvement centripète en phase lutéale.', },
{ question: 'Comment varie l’activité des cellules sécrétrices tubaires en fin de cycle ?', answer: 'Elles deviennent les plus volumineuses.', },
{ question: 'Quelle est la structure de la musculeuse tubaire ?', answer: 'Des cellules musculaires lisses à contractions rythmiques.', },
{ question: 'Qu’est-ce que la séreuse tubaire ?', answer: 'Une couche conjonctivo-élastique riche en vaisseaux, recouverte du mésothélium.', },
{ question: 'Quelles sont les dimensions de l’utérus ?', answer: '7 à 8 cm de long et 4 à 5 cm de large.', },
{ question: 'Quelles sont les trois régions anatomiques de l’utérus ?', answer: 'Le corps, l’isthme et le col.', },
{ question: 'Quelles sont les trois couches de la paroi utérine ?', answer: 'Endomètre, myomètre, séreuse.', },
{ question: 'Quelle est la couche la plus épaisse de l’utérus ?', answer: 'Le myomètre.', },
{ question: 'Quels sont les trois types de fibres dans le myomètre ?', answer: 'Fibres longitudinales profondes et circulaires superficielles, couche plexiforme, fibres longitudinales externes.', },
{ question: 'Qu’est-ce qu’un fibrome ?', answer: 'Une tumeur bénigne du myomètre composée de tissu musculaire et fibreux.', },
{ question: 'De quoi est constituée la muqueuse utérine ?', answer: 'Épithélium simple (cilié et sécrétrice) et chorion avec glandes tubuleuses.', },
{ question: 'Comment varie l’épaisseur de l’endomètre ?', answer: 'De 0,5 mm en début de cycle à 5 mm en période ovulatoire.', },
{ question: 'Quelles cellules composent le chorion ?', answer: 'Fibroblastes, cellules immunitaires, substance fondamentale riche, réseau de réticuline.', },
{ question: 'Qu’est-ce que l’endocol ?', answer: 'Le canal cervical, avec un épithélium cylindrique simple cilié et sécrétrices.', },
{ question: 'Que produit le mucus cervical ?', answer: 'Une glaire dont la qualité varie selon le cycle, translucide à l’ovulation.', },
{ question: 'Quel épithélium recouvre l’exocol ?', answer: 'Un épithélium pavimenteux stratifié non kératinisé.', },
{ question: 'Quelle infection cause des lésions cervicales fréquentes ?', answer: 'Le HPV.', },
{ question: 'Quel est le rôle du vagin ?', answer: 'Canal musculo-membraneux entre col de l’utérus et vulve.', },
{ question: 'Quel type d’épithélium possède le vagin ?', answer: 'Pavimenteux stratifié non kératinisé en 4 couches.', },
{ question: 'Quel rôle joue le glycogène vaginal ?', answer: 'Il est métabolisé par les bacilles de Döderlein en acide lactique, responsable du pH bas.', },
{ question: 'Comment est organisé le chorion vaginal ?', answer: 'Tissu conjonctif lâche riche en fibres élastiques, très vascularisé et sans glandes.', },
{ question: 'Quelles sont les couches musculaires du vagin ?', answer: 'Interne circulaire et externe longitudinale.', },
{ question: 'Quels sont les deux phases cycliques de l’épithélium vaginal ?', answer: 'Phase oestrogénique (prolifération) et phase lutéale (desquamation).', },
{ question: 'Quelles hormones régulent le cycle menstruel ?', answer: 'Œstrogènes et progestérone.', },
{ question: 'Quelles sont les trois phases du cycle ovarien ?', answer: 'Phase folliculaire (J1-J14), ovulation (J14), phase lutéale (J14-J28).', },
{ question: 'Quelle est la phase du cycle endométrial correspondant aux règles ?', answer: 'La phase de desquamation (J1-J4).', },
{ question: 'Que provoque la chute d’œstrogènes et de progestérone ?', answer: 'Une vasoconstriction des artères spiralées et la desquamation de la zone fonctionnelle.', },
{ question: 'Quelle couche persiste après la menstruation ?', answer: 'La couche basale (zone résiduelle).', },
{ question: 'Que se passe-t-il durant la phase proliférative (J5-J14) ?', answer: 'Reconstruction de l’endomètre, mitoses nombreuses, glandes rectilignes, croissance vasculaire.', },
{ question: 'Quelle hormone domine la phase proliférative ?', answer: 'Les œstrogènes.', },
{ question: 'Que provoque la progestérone dans la phase sécrétoire (J15-J28) ?', answer: 'Transformation glandulaire, sécrétion, “dentelle utérine”, œdème du chorion.', },
{ question: 'Quand le chorion présente-t-il un œdème maximal ?', answer: 'Vers le 21e jour du cycle.', },
{ question: 'Que devient l’endomètre en phase sécrétoire ?', answer: 'Glandes longues et sinueuses, glycogène du pôle basal vers le pôle apical.', },
