{ question: 'Quels sont les deux phénomènes étroitement liés en reproduction féminine ?', answer: 'L’ovogenèse et la folliculogenèse.', },
{ question: 'Que décrit la folliculogenèse ?', answer: 'Le développement des follicules du stade primordial jusqu’à la libération d’un ovocyte mature.', },
{ question: 'Que décrit l’ovogenèse ?', answer: 'Le développement des ovocytes.', },
{ question: 'De quoi dépendent ovogenèse et folliculogenèse ?', answer: 'Du contrôle de l’axe hypothalamo-hypophysaire et de facteurs locaux.', },
{ question: 'Qu’est-ce qui constitue un follicule ?', answer: 'Un ovocyte entouré de cellules folliculaires.', },
{ question: 'Quel est l’objectif général de l’ovogenèse ?', answer: 'Obtenir un ovocyte mature de qualité.', },
{ question: 'À quel stade est bloqué l’ovocyte mature ?', answer: 'En métaphase de deuxième division de méiose.', },
{ question: 'De quoi est entouré l’ovocyte mature ?', answer: 'De la zone pellucide et séparé d’elle par l’espace périvitellin contenant le globule polaire.', },
{ question: 'Qu’est-ce que le follicule primordial ?', answer: 'Un follicule immature contenant un ovocyte.', },
{ question: 'Que devient le follicule après ovulation en absence de grossesse ?', answer: 'Le corps jaune régresse en corps blanc.', },
{ question: 'Quelles cellules entourent l’ovocyte dans le follicule ?', answer: 'Les cellules de la granulosa (péri-ovocytaires), et les cellules de la thèque interne et externe.', },
{ question: 'Quand débute l’ovogenèse ?', answer: 'Durant la vie fœtale, liée à la multiplication des cellules germinales primordiales.', },
{ question: 'L’ovogenèse est-elle continue ou discontinue ?', answer: 'Discontinue.', },
{ question: 'Quels sont les deux blocages successifs de l’ovocyte ?', answer: 'En prophase I (diplotène) et en métaphase II.', },
{ question: 'Que deviennent les gonocytes dès la 5e semaine de développement ?', answer: 'Ils envahissent les gonades et deviennent des ovogonies.', },
{ question: 'À partir de quel moment les ovogonies entrent-elles en méiose ?', answer: 'Vers le 3e mois de vie embryonnaire.', },
{ question: 'Quel est le stade du premier blocage méiotique ?', answer: 'Prophase I, stade diplotène.', },
{ question: 'Comment s’appelle l’enveloppe nucléaire de l’ovocyte I ?', answer: 'La vésicule germinative.', },
{ question: 'Quel est le nombre maximal d’ovocytes en vie fœtale ?', answer: '3 à 7 millions au 7e mois.', },
{ question: 'Quand l’ovogenèse reprend-elle ?', answer: 'À la puberté.', },
{ question: 'Quel est l’effet du pic de LH sur l’ovocyte ?', answer: 'Reprise de la méiose, 1re division, expulsion du premier globule polaire.', },
{ question: 'À quel stade l’ovocyte II est-il bloqué ?', answer: 'En métaphase II.', },
{ question: 'Quand se termine la méiose ?', answer: 'Uniquement en cas de fécondation.', },
{ question: 'Que produit l’achèvement de la méiose après fécondation ?', answer: 'Un deuxième globule polaire et un zygote.', },
{ question: 'Quel est le rôle unique du spermatozoïde pour l’ovocyte ?', answer: 'Permettre à l’ovocyte de terminer sa différenciation.', },
{ question: 'Quelle est la taille d’un ovocyte mature ?', answer: '120 à 130 µm.', },
{ question: 'Quelles sont les trois phases de l’ovogenèse ?', answer: 'Multiplication, croissance et maturation.', },
{ question: 'Quel est le stade obtenu à la fin de la multiplication ?', answer: 'L’ovocyte I bloqué en prophase I.', },
{ question: 'Quand débute la phase de multiplication ?', answer: 'Dès l’arrivée des CGP dans les gonades.', },
{ question: 'Quelle est la quantité maximale d’ovogonies au 7e mois ?', answer: '6 à 7 millions.', },
{ question: 'Quel facteur induit l’entrée en méiose ?', answer: 'L’acide rétinoïque (RA).', },
{ question: 'Quels facteurs inhibent l’entrée prématurée en méiose ?', answer: 'AMH et NANOS2.', },
{ question: 'Quelle quantité d’ADN possède un ovocyte I ?', answer: '2N chromosomes, 4q d’ADN au total.', },
{ question: 'Comment se forment les follicules primordiaux ?', answer: 'Association d’un ovocyte I et d’une couche de cellules folliculaires aplaties.', },
{ question: 'Quand débute la croissance ovocytaire ?', answer: 'Après la naissance.', },
{ question: 'Quelle est la taille de l’ovocyte en début et fin de croissance ?', answer: '30 µm dans le follicule primordial et 120 µm avant le pic de LH.', },
{ question: 'Quelles sont les deux compétences acquises par l’ovocyte ?', answer: 'Compétence à reprendre la méiose et compétence au développement.', },
{ question: 'De quoi dépend la reprise de la méiose ?', answer: 'Diminution d’AMPc, dégradation des jonctions GAP, diminution d’OMI.', },
{ question: 'Quel événement déclenche la reprise de la méiose ?', answer: 'Le pic de LH.', },
{ question: 'Quel rôle ont MAS et MPF ?', answer: 'Activer la méiose.', },
{ question: 'Quel ion intracellulaire participe à la reprise méiotique ?', answer: 'Le calcium.', },
{ question: 'Combien d’heures après le pic de LH commence la maturation ?', answer: '15 heures.', },
{ question: 'Quelles sont les trois maturations nécessaires pour rendre l’ovocyte fécondable ?', answer: 'Maturation nucléaire, cytoplasmique, membranaire.', },
{ question: 'Qu’est-ce que la GVBD ?', answer: 'La rupture de la vésicule germinative.', },
{ question: 'Quand survient l’expulsion du premier globule polaire ?', answer: 'Environ 20h après le pic de LH.', },
{ question: 'Quel facteur maintient le blocage en métaphase II ?', answer: 'Le CSF (Cytostatic Factor).', },
{ question: 'Comment le CSF est-il dégradé ?', answer: 'Par une libération de Ca²⁺ lors de la fécondation.', },
{ question: 'Qu’est-ce que la maturation cytoplasmique ?', answer: 'Accumulation d’ARN, de protéines, réorganisation des organites.', },
{ question: 'Quelles protéines spécifiques sont synthétisées durant la maturation cytoplasmique ?', answer: 'ZP1, ZP2, ZP3 et protéines du cycle cellulaire.', },
{ question: 'Quel est le rôle des granules corticaux ?', answer: 'Prévenir la polyspermie.', },
{ question: 'Quelles modifications inclut la maturation membranaire ?', answer: 'Réorganisation des récepteurs (intégrines, CD9, Juno) et des lipides membranaires.', },
{ question: 'Quelles sont les caractéristiques de l’ovocyte II mature ?', answer: 'Cellule spécialisée, rare, capable de fusion et d’initier le développement embryonnaire.', },
{ question: 'Quelle est la quantité d’ADN d’un ovocyte II ?', answer: 'N chromosomes, 2 quantités d’ADN.', },
{ question: 'Où a lieu la folliculogenèse ?', answer: 'Dans le cortex ovarien.', },
{ question: 'Quand débute la folliculogenèse ?', answer: 'En fin de phase de multiplication fœtale.', },
{ question: 'Combien d’ovulations ont lieu entre puberté et ménopause ?', answer: 'Environ 300 à 400.', },
{ question: 'Quel est le nombre de follicules à la naissance ?', answer: 'Environ 1 million.', },
{ question: 'Combien reste-t-il de follicules à la puberté ?', answer: 'Environ 300 000.', },
{ question: 'Combien reste-t-il de follicules à la ménopause ?', answer: 'Moins de 1000.', },
{ question: 'Quelle est l’évolution d’un follicule primordial ?', answer: 'Follicule primaire, secondaire, tertiaire, pré-ovulatoire, corps jaune, corps blanc.', },
{ question: 'Quel est le diamètre d’un follicule secondaire ?', answer: '80 à 180 µm.', },
{ question: 'Quelle est la taille de l’ovocyte dans un follicule secondaire ?', answer: '40 à 60 µm.', },
{ question: 'Qu’est-ce qui devient bien visible dans le follicule secondaire ?', answer: 'L’épaisseur de la zone pellucide.', },
{ question: 'Combien de couches de cellules de granulosa a un follicule secondaire ?', answer: '3 à 4 couches de cellules péri-ovocytaires cubiques.', },
{ question: 'Quelle structure se forme dans le stroma autour d’un follicule secondaire ?', answer: 'La thèque interne.', },
{ question: 'Quelle caractéristique ont les cellules de la thèque interne ?', answer: 'Des caractéristiques cytologiques de cellules sécrétrices de stéroïdes.', },
{ question: 'Quel est le diamètre d’un follicule tertiaire ?', answer: 'De 180 µm à quelques mm.', },
{ question: 'Qu’est-ce que l’antrum ?', answer: 'Une cavité issue de la confluence de plusieurs petites cavités contenant du liquide folliculaire.', },
{ question: 'Comment est positionné l’ovocyte dans un follicule tertiaire ?', answer: 'Refoulé en périphérie, au pôle du follicule.', },
{ question: 'Comment s’appelle la couche de granulosa entourant l’ovocyte dans un follicule tertiaire ?', answer: 'La corona radiata.', },
{ question: 'Que sécrète la thèque interne dans un follicule tertiaire ?', answer: 'Des œstrogènes.', },
{ question: 'Quel est le rôle de la thèque externe ?', answer: 'Assurer un conjonctif de soutien.', },
{ question: 'Ces follicules tertiaires sont-ils visibles en échographie ?', answer: 'Oui.', },
{ question: 'Quel est le diamètre du follicule de De Graaf ?', answer: 'Environ 20 mm.', },
{ question: 'Où se situe le follicule de De Graaf ?', answer: 'Il fait saillie à la surface de l’ovaire.', },
{ question: 'Qu’est-ce qui augmente le volume de la cavité antrale dans le follicule pré-ovulatoire ?', answer: 'L’accumulation de liquide folliculaire.', },
{ question: 'Quel est le diamètre de l’ovocyte dans le follicule pré-ovulatoire ?', answer: '120 à 150 µm.', },
{ question: 'Quelle est la couche de granulosa immédiatement autour de l’ovocyte ?', answer: 'La corona radiata.', },
{ question: 'Qu’est-ce que le cumulus oophorus ?', answer: 'La structure reliant la corona radiata à la granulosa.', },
{ question: 'Quels types de thèques persistent dans le follicule de Graaf ?', answer: 'Thèque interne et thèque externe.', },
{ question: 'Comment définir l’ovulation ?', answer: 'La sortie de l’ovocyte secondaire hors du follicule.', },
{ question: 'Que contient l’ovocyte expulsé lors de l’ovulation ?', answer: 'L’ovocyte II entouré de la corona radiata et du cumulus oophorus.', },
{ question: 'Qui capte l’ovocyte après l’ovulation ?', answer: 'Le pavillon de la trompe utérine.', },
{ question: 'Quel événement hormonal précède l’ovulation ?', answer: 'Le pic de LH et FSH.', },
{ question: 'Quel est l’effet du pic de LH sur l’ovocyte ?', answer: 'Reprise de la méiose.', },
{ question: 'Quelles cellules sécrètent des mucopolysaccharides juste avant l’ovulation ?', answer: 'Les cellules du cumulus oophorus.', },
{ question: 'Quel changement vasculaire se produit avant l’ovulation ?', answer: 'Vascularisation renforcée autour du follicule.', },
{ question: 'Combien d’heures après la décharge ovulante la rupture folliculaire se produit-elle ?', answer: '36 heures.', },
{ question: 'Quelle molécule sécrétée par la granulosa joue un rôle dans la rupture folliculaire ?', answer: 'L’acide hyaluronique.', },
{ question: 'Qu’est-ce que le stigma ?', answer: 'Un point blanc comprimant les vaisseaux à la surface de l’ovaire avant la rupture.', },
{ question: 'En quoi se transforme le follicule après l’ovulation ?', answer: 'En corps jaune.', },
{ question: 'Quel rôle joue la LH dans la formation du corps jaune ?', answer: 'Elle induit une invasion vasculaire et la transformation des cellules folliculaires.', },
{ question: 'En quoi se transforment les cellules de la granulosa après l’ovulation ?', answer: 'En cellules lutéales sécrétrices de progestérone.', },
{ question: 'En quoi se transforment les cellules de la thèque interne après l’ovulation ?', answer: 'En cellules paralutéales sécrétrices d’œstrogènes.', },
{ question: 'Que devient le corps jaune si l’ovocyte n’est pas fécondé ?', answer: 'Il subit une atrophie et devient un corpus albicans.', },
{ question: 'Que devient le corps jaune en cas de grossesse ?', answer: 'Il se maintient comme corps jaune gestatif.', },
{ question: 'Quel est le destin le plus fréquent des follicules ?', answer: 'L’atrésie folliculaire.', },
{ question: 'À quel stade l’atrésie peut-elle survenir ?', answer: 'À tous les stades du développement folliculaire.', },
{ question: 'Quel élément dégénère en premier lors de l’atrésie ?', answer: 'L’ovocyte.', },
{ question: 'La folliculogenèse est-elle continue ou discontinue ?', answer: 'Continue.', },
{ question: 'Quand la croissance folliculaire commence-t-elle par rapport à l’ovulation ?', answer: 'Environ 5 mois avant.', },
{ question: 'Quelle portion de la folliculogenèse est cyclique ?', answer: 'Les 15 derniers jours.', },
{ question: 'Quels phénomènes sont indépendants des gonadotrophines ?', answer: 'Quiescence et croissance folliculaire de base.', },
{ question: 'Quels phénomènes sont dépendants des gonadotrophines ?', answer: 'Recrutement, sélection, dominance.', },
{ question: 'Qu’est-ce que la quiescence folliculaire ?', answer: 'Le pool des follicules primordiaux constituant la réserve ovarienne.', },
{ question: 'Combien de follicules restent à la ménopause ?', answer: 'Quelques dizaines à 1000.', },
{ question: 'Qu’est-ce que la croissance folliculaire de base ?', answer: 'Passage du follicule primordial à primaire, puis secondaire, puis préantral sans gonadotrophines.', },
{ question: 'Quelle est la durée de la croissance folliculaire de base ?', answer: 'Plusieurs mois.', },
{ question: 'Quels types de facteurs contrôlent la croissance de base ?', answer: 'Des phénomènes paracrines et autocrines.', },
{ question: 'Qu’est-ce que la croissance terminale ?', answer: 'La phase préovulatoire des 15 derniers jours dépendante des gonadotrophines.', },
{ question: 'Qu’est-ce que le recrutement folliculaire ?', answer: 'L’entrée en croissance d’une cohorte de follicules sensibles à la FSH en fin de phase lutéale.', },
{ question: 'Combien de follicules sont recrutés par cohorte ?', answer: '10 à 20.', },
{ question: 'Qu’est-ce que la sélection folliculaire ?', answer: 'Le choix du follicule ayant le seuil de réponse le plus bas à la FSH.', },
{ question: 'Pourquoi un seul follicule est-il sélectionné chez l’humain ?', answer: 'Parce que l’espèce humaine est mono-ovulante.', },
{ question: 'Qu’est-ce que la dominance folliculaire ?', answer: 'La maturation du follicule sélectionné et l’inhibition des autres.', },
{ question: 'Quel récepteur les cellules de la granulosa expriment-elles avant l’ovulation ?', answer: 'Le récepteur de la LH.', },
{ question: 'Quelles sont les deux phases du cycle ovarien ?', answer: 'Phase folliculaire (œstrogénique) et phase lutéale (progestative).', },
{ question: 'Quelle hormone hypothalamique contrôle la sécrétion de FSH et LH ?', answer: 'La GnRH.', },
{ question: 'Comment varie la FSH dans le cycle ?', answer: 'Augmente début phase folliculaire, diminue, remonte avant ovulation, puis baisse en phase lutéale.', },
{ question: 'Quel événement dépend du pic de LH ?', answer: 'L’ovulation.', },
{ question: 'Sur quelles cellules agit la FSH ?', answer: 'Les cellules de la granulosa.', },
{ question: 'Sur quelles cellules agit la LH en début de phase folliculaire ?', answer: 'Les cellules de la thèque interne.', },
{ question: 'Que produisent les cellules de la thèque interne en réponse à la LH ?', answer: 'Des androgènes.', },
{ question: 'Que produisent les cellules de la granulosa en réponse à la FSH ?', answer: 'Des œstrogènes et de l’inhibine.', },
{ question: 'Comment évoluent les œstrogènes durant la phase folliculaire ?', answer: 'Ils augmentent progressivement jusqu’à un maximum au 12e jour.', },
{ question: 'Quand apparaît la progestérone ?', answer: 'Après l’ovulation, sécrétée par le corps jaune.', },
{ question: 'Quel rétrocontrôle exercent œstrogènes et inhibine en première partie de cycle ?', answer: 'Un rétrocontrôle négatif sur la FSH.', },
{ question: 'Quel phénomène déclenche le rétrocontrôle positif ?', answer: 'Une imprégnation d’œstradiol élevée pendant 48 heures.', },
{ question: 'Quels pics hormonaux résultent du rétrocontrôle positif ?', answer: 'Les pics de LH et FSH.', },
{ question: 'Quel est l’effet de la progestérone en phase lutéale ?', answer: 'Inhiber l’axe hypothalamo-hypophysaire.', },
{ question: 'Quel est le rôle principal de la FSH dans la folliculogenèse ?', answer: 'Recrutement et croissance folliculaire.', },
{ question: 'Quel paramètre déclenche la dominance et l’atrésie des autres follicules ?', answer: 'Le seuil de rétrocontrôle négatif par E2 et inhibine.', },
{ question: 'Que provoque la LH ?', answer: 'L’ovulation et la synthèse de progestérone.', },
{ question: 'Jusqu’où évoluent les follicules durant l’enfance ?', answer: 'Jusqu’aux stades pré-antral ou antral précoce.', },
{ question: 'Pourquoi la ménopause survient-elle ?', answer: 'Parce que le nombre de follicules descend sous un seuil critique (~1000).', },
{ question: 'Quelle modification thermique suit l’ovulation ?', answer: 'Une augmentation de la température due à la progestérone.', },
{ question: 'Que reflète l’AMH ?', answer: 'La réserve ovarienne.', },
{ question: 'Quel est le dosage hormonal mesuré au 20e jour du cycle ?', answer: 'Le taux de progestérone.', },
{ question: 'Quel est le but de la stimulation ovarienne en AMP ?', answer: 'Obtenir plusieurs ovocytes matures.', },
{ question: 'Comment évite-t-on les pics prématurés de FSH et LH en FIV ?', answer: 'Par antagonistes de la GnRH ou GnRH en continu.', },
{ question: 'Comment crée-t-on artificiellement un pic de LH en FIV ?', answer: 'Avec un analogue de la LH.', },
{ question: 'Quel est le nombre normal d’ovocytes ovulés chez l’humain ?', answer: 'Un seul (mono-ovulant).', },
{ question: 'Qu’indique la présence de deux ovocytes ovulés ?', answer: 'La possibilité de faux jumeaux.', },
