{ question: 'Quelle est la définition de la fécondation ?', answer: 'Fusion de deux cellules matures haploïdes, le spermatozoïde et l’ovocyte, en une cellule unique diploïde et totipotente : le zygote.', },
{ question: 'Quelles conditions sont nécessaires à la fécondation ?', answer: 'Des conditions chronologiques et topographiques précises.', },
{ question: 'Comment nomme-t-on le dialogue moléculaire entre les deux gamètes ?', answer: 'L’interaction gamétique.', },
{ question: 'Quelle est la taille de l’ovocyte ?', answer: '120 µm.', },
{ question: 'Quelle est la taille de la tête du spermatozoïde ?', answer: '3 x 4,5 µm.', },
{ question: 'Quelle est la taille du flagelle du spermatozoïde ?', answer: '55 µm.', },
{ question: 'Comment est le cytoplasme de l’ovocyte ?', answer: 'Très développé.', },
{ question: 'Comment est le cytoplasme du spermatozoïde ?', answer: 'Réduit.', },
{ question: 'Comment est la chromatine de l’ovocyte ?', answer: 'Décondensée, avec histones.', },
{ question: 'Comment est la chromatine du spermatozoïde ?', answer: 'Très condensée, avec protamines et ponts SS.', },
{ question: 'Comment est la méiose ovocytaire ?', answer: 'Discontinue, avec un 1er arrêt en fin de prophase I (vésicule germinative) et un 2e arrêt en métaphase II.', },
{ question: 'Comment est la méiose spermatique ?', answer: 'Continue tout au long de la vie.', },
{ question: 'Quelle est la durée de survie de l’ovocyte après ovulation ?', answer: '10 à 24 heures.', },
{ question: 'Quelle est la durée de survie des spermatozoïdes dans les cryptes cervicales ?', answer: '3 à 4 jours.', },
{ question: 'Qu’est-ce que la période de fécondabilité ?', answer: 'La période du cycle où un rapport peut conduire à une grossesse.', },
{ question: 'Quelle est la période de fécondabilité pour un cycle de 28 jours ?', answer: 'De J11 à J15.', },
{ question: 'Comment le complexe cumulo-ovocytaire est-il capté ?', answer: 'Par les franges du pavillon de la trompe.', },
{ question: 'Quelles structures composent le CCO ?', answer: 'Ovocyte mature + cellules folliculaires formant corona radiata et cumulus oophorus.', },
{ question: 'Comment le CCO est-il transporté vers l’ampoule ?', answer: 'Par les cils tubaires et la motricité tubaire.', },
{ question: 'Quelle est la cause du faible péristaltisme tubaire en post-ovulatoire ?', answer: 'La progestérone.', },
{ question: 'Combien de temps le CCO séjourne-t-il dans l’ampoule ?', answer: 'Environ 72 heures.', },
{ question: 'Combien de temps l’ovocyte survit-il sans fécondation ?', answer: 'Environ 24 heures.', },
{ question: 'Quels sont les rôles du tractus génital féminin sur les spermatozoïdes ?', answer: 'Éliminer le liquide séminal, filtrer, sélectionner, contrôler le nombre, capaciter les gamètes.', },
{ question: 'Quel volume de sperme est déposé dans le vagin après éjaculation ?', answer: '2 à 6 ml.', },
{ question: 'Combien de spermatozoïdes sont contenus dans l’éjaculat ?', answer: '40 à 600 millions.', },
{ question: 'Quel est le rôle de la glaire cervicale en période préovulatoire ?', answer: 'Former un filet à mailles larges (~30 µm) guidant et sélectionnant les spermatozoïdes mobiles.', },
{ question: 'Quel est l’effet de la progestérone sur la glaire après ovulation ?', answer: 'Elle diminue, deviant imperméable aux spermatozoïdes (mailles 3-4 µm).', },
{ question: 'Quel pourcentage de spermatozoïdes pénètre dans le canal cervical ?', answer: '1 % (environ 3 millions).', },
{ question: 'Où se trouve le premier réservoir à spermatozoïdes ?', answer: 'Dans les cryptes des glandes endocervicales.', },
{ question: 'Quels mécanismes transportent les spermatozoïdes dans l’utérus ?', answer: 'Motilité propre, cellules ciliées, contractions utérines.', },
{ question: 'Quel rôle jouent les sphincters utéro-tubaires ?', answer: 'Contrôler la pénétration dans la trompe (2e barrière).', },
{ question: 'Quelles caractéristiques ralentissent les spermatozoïdes dans l’isthme tubaire ?', answer: 'Hyperviscosité, œdème, liaison aux cellules épithéliales.', },
{ question: 'Combien de spermatozoïdes arrivent au contact du CCO ?', answer: 'Une centaine.', },
{ question: 'Quels facteurs aident les spermatozoïdes à atteindre l’ampoule ?', answer: 'Contractions tubaires, cellules ciliées, molécules chémo-attractives du liquide folliculaire.', },
{ question: 'Où peuvent s’accumuler les spermatozoïdes au-delà de la trompe ?', answer: 'Dans le cul-de-sac de Douglas.', },
{ question: 'Comment est le spermatozoïde éjaculé in vivo ?', answer: 'Non fécondant avant capacitation.', },
{ question: 'Qu’est-ce qui doit être éliminé pour permettre la capacitation ?', answer: 'Le plasma séminal.', },
{ question: 'Où a lieu la capacitation in vivo ?', answer: 'Dans l’utérus puis les trompes.', },
{ question: 'Comment est la capacitation in vivo ?', answer: 'Progressive, continue, réversible, non spécifique d’espèce.', },
{ question: 'Comment est la capacitation in vitro ?', answer: 'Rapide, induite par élimination du plasma séminal, réversible.', },
{ question: 'Quelle hormone peut induire la capacitation in vitro ?', answer: 'La progestérone.', },
{ question: 'Quelles sont les modifications membranaires de la capacitation ?', answer: 'Enlèvement des protéines de revêtement, du cholestérol libre, des résidus glucidiques.', },
{ question: 'Quelles sont les conséquences principales de la capacitation ?', answer: 'Démasquage des récepteurs, perméabilité au calcium, hyperactivation.', },
{ question: 'Quelle modification de motilité caractérise la capacitation ?', answer: 'Amplitude latérale de la tête > 5 µm, nage circulaire.', },
{ question: 'Quelle enzyme augmente lors de la capacitation ?', answer: 'L’adénylate cyclase (augmentation AMPc).', },
{ question: 'Quel est le timing des étapes de l’interaction gamétique ?', answer: 'T0 mise en contact, T2h début de fusion, T30h première division.', },
{ question: 'Quelles sont les 7 étapes de l’interaction gamétique ?', answer: 'Traversée du cumulus, fixation primaire ZP, réaction acrosomique, liaison secondaire, traversée ZP, fusion, activation ovocytaire.', },
{ question: 'De quoi est composé le cumulus ?', answer: '3000 à 6000 cellules folliculeuses dans une matrice riche en acide hyaluronique.', },
{ question: 'Quels spermatozoïdes traversent le cumulus in vivo ?', answer: 'Les spermatozoïdes capacitants avec acrosome intact.', },
{ question: 'Quelles enzymes facilitent la traversée du cumulus in vitro ?', answer: 'Les hydrolases libérées lors de la réaction acrosomique.', },
{ question: 'Qu’est-ce que la zone pellucide ?', answer: 'Coque acellulaire de glycoprotéines entourant l’ovocyte.', },
{ question: 'Quelles glycoprotéines composent la ZP humaine ?', answer: 'ZP2, ZP3, ZP4 reliées par ZP1.', },
{ question: 'Avec quoi débute la fixation primaire ?', answer: 'Le contact entre ZP3-OS et l’apex du spermatozoïde.', },
{ question: 'Quel est l’inducteur physiologique de la réaction acrosomique ?', answer: 'ZP3.', },
{ question: 'De quoi dépend la réaction acrosomique ?', answer: 'Du calcium.', },
{ question: 'Quelles enzymes sont libérées lors de la RA ?', answer: 'Acrosine, hyaluronidase, β-N-acétylglucosaminidase.', },
{ question: 'Quelles structures participent à la liaison secondaire ?', answer: 'ZP2 et les protéines de la membrane acrosomique interne.', },
{ question: 'Quelle protéine majeure participe à la liaison secondaire ?', answer: 'SPAM1.', },
{ question: 'Comment le spermatozoïde traverse-t-il la ZP ?', answer: 'En biais, mécaniquement et par enzymes.', },
{ question: 'Quelle est la vitesse de progression dans la ZP ?', answer: '1 µm/min, soit 15 min.', },
{ question: 'Quelles enzymes rompent les ponts S-S de la ZP ?', answer: 'L’acrosine.', },
{ question: 'Où a lieu la fusion des membranes ?', answer: 'Au niveau du segment post-acrosomique du spermatozoïde.', },
{ question: 'Quels ligands spermatiques interviennent dans la fusion ?', answer: 'ADAMs (fertilines) et Izumo1.', },
{ question: 'Quels ligands ovocytaires interviennent dans la fusion ?', answer: 'CD9, CD81, intégrines α6β1, Juno.', },
{ question: 'Quelle invalidation provoque la stérilité mâle ?', answer: 'KO Izumo1.', },
{ question: 'Quelle invalidation provoque la stérilité femelle ?', answer: 'KO Juno.', },
{ question: 'Quel est le facteur universel d’activation ovocytaire ?', answer: 'La phospholipase C zeta (PLCζ).', },
{ question: 'Quel second messager est libéré après activation ?', answer: 'IP3.', },
{ question: 'Que provoque IP3 ?', answer: 'Une libération massive de Ca2+ à partir du RE.', },
{ question: 'Quelles sont les caractéristiques des oscillations calciques ?', answer: 'Toutes les 10 min pendant plusieurs heures.', },
{ question: 'Quel est le rôle des pulses de Ca2+ ?', answer: 'Ils sont indispensables à l’activation ovocytaire et à la future compétence embryonnaire.', },
{ question: 'Qu’est-ce que la réaction corticale ?', answer: 'Fusion des granules corticaux avec la membrane ovocytaire et libération d’enzymes.', },
{ question: 'Quelle modification de la ZP bloque la polyspermie ?', answer: 'Protéolyse de ZP2 et déglycosylation de ZP3.', },
{ question: 'De quelle taille est le pronucléus mâle ?', answer: '24 µm.', },
{ question: 'Quel phénomène transforme la tête du spermatozoïde en pronucléus ?', answer: 'Remplacement des protamines par des histones ovocytaires.', },
{ question: 'Quel est le rôle du glutathion ovocytaire ?', answer: 'Rupture des ponts disulfure des protamines.', },
{ question: 'Que devient l’enveloppe nucléaire paternelle ?', answer: 'Elle disparaît puis se reconstitue à partir du RE.', },
{ question: 'Combien mesure le pronucléus femelle ?', answer: '22 µm.', },
{ question: 'Quand est expulsé le second globule polaire ?', answer: '2h après le début de la fusion.', },
{ question: 'À quel moment apparaissent les deux pronucléi ?', answer: '6 à 7h après le début de la fécondation.', },
{ question: 'Quelles mitochondries persistent dans le zygote ?', answer: 'Les mitochondries maternelles.', },
{ question: 'Quel élément paternel essentiel est apporté au zygote ?', answer: 'Le centriole proximal.', },
{ question: 'Comment s’appelle le fuseau organisé par le centriole paternel ?', answer: 'Le spermaster.', },
{ question: 'Quel est le rôle du spermaster ?', answer: 'Attirer le pronucléus femelle et unir les deux pronucléi au centre.', },
{ question: 'Quand débute la phase S du premier cycle embryonnaire ?', answer: 'Environ 12h après la fécondation.', },
{ question: 'Combien dure la phase S ?', answer: '12 à 18 heures.', },
{ question: 'Quel est le statut chromosomique en fin de phase S ?', answer: '1n, 2C dans chaque pronucléus.', },
{ question: 'Que se passe-t-il en phase G2 ?', answer: 'Rapprochement et apposition des pronucléi, duplication centriolaire.', },
{ question: 'Que se passe-t-il en prophase du zygote ?', answer: 'Condensation séparée des chromosomes paternels et maternels.', },
{ question: 'Que signifie syngamie ?', answer: 'Alignement des chromosomes paternels et maternels sur la plaque équatoriale.', },
{ question: 'Quand survient la syngamie ?', answer: 'Environ 30h après la mise en contact CCO–spermatozoïde.', },
{ question: 'Que signe la syngamie ?', answer: 'L’achèvement de la fécondation.', },
