{ question: 'Où se déroule la fécondation ?', answer: 'Au niveau de l’ampoule tubaire.', },
{ question: 'À quel moment apparaît le zygote au stade 2PN ?', answer: 'À J1.', },
{ question: 'Quelle période couvre la première semaine du développement ?', answer: 'La période préimplantatoire jusqu’à la nidation.', },
{ question: 'Quels mécanismes assurent la migration du zygote vers l’utérus ?', answer: 'Les battements des cils tubaires et les contractions tubaires.', },
{ question: 'Qu’est-ce que la segmentation ?', answer: 'Une série de divisions mitotiques menant à l’éclosion.', },
{ question: 'Entre quels jours se déroule la segmentation ?', answer: 'De J1 à J4.', },
{ question: 'Quelles sont les caractéristiques de la segmentation ?', answer: 'Rotationnelle, symétrique puis asymétrique, à volume constant et sans croissance cellulaire.', },
{ question: 'Comment s’appellent les cellules issues de la segmentation ?', answer: 'Les blastomères.', },
{ question: 'Que devient le rapport nucléocytoplasmique au cours des divisions ?', answer: 'Il augmente.', },
{ question: 'À quel moment apparaît la morula ?', answer: 'À partir du 4e jour.', },
{ question: 'Qu’est-ce que la morula ?', answer: 'Un embryon de 16 à 32 blastomères en forme de petite mûre.', },
{ question: 'Quels sont les deux types de blastomères qui se différencient en fin de première semaine ?', answer: 'La masse cellulaire interne (MCI) et le trophoblaste.', },
{ question: 'Quel est le rôle de la MCI ?', answer: 'Former le bouton embryonnaire.', },
{ question: 'Quel est le rôle du trophoblaste ?', answer: 'Former la paroi du blastocyste.', },
{ question: 'Pourquoi l’embryon dépend-il des sécrétions tubaires avant l’implantation ?', answer: 'Parce que l’ovocyte est pauvre en réserves nutritives.', },
{ question: 'Quand a lieu la première division embryonnaire ?', answer: '30 à 36 heures après l’insémination.', },
{ question: 'Qu’est-ce que la segmentation holoblastique ?', answer: 'Une segmentation totale.', },
{ question: 'Selon quel plan se fait la première division ?', answer: 'Un plan méridional perpendiculaire à l’équateur.', },
{ question: 'Quel est le résultat de la première division ?', answer: 'Deux blastomères de taille similaire.', },
{ question: 'Quelles sont les caractéristiques de la deuxième division ?', answer: 'Légère asynchronie et orientation différente pour chaque blastomère.', },
{ question: 'Quelle disposition forme l’embryon au stade 4 cellules ?', answer: 'La disposition tétraédrique.', },
{ question: 'Pourquoi peut-on observer des embryons à nombre impair de cellules ?', answer: 'En raison de l’asynchronie des divisions.', },
{ question: 'Jusqu’à quel stade les blastomères sont-ils totipotents ?', answer: 'Jusqu’au stade 8-16 cellules.', },
{ question: 'Quels éléments sont observés à la surface des blastomères ?', answer: 'Des microvillosités et quelques desmosomes.', },
{ question: 'Qu’est-ce que l’activation du génome embryonnaire (AGE) ?', answer: 'Le passage du contrôle maternel au contrôle embryonnaire.', },
{ question: 'À quel stade a lieu l’activation du génome embryonnaire ?', answer: 'Au stade 4 à 8 cellules.', },
{ question: 'Quelles molécules maternelles assurent le développement initial avant AGE ?', answer: 'Protéines et ARNm maternels.', },
{ question: 'Qu’est-ce que la morula compactée ?', answer: 'Un amas cellulaire dont les blastomères périphériques s’aplatissent et adhèrent.', },
{ question: 'À partir de combien de cellules commence la compaction ?', answer: '16 cellules.', },
{ question: 'Quel est le rôle de l’E-cadhérine dans la compaction ?', answer: 'Inducteur de la polarisation et redistribution baso-latérale.', },
{ question: 'Quelle protéine maintient la cohésion après compaction ?', answer: 'La connexine 43.', },
{ question: 'Quelles jonctions apparaissent au cours de la compaction ?', answer: 'Jonctions adhérentes, desmosomes, jonctions communicantes, jonctions serrées.', },
{ question: 'Quelles sont les caractéristiques des blastomères périphériques après compaction ?', answer: 'Aplatis, polarisés, microvillosités apicales persistantes.', },
{ question: 'Quelles sont les caractéristiques des blastomères internes ?', answer: 'Arrondis, volumineux et en contact complet entre eux.', },
{ question: 'Quelle est la différence entre totipotence et pluripotence ?', answer: 'La totipotence permet de former un embryon complet, la pluripotence seulement les trois feuillets sans trophoblaste.', },
{ question: 'Quels facteurs exprime la MCI ?', answer: 'Oct4 et Nanog.', },
{ question: 'Quel est le devenir de la MCI ?', answer: 'Le fœtus et les annexes.', },
{ question: 'Quel est le devenir du trophoblaste ?', answer: 'La partie fœtale du placenta.', },
{ question: 'Qu’est-ce que la cavitation ?', answer: 'La création du blastocœle.', },
{ question: 'Quelle pompe ionique est indispensable à la formation du blastocyste ?', answer: 'La pompe Na+/K+ ATPase.', },
{ question: 'Quel est le rôle des aquaporines dans la cavitation ?', answer: 'Permettre le flux passif d’eau vers l’intérieur.', },
{ question: 'À quoi conduit l’accumulation liquidienne au centre de la morula ?', answer: 'À la formation du blastocœle.', },
{ question: 'Quelles sont les caractéristiques du blastocyste jeune ?', answer: 'Environ 32 cellules et 150 µm.', },
{ question: 'Quelles sont les caractéristiques du blastocyste expansé ?', answer: '60 à 120 cellules, environ 200 µm.', },
{ question: 'Comment se déroule l’éclosion ?', answer: 'Grâce à la strypsine trophoblastique qui digère la ZP.', },
{ question: 'À quel moment a lieu l’éclosion ?', answer: 'J6-J7.', },
{ question: 'Par où éclos le blastocyste ?', answer: 'Par son pôle anti-embryonnaire.', },
{ question: 'Quels sont les rôles principaux de la zone pellucide ?', answer: 'Protection, spécificité d’espèce, blocage polyspermie, nutrition, cohésion des blastomères, prévention de la grossesse extra-utérine.', },
{ question: 'Quelle est la fenêtre d’implantation ?', answer: 'Entre J20 et J23 du cycle menstruel.', },
{ question: 'Quelle est la condition hormonale de la réceptivité endométriale ?', answer: 'La phase sécrétoire sous influence progestative.', },
{ question: 'Qu’est-ce qu’un pinopode ?', answer: 'Une protrusion cytoplasmique apicale facilitant l’apposition embryonnaire.', },
{ question: 'Quelles sont les cinq phases de la nidation ?', answer: 'Orientation, apposition, adhésion, invasion, enfouissement total.', },
{ question: 'Quels signaux embryonnaires interviennent précocement lors de l’orientation ?', answer: 'PAF, histamine, hCG, LIF, VEGF.', },
{ question: 'À quoi correspond l’apposition ?', answer: 'Une phase instable et réversible de contact initial.', },
{ question: 'Quels mécanismes favorisent l’apposition ?', answer: 'Pinocytose et contact avec pinopodes.', },
{ question: 'Qu’est-ce que l’adhésion embryonnaire ?', answer: 'Fixation stable et irréversible à l’endomètre par le pôle embryonnaire.', },
{ question: 'Quelles molécules assurent l’adhésion trophoblastique ?', answer: 'Protéoglycanes HS, sélectines, intégrines, métalloprotéinases.', },
{ question: 'Quelles cytokines participent à l’adhésion ?', answer: 'IL1, LIF, CSF1, EGF.', },
{ question: 'À quel jour commence la différenciation du trophoblaste ?', answer: 'J8.', },
{ question: 'Quels sont les deux types cellulaires issus du trophoblaste ?', answer: 'Cytotrophoblaste (CT) et syncytiotrophoblaste (ST).', },
{ question: 'Quels sont les caractéristiques du cytotrophoblaste ?', answer: 'Cellules mononuclées, nombreuses mitoses.', },
{ question: 'Quelles sont les caractéristiques du syncytiotrophoblaste ?', answer: 'Cellules multinucléées sans limites, syncytium.', },
{ question: 'Quels sont les deux feuillets du disque embryonnaire ?', answer: 'Hypoblaste et épiblaste.', },
{ question: 'Quand débute l’invasion du trophoblaste ?', answer: 'J8-J9.', },
{ question: 'Quelle enzyme détruit la matrice endométriale ?', answer: 'Les métalloprotéinases.', },
{ question: 'Qu’est-ce qu’un invadopode ?', answer: 'Prolongement digitiforme du syncytiotrophoblaste pénétrant l’endomètre.', },
{ question: 'À quel moment se forment les deux cavités (amniotique et vitelline primitive) ?', answer: 'De J8 à J10.', },
{ question: 'Que devient l’épiblaste lors de la cavitation ?', answer: 'Il forme le toit de la cavité amniotique.', },
{ question: 'Que devient l’hypoblaste lors de la cavitation ?', answer: 'Il forme la membrane de Heuser et la vésicule vitelline primitive.', },
{ question: 'Quand l’embryon est-il totalement inclus dans l’endomètre ?', answer: 'J11-J12.', },
{ question: 'Qu’est-ce qui crée les lacs sanguins maternels ?', answer: 'La perforation des capillaires maternels par le ST.', },
{ question: 'Qu’est-ce que le réticulum extra-embryonnaire ?', answer: 'Un tissu conjonctif lâche acellulaire apparaissant à J10.', },
{ question: 'Quand apparaît le mésoblaste extra-embryonnaire ?', answer: 'À J11.', },
{ question: 'Qu’est-ce que la cavité choriale ?', answer: 'Le coelome extra-embryonnaire issu de lacunes mésoblastiques.', },
{ question: 'Qu’est-ce que le pédicule embryonnaire ?', answer: 'Le pont mésoblastique allongé à J13.', },
{ question: 'Quand se forme la vésicule vitelline secondaire ?', answer: 'À J13.', },
{ question: 'Que deviennent les restes de la vésicule vitelline primitive ?', answer: 'Des kystes exocoelomiques.', },
{ question: 'Quels sont les deux types de membranes mésoblastiques EE ?', answer: 'Somatopleure et splanchnopleure.', },
{ question: 'De quoi est composé le chorion de l’œuf ?', answer: 'Mésoblaste EE + cytotrophoblaste + syncytiotrophoblaste.', },
