{ question: 'Que signifie le mot protéine et quelle est son origine ?', answer: 'Le terme protéine vient du grec proteion signifiant “ce qui est au premier plan”.', },
{ question: 'Pourquoi les protéines sont-elles au centre du fonctionnement du vivant ?', answer: 'Parce qu’il n’existe presque aucun processus biologique qui ne soit régi par une ou plusieurs protéines.', },
{ question: 'D’où proviennent les protéines ?', answer: 'Elles proviennent de l’expression de nos gènes.', },
{ question: 'Quel est le rôle des protéines du cytosquelette ?', answer: 'Elles interviennent dans la forme cellulaire, la configuration, les changements de conformation, de taille et les différenciations.', },
{ question: 'Quel type de protéines maintient la matrice extracellulaire et la charpente des tissus ?', answer: 'Les protéines des tissus de soutien.', },
{ question: 'Quel est le rôle principal des immunoglobulines ?', answer: 'Reconnaître le soi et le non-soi.', },
{ question: 'Quels éléments structuraux caractérisent un anticorps ?', answer: 'Des régions stables donnant la structure et des régions très variables capables de reconnaître un antigène.', },
{ question: 'Quel est le rôle de l’hémoglobine ?', answer: 'Transporter l’oxygène des poumons vers les tissus périphériques.', },
{ question: 'Que permettent certaines protéines transmembranaires ?', answer: 'Le passage de signaux ou de molécules à courte distance à travers la membrane.', },
{ question: 'Pourquoi ces protéines transmembranaires doivent-elles avoir des zones hydrophobes ?', answer: 'Pour pouvoir interagir avec la bicouche lipidique hydrophobe.', },
{ question: 'Qu’est-ce qu’une enzyme ?', answer: 'Une protéine ayant une activité catalytique permettant d’accélérer les réactions chimiques vitales.', },
{ question: 'Pourquoi l’activité catalytique est-elle indispensable ?', answer: 'Sans catalyse, certaines réactions seraient extrêmement lentes et incompatibles avec le rythme du vivant.', },
{ question: 'Quels types de protéines permettent les mouvements cellulaires et intracellulaires ?', answer: 'Les protéines de la contraction et les protéines motrices.', },
{ question: 'Quel est le rôle des récepteurs protéiques ?', answer: 'Transformer un signal en un autre message, intervenant dans la communication cellulaire.', },

{ question: 'Qu’est-ce qu’une liaison covalente ?', answer: 'Une interaction forte impliquant un échange d’électrons entre deux atomes.', },
{ question: 'Quel rôle jouent les liaisons covalentes dans les protéines ?', answer: 'Elles forment l’ossature peptidique, reliant les acides aminés.', },
{ question: 'Qu’est-ce qu’une liaison non covalente ?', answer: 'Une liaison faible et réversible, essentielle à l’organisation tridimensionnelle de la protéine.', },
{ question: 'Qu’est-ce qu’une interaction de Van der Waals ?', answer: 'Interaction aspécifique dépendant uniquement de la distance interatomique.', },
{ question: 'Qu’est-ce qu’une liaison électrostatique ?', answer: 'Interaction entre molécules ou groupes ioniques chargés.', },
{ question: 'De quoi dépendent les liaisons ioniques ?', answer: 'Du pH du milieu.', },
{ question: 'Quels types d’atomes forment les liaisons hydrogène dans les protéines ?', answer: 'O donneur et N accepteur (2,88 Å) ou N donneur et O accepteur (3,04 Å).', },
{ question: 'Pourquoi les interactions hydrophobes sont-elles essentielles ?', answer: 'Car elles sont une des bases principales de la structuration tridimensionnelle des protéines.', },
{ question: 'Comment s’organise une protéine dans l’eau ?', answer: 'Résidus hydrophiles exposés, résidus hydrophobes enfouis.', },

{ question: 'Quelle est la formule du pH ?', answer: 'pH = -log[H+].', },
{ question: 'Que peut-on dire des acides en milieu biologique ?', answer: 'Ils sont faibles et partiellement ionisés.', },
{ question: 'Que représente le pKa ?', answer: 'Le pH à lequel un acide est à 50 % dissocié.', },
{ question: 'Énoncer l’équation de Henderson-Hasselbalch.', answer: 'pH = pKa + log([A-]/[HA]).', },
{ question: 'Que se passe-t-il si pH < pKa ?', answer: 'La forme protonée domine.', },
{ question: 'Que se passe-t-il si pH > pKa ?', answer: 'La forme déprotonée domine.', },

{ question: 'Quelle est la structure commune d’un acide aminé ?', answer: 'Un carbone asymétrique portant COOH, NH2, H et une chaîne latérale R.', },
{ question: 'Quel acide aminé n’est pas asymétrique ?', answer: 'La glycine.', },
{ question: 'Quelle série d’acides aminés est retrouvée chez les êtres vivants ?', answer: 'La série L.', },
{ question: 'Combien existe-t-il d’acides aminés naturels ?', answer: '20.', },
{ question: 'Quels sont les acides aminés essentiels ?', answer: 'Valine, leucine, isoleucine, phénylalanine, tryptophane, thréonine, histidine, lysine.', },

{ question: 'Quelles sont les caractéristiques de la glycine ?', answer: 'Elle n’a pas de carbone asymétrique et est donc achirale.', },
{ question: 'Quel est la particularité de la proline ?', answer: 'Sa chaîne latérale est cyclisée sur l’azote, rigidifiant l’acide aminé.', },
{ question: 'Quel acide aminé aromatique absorbe fortement dans l’UV grâce à son cycle phényl ?', answer: 'La phénylalanine.', },
{ question: 'Quel acide aminé contient un groupe indole absorbant l’UV ?', answer: 'Le tryptophane.', },
{ question: 'Quelle est la particularité de la tyrosine ?', answer: 'Elle possède un OH portant sa chaîne latérale de apolaire à polaire et absorbe aussi les UV.', },
{ question: 'Quels acides aminés sont phosphorylables ?', answer: 'Sérine, thréonine, tyrosine.', },
{ question: 'Quel acide aminé porte une fonction thiol permettant la formation d’un pont disulfure ?', answer: 'La cystéine.', },
{ question: 'Qu’est-ce qu’un pont disulfure ?', answer: 'Une liaison covalente réversible entre deux cystéines en milieu oxydant.', },

{ question: 'Quel acide aminé subit N-glycosylation ?', answer: 'L’asparagine.', },
{ question: 'Quels acides aminés acides apportent une charge négative à pH 7 ?', answer: 'Acide aspartique (pKa 3,9) et acide glutamique (pKa 4,1).', },
{ question: 'Quels acides aminés basiques apportent une charge positive à pH 7 ?', answer: 'Lysine, arginine, histidine.', },
{ question: 'Pourquoi l’histidine est-elle un acide aminé particulier ?', answer: 'Son pKa de 6 permet une protonation variable autour du pH physiologique.', },
