{ question: 'Quels sont les éléments qui constituent la ceinture pelvienne en avant ?', answer: 'L’union des os coxaux par une articulation fibrocartilagineuse : la symphyse pubienne.', },
{ question: 'Quels éléments composent la ceinture pelvienne en arrière ?', answer: 'Le sacrum entre les deux os coxaux via l’articulation sacro-iliaque.', },
{ question: 'Quelle articulation unit le bassin et la cuisse ?', answer: 'L’articulation de la hanche.', },
{ question: 'Quelles sont les caractéristiques générales du fémur ?', answer: 'C’est un os long avec une épiphyse proximale (tête et col), une diaphyse, et une épiphyse distale portant les condyles.', },
{ question: 'Quels éléments composent l’épiphyse proximale du fémur ?', answer: 'La tête fémorale, le col, le grand trochanter et le petit trochanter.', },
{ question: 'Quels éléments composent l’épiphyse distale du fémur ?', answer: 'Les condyles latéral et médial.', },
{ question: 'Quels os forment le genou ?', answer: 'La patella, le fémur et le tibia.', },
{ question: 'Quels os composent la jambe ?', answer: 'Le tibia en médial et la fibula en latéral.', },
{ question: 'Qu’est-ce que la malléole tibiale ?', answer: 'L’extrémité distale du tibia.', },
{ question: 'Qu’est-ce que la malléole fibulaire ?', answer: 'L’extrémité distale de la fibula.', },
{ question: 'Quel os forme le dôme de l’arrière-pied ?', answer: 'Le talus.', },

{ question: 'Quelles sont les trois régions de l’os coxal ?', answer: 'Le pubis, l’ischion et l’ilion.', },
{ question: 'Où se situe le pubis sur l’os coxal ?', answer: 'Dans la moitié inféro-antérieure, formant la symphyse pubienne.', },
{ question: 'Où se situe l’ischion sur l’os coxal ?', answer: 'Dans la moitié inféro-postérieure, représentant la zone de l’assise.', },
{ question: 'Où se situe l’ilion ?', answer: 'Dans la partie supérieure de l’os coxal : l’aile iliaque.', },
{ question: 'Que deviennent les lignes d’ossification de l’os coxal chez l’enfant ?', answer: 'Elles sont franches et permettent la croissance du bassin.', },
{ question: 'Que deviennent les lignes d’ossification de l’os coxal chez l’adulte ?', answer: 'Elles deviennent une séparation artificielle lorsque l’ossification est terminée.', },
{ question: 'Qu’est-ce que le foramen obturé ?', answer: 'Un large orifice entre pubis et ischion, totalement fermé par une membrane obturatrice.', },

{ question: 'Quelles sont les trois branches de l’os coxal ?', answer: 'La branche ischio-pubienne, la branche ilio-pubienne et la branche ilio-ischiatique.', },
{ question: 'Quel est le centre d’union des trois pièces et des trois branches de l’os coxal ?', answer: 'L’acétabulum.', },

{ question: 'Quel est le bord supérieur de l’os coxal ?', answer: 'La crête iliaque entre EIAS et EIPS.', },
{ question: 'Quel est le bord inférieur de l’os coxal ?', answer: 'La branche ischio-pubienne.', },
{ question: 'Quel est le bord antérieur de l’os coxal ?', answer: 'De l’EIAS au pubis.', },
{ question: 'Quel est le bord postérieur de l’os coxal ?', answer: 'De l’EIPS à la tubérosité ischiatique.', },
{ question: 'Quels sont les deux faces de l’os coxal ?', answer: 'Une face exopelvienne convexe et une face endopelvienne concave.', },

{ question: 'Quels sont les reliefs du bord postérieur de la face exopelvienne ?', answer: 'EIPS, EIPI, grande incisure ischiatique, épine ischiatique, petite incisure ischiatique, tubérosité ischiatique.', },
{ question: 'Quel relief osseux supporte le poids du corps en position assise ?', answer: 'La tubérosité ischiatique.', },

{ question: 'Quels sont les reliefs du bord antérieur de l’os coxal ?', answer: 'EIAS, EIAI, éminence iliopéctinée, branche supérieure du pubis, branche inférieure du pubis.', },
{ question: 'Quelle insertion se fait sur l’EIAS ?', answer: 'Le ligament inguinal.', },
{ question: 'Quelle insertion se fait sur l’EIAI ?', answer: 'Le tendon direct du droit fémoral.', },
{ question: 'Quelle est la particularité de la branche supérieure du pubis ?', answer: 'Elle se dirige vers la symphyse pubienne et appartient surtout à la face endopelvienne.', },
{ question: 'Comment se forme le bord inférieur de l’os coxal ?', answer: 'Par la réunion de la branche inférieure du pubis et de la branche de l’ischion.', },

{ question: 'Quels éléments forment la fosse glutéale ?', answer: 'Les lignes glutéales antérieure, postérieure et inférieure.', },
{ question: 'Quels muscles s’insèrent sur les champs déterminés par les lignes glutéales ?', answer: 'Petit fessier (champ antérieur), moyen fessier (champ moyen), grand fessier (champ postérieur).', },

{ question: 'Quelles sont les zones du pourtour de l’acétabulum ?', answer: 'En avant : branche ilio-pubienne ; en arrière : branche ilio-ischiatique et épine sciatique ; en supérieur : sillon supra-acétabulaire ; en inférieur : éminence ilio-pubienne.', },
{ question: 'Quelle est la structure cartilagée de l’acétabulum ?', answer: 'La surface semi-lunaire (croissant) avec corne ventrale fine et corne dorsale épaisse reliées par le ligament transverse.', },

{ question: 'Qu’est-ce que la ligne arquée ?', answer: 'Une limite séparant ilion et ischion-pubis et le passage important de l’accouchement.', },
{ question: 'Qu’est-ce que la surface quadrilatère ?', answer: 'La face endopelvienne de la coxo-fémorale, zone de passage de l’obturateur médial.', },
{ question: 'Qu’est-ce que la surface auriculaire ?', answer: 'La surface articulaire avec le sacrum, sur l’ilion.', },
{ question: 'Quel est le moyen d’union diaphysaire entre le tibia et la fibula ?', answer: 'La membrane interosseuse.', },
{ question: 'Quels sont les moyens d’union épiphysaires supérieurs entre tibia et fibula ?', answer: 'L’articulation tibio-fibulaire proximale, qui arrime les deux os avec un petit jeu d’éloignement.', },
{ question: 'Quels sont les moyens d’union épiphysaires inférieurs entre tibia et fibula ?', answer: 'Les ligaments tibio-fibulaires antérieur et postérieur.', },
{ question: 'Que permettent les moyens d’union épiphysaires inférieurs ?', answer: 'Un écartement des deux os lors de la flexion-extension de cheville.', },

{ question: 'Quels os constituent le tarse postérieur ?', answer: 'Le talus en haut et le calcanéus en bas.', },
{ question: 'Quel os du pied est en contact avec les extrémités inférieures du tibia et de la fibula ?', answer: 'Le talus.', },
{ question: 'Quel os du pied repose sur le sol ?', answer: 'Le calcanéus.', },
{ question: 'Comment s’appelle la ligne articulaire séparant tarse postérieur et tarse antérieur ?', answer: 'L’articulation transverse du tarse.', },
{ question: 'Quels os composent le tarse antérieur ?', answer: 'Le naviculaire, le cuboïde et les trois cunéiformes.', },
{ question: 'Que sépare la ligne articulaire tarsométatarsienne ?', answer: 'Le tarse antérieur et les métatarsiens.', },
{ question: 'Combien le pied possède-t-il de métatarsiens ?', answer: 'Cinq.', },
{ question: 'Combien de phalanges possèdent les doigts II à V ?', answer: 'Trois chacun.', },
{ question: 'Combien de phalanges possède l’hallux ?', answer: 'Deux.', },

{ question: 'Avec quels os le talus s’articule-t-il ?', answer: 'Avec tibia et fibula en haut, avec le calcanéus en bas, et avec le naviculaire en avant.', },
{ question: 'Comment se nomme la surface articulaire supérieure du talus ?', answer: 'La trochlée.', },
{ question: 'Quel est le rôle de la trochlée ?', answer: 'Surface articulaire pour les malléoles tibiales et fibulaires.', },
{ question: 'Quelle est la particularité de la trochlée du talus ?', answer: 'Elle est plus large en avant qu’en arrière.', },
{ question: 'Où se situe le col du talus ?', answer: 'Entre la trochlée et la tête.', },
{ question: 'Avec quel os s’articule la tête du talus ?', answer: 'Avec le naviculaire.', },
{ question: 'Quel angle sépare tête et trochlée en vue supérieure ?', answer: '150°.', },
{ question: 'Quel angle sépare tête et trochlée en vue latérale ?', answer: '110°.', },
{ question: 'Quelle surface articulaire du talus est plus volumineuse : malléolaire latérale ou médiale ?', answer: 'La malléolaire latérale.', },
{ question: 'Quels types de surfaces articulaires se trouvent sous le talus ?', answer: 'Les surfaces calcanéennes postérieure et moyenne.', },

{ question: 'Quel est l’os le plus volumineux du tarse ?', answer: 'Le calcanéus.', },
{ question: 'Avec quels os le calcanéus s’articule-t-il ?', answer: 'Avec le talus en haut et le cuboïde en avant.', },
{ question: 'Combien le calcanéus possède-t-il de surfaces articulaires taliennes ?', answer: 'Trois : antérieure, moyenne et postérieure.', },
{ question: 'Quelle est la plus grosse des surfaces articulaires taliennes ?', answer: 'La surface postérieure.', },
{ question: 'Qu’est-ce que le sillon calcanéen ?', answer: 'Un sillon séparant les surfaces articulaires moyenne et antérieure, devenant avec le talus le sinus du tarse.', },
{ question: 'Qu’est-ce que la tubérosité calcanéenne ?', answer: 'Le relief postérieur du calcanéus formant le talon.', },
{ question: 'Quel type d’articulation unit talus et calcanéus ?', answer: 'L’articulation talo-calcanéenne (subtalaire).', },

{ question: 'Quel os est situé en avant du talus ?', answer: 'Le naviculaire.', },
{ question: 'Avec quels os le naviculaire s’articule-t-il ?', answer: 'Avec la tête du talus et les trois cunéiformes.', },
{ question: 'Quel cunéiforme est le plus médial ?', answer: 'Le premier cunéiforme (C1).', },
{ question: 'Quel cunéiforme est le plus petit ?', answer: 'Le deuxième cunéiforme (C2).', },
{ question: 'Quel cunéiforme s’articule avec le cuboïde ?', answer: 'Le troisième cunéiforme (C3).', },
{ question: 'Quel os constitue le tiers latéral du tarse antérieur ?', answer: 'Le cuboïde.', },

{ question: 'Quel métatarsien s’articule uniquement avec le cunéiforme médial ?', answer: 'Le premier métatarsien.', },
{ question: 'Quel métatarsien possède le plus d’articulations ?', answer: 'Le deuxième métatarsien (avec les trois cunéiformes).', },
{ question: 'Quels métatarsiens s’articulent uniquement avec un seul os ?', answer: 'Le premier avec C1 et le cinquième avec le cuboïde.', },

{ question: 'Quelles sont les zones d’appui classiques du pied ?', answer: 'Les tubérosités calcanéennes à l’arrière et les têtes des métatarsiens à l’avant.', },
{ question: 'Quel métatarsien repose le plus entièrement sur le sol ?', answer: 'Le cinquième métatarsien (le plus horizontal).', },
{ question: 'Quel métatarsien constitue l’axe du pied ?', answer: 'Le deuxième métatarsien.', },
{ question: 'Combien de phalanges possède l’hallux ?', answer: 'Deux.', },
{ question: 'Combien d’os sésamoïdes se trouvent sous la tête du premier métatarsien ?', answer: 'Deux.', },

{ question: 'Quel est le type articulaire de l’articulation coxo-fémorale ?', answer: 'Une synoviale sphéroïde.', },
{ question: 'Combien de degrés de liberté possède l’articulation coxo-fémorale ?', answer: 'Trois.', },
{ question: 'Qu’est-ce que la fossette de la tête du fémur ?', answer: 'Une zone non cartilagineuse où s’insère le ligament de la tête.', },
{ question: 'Quelle est la fonction du labrum acétabulaire ?', answer: 'Augmenter les contacts entre fémur et os coxal.', },
{ question: 'Quel ligament ferme les cornes de l’acétabulum ?', answer: 'Le ligament transverse.', },
{ question: 'Pourquoi la luxation de hanche est-elle difficile ?', answer: 'À cause de la forte coaptation et des moyens d’union.', },

{ question: 'Combien existe-t-il de ligaments extracapsulaires de la hanche ?', answer: 'Trois.', },
{ question: 'Quel est le ligament antérieur médial de la hanche ?', answer: 'Le ligament pubo-fémoral.', },
{ question: 'Quel est le ligament antérosupérieur le plus puissant ?', answer: 'Le ligament ilio-fémoral.', },
{ question: 'Quel est le ligament postéroinférieur ?', answer: 'Le ligament ischio-fémoral.', },

{ question: 'Quels sont les mouvements permis par la hanche ?', answer: 'Flexion, extension, abduction, adduction, rotations médiale et latérale.', },

{ question: 'Quel muscle assure la quasi-totalité de la flexion de hanche ?', answer: 'Le muscle ilio-psoas.', },
{ question: 'Quels muscles composent l’ilio-psoas ?', answer: 'Le psoas major et l’iliaque.', },
{ question: 'De quelles vertèbres proviennent les insertions proximales du psoas ?', answer: 'Des corps vertébraux et processus transverses de T12 à L5.', },
{ question: 'Quel est le tendon commun de l’ilio-psoas ?', answer: 'Le tendon terminal au petit trochanter.', },
{ question: 'Quelle est l’action principale de l’ilio-psoas ?', answer: 'Flexion de la hanche.', },
{ question: 'Quelle est son innervation ?', answer: 'Le nerf fémoral.', },

{ question: 'Quels sont les trois muscles glutéaux ?', answer: 'Grand glutéal, moyen glutéal, petit glutéal.', },
{ question: 'Quel muscle forme le relief fessier ?', answer: 'Le grand glutéal.', },
{ question: 'Où s’insère principalement le grand glutéal ?', answer: 'Sur la crête iliaque, la face exopelvienne postérieure, le sacrum et le coccyx.', },
{ question: 'Quelle est l’action principale du grand glutéal ?', answer: 'L’extension de la cuisse.', },
{ question: 'Quel est son rôle dans la station debout ?', answer: 'Maintien de la hanche en extension en appui unipodal.', },
{ question: 'Quel est le nerf du grand glutéal ?', answer: 'Le nerf glutéal inférieur.', },

{ question: 'Quelle est l’insertion proximale du tenseur du fascia lata ?', answer: 'L’EIAS.', },
{ question: 'Où se termine le TFL ?', answer: 'Sur le tractus ilio-tibial puis sur le tubercule infracondylaire du tibia.', },
{ question: 'Quelles actions le TFL exerce-t-il ?', answer: 'Abduction, rotation médiale de hanche et légère extension du genou.', },
{ question: 'Quel est son nerf ?', answer: 'Le nerf glutéal supérieur.', },

{ question: 'Où s’insère le moyen fessier ?', answer: 'Entre les lignes glutéales antérieure et postérieure.', },
{ question: 'Où se termine le moyen fessier ?', answer: 'Sur la partie supérieure du grand trochanter.', },
{ question: 'Quel est son rôle principal lors de la marche ?', answer: 'Maintien du bassin horizontal en appui unipodal.', },
{ question: 'Quelle est sa fonction articulaire ?', answer: 'Abduction de la hanche.', },
{ question: 'Quel est son nerf ?', answer: 'Le nerf glutéal supérieur.', },
{ question: 'Quels muscles appartiennent au groupe des pelvitrochantériens ?', answer: 'Piriforme, obturateur interne, jumeau supérieur, jumeau inférieur, obturateur externe, carré fémoral.', },
{ question: 'Où se situent les muscles pelvitrochantériens ?', answer: 'Dans la région postérieure du bassin, sous le petit glutéal.', },
{ question: 'Quel est le rôle général des pelvitrochantériens ?', answer: 'Ils s’insèrent du sacrum et de l’os coxal vers le grand trochanter.', },

{ question: 'Quelle est l’insertion proximale du muscle piriforme ?', answer: 'La face latérale du sacrum.', },
{ question: 'Quelle est l’insertion distale du muscle piriforme ?', answer: 'Le bord médial du grand trochanter.', },
{ question: 'Quels espaces sont délimités par le piriforme ?', answer: 'Le foramen supra-piriforme et le foramen infra-piriforme.', },
{ question: 'Quel est le trajet du piriforme ?', answer: 'Fibres obliques en bas et en dedans, traversant la grande incisure ischiatique.', },
{ question: 'Que contient la région des foramens supra- et infra-piriforme ?', answer: 'Le passage des nerfs et vaisseaux destinés à la région fessière.', },

{ question: 'Quelle est l’insertion proximale de l’obturateur interne ?', answer: 'La membrane obturatrice interne et les portions osseuses du pourtour.', },
{ question: 'Quel est le trajet de l’obturateur interne ?', answer: 'Tendon quasi horizontal.', },
{ question: 'Quelle est l’insertion distale de l’obturateur interne ?', answer: 'Grand trochanter.', },

{ question: 'D’où provient le jumeau supérieur ?', answer: 'De l’épine ischiatique.', },
{ question: 'D’où provient le jumeau inférieur ?', answer: 'De la tubérosité ischiatique.', },
{ question: 'Où se terminent les jumeaux ?', answer: 'Avec l’obturateur interne, sur le grand trochanter.', },

{ question: 'D’où provient l’obturateur externe ?', answer: 'De la face externe de la membrane obturatrice et du pourtour du foramen obturateur.', },
{ question: 'Quel est le trajet de l’obturateur externe ?', answer: 'Il contourne le col du fémur sous et en arrière.', },
{ question: 'Où se termine l’obturateur externe ?', answer: 'Dans la fosse trochantérique (face médiale du grand trochanter).', },

{ question: 'D’où provient le carré fémoral ?', answer: 'De la face latérale de la tubérosité ischiatique.', },
{ question: 'Où se termine le carré fémoral ?', answer: 'Sur la crête intertrochantérique du fémur.', },

{ question: 'Quelle action commune partagent tous les pelvitrochantériens ?', answer: 'La rotation latérale de la hanche.', },
{ question: 'Quelles sont les actions du piriforme ?', answer: 'Abduction de la hanche, rotation latérale et extension.', },
{ question: 'Quelles sont les actions des obturateurs et des jumeaux ?', answer: 'Principaux moteurs de la rotation latérale de hanche.', },
{ question: 'Quelles sont les actions de l’obturateur externe ?', answer: 'Rotation latérale et adduction.', },
{ question: 'Quelle est la fonction principale du carré fémoral ?', answer: 'Adduction de la hanche (et rotation latérale modeste).', },

{ question: 'Où s’insèrent proximalement les muscles adducteurs ?', answer: 'Sur la partie inférieure de l’os coxal, principalement le pubis.', },
{ question: 'Où se terminent les muscles adducteurs ?', answer: 'Sur la ligne âpre du fémur.', },
{ question: 'Quels muscles appartiennent aux couches superficielles et moyennes des adducteurs ?', answer: 'Pectiné, long adducteur, court adducteur.', },
{ question: 'Quels muscles appartiennent aux couches profondes des adducteurs ?', answer: 'Gracile et grand adducteur.', },

{ question: 'Quelle est l’origine du court adducteur ?', answer: 'La branche inférieure du pubis.', },
{ question: 'Où se termine le court adducteur ?', answer: 'Sur le tiers supérieur de la diaphyse fémorale, lèvre médiale de la ligne âpre.', },
{ question: 'Quel nerf innerve le court adducteur ?', answer: 'Le nerf obturateur.', },

{ question: 'Quelle est l’origine du pectiné ?', answer: 'Le pecten du pubis.', },
{ question: 'Où se termine le pectiné ?', answer: 'Sur la ligne pectinée du fémur.', },
{ question: 'Quelle est son innervation ?', answer: 'Le nerf fémoral.', },

{ question: 'Quelle est l’origine du long adducteur ?', answer: 'La face latérale du pubis proche de la symphyse.', },
{ question: 'Où se termine le long adducteur ?', answer: 'Sur la lèvre médiale de la ligne âpre, tiers moyen du fémur.', },
{ question: 'Quel est le nerf du long adducteur ?', answer: 'Le nerf obturateur.', },

{ question: 'Quelle est l’origine du gracile ?', answer: 'Le pubis.', },
{ question: 'Pourquoi le gracile ne s’insère-t-il pas sur le fémur ?', answer: 'Car il descend jusqu’à la patte d’oie sur le tibia.', },
{ question: 'Quelles sont les fonctions du gracile ?', answer: 'Adduction de hanche et stabilisation du genou via la patte d’oie.', },
{ question: 'Quel nerf innerve le gracile ?', answer: 'Le nerf obturateur.', },

{ question: 'Quelle est l’origine du grand adducteur ?', answer: 'Branche inférieure du pubis et branche de l’ischion.', },
{ question: 'Où se termine le chef oblique du grand adducteur ?', answer: 'Sur la lèvre médiale de la ligne âpre, sur toute la hauteur du fémur.', },
{ question: 'Où se termine le chef vertical du grand adducteur ?', answer: 'Sur le tubercule de l’adducteur (épicondyle médial du fémur).', },
{ question: 'Quel nerf innerve le grand adducteur ?', answer: 'Le nerf obturateur (et partiellement le nerf sciatique pour le faisceau ischio-condylaire).', },
{ question: 'Qu’est-ce que le hiatus du grand adducteur ?', answer: 'Un espace entre les faisceaux oblique et vertical où passe l’artère fémorale.', },

{ question: 'Quels os participent à l’articulation du genou ?', answer: 'Le fémur, le tibia et la patella.', },
{ question: 'La fibula participe-t-elle à l’articulation du genou ?', answer: 'Non.', },
{ question: 'Quels sont les deux compartiments de l’articulation fémorotibiale ?', answer: 'Latéral et médial.', },
{ question: 'Quels éléments articulaires composent l’articulation fémoropatellaire ?', answer: 'La trochlée fémorale et la face articulaire postérieure de la patella.', },

{ question: 'Quelle est la particularité géométrique du genou ?', answer: 'Condyles fémoraux convexes et plateaux tibiaux concaves.', },
{ question: 'Pourquoi la hanche est-elle plus stable que le genou ?', answer: 'Car elle possède une forte imbrication osseuse, contrairement au genou.', },
{ question: 'De quoi dépend surtout la stabilité du genou ?', answer: 'Des ligaments intra- et péri-articulaires.', },

{ question: 'Quel type d’articulation est l’articulation fémoro-patellaire ?', answer: 'Un ginglyme.', },
{ question: 'Quel mouvement principal accomplit la patella ?', answer: 'Une translation proximodistale.', },
{ question: 'La stabilité de la patella dépend-elle principalement des surfaces osseuses ?', answer: 'Non, elle dépend surtout des structures périarticulaires.', },

{ question: 'Quelles sont les principales structures péri-articulaires autour du genou ?', answer: 'Cartilage, ligaments, capsule, membrane synoviale, tendons, muscles, ménisques, os sous-chondral, bourses.', },
{ question: 'Quels sont les rôles principaux des structures péri-articulaires ?', answer: 'Stabilisation, mobilité, transmission des forces, amortissement et lubrification.', },

{ question: 'Quelle est la nature des ménisques ?', answer: 'Fibrocartilages recouverts de cartilage articulaire.', },
{ question: 'Combien existe-t-il de ménisques ?', answer: 'Deux : médial et latéral.', },
{ question: 'Quelle est la forme du ménisque latéral ?', answer: 'Quasi circulaire (≈ O).', },
{ question: 'Quelle est la forme du ménisque médial ?', answer: 'Plus ouvert (≈ C).', },
{ question: 'Où les ménisques se fixent-ils ?', answer: 'Sur le tibia à leurs cornes antérieure et postérieure.', },
{ question: 'Où les ménisques n’ont-ils pas d’insertion osseuse ?', answer: 'Au milieu de leur longueur.', },
{ question: 'Avec quoi le bord périphérique des ménisques est-il attaché ?', answer: 'Avec la capsule articulaire.', },

{ question: 'Comment apparaissent les ménisques en coupe sagittale ?', answer: 'Comme deux triangles fibrocartilagineux.', },
{ question: 'Pourquoi un même ménisque peut-il apparaître deux fois en coupe ?', answer: 'Parce que la coupe peut traverser la portion antérieure et postérieure.', },
{ question: 'Quel rôle ont les ménisques dans la congruence articulaire ?', answer: 'Améliorer la conformité entre condyles fémoraux et plateau tibial.', },
{ question: 'Comment les ménisques modifient-ils la surface d’appui ?', answer: 'Ils multiplient la surface articulaire.', },
{ question: 'Quel rôle ont les ménisques dans les mouvements du genou ?', answer: 'Ils facilitent et stabilisent la flexion-extension.', },
