{ question: 'Quelles sont les deux grandes composantes de l’appareil digestif ?', answer: 'Le tractus digestif et les glandes annexes.', },
{ question: 'Quels organes appartiennent au tractus digestif ?', answer: 'Cavité orale, pharynx, œsophage, estomac, intestin grêle, côlon, rectum.', },
{ question: 'Quelles glandes appartiennent aux glandes annexes du tube digestif ?', answer: 'Les glandes salivaires, le foie et le pancréas.', },
{ question: 'Quelles sont les fonctions du tractus digestif ?', answer: 'Ingestion, digestion mécanique et chimique, absorption des nutriments, élimination des matières fécales.', },
{ question: 'Quelles sont les fonctions des glandes annexes ?', answer: 'Digestion chimique par sécrétions exocrines, métabolisme et sécrétions endocrines.', },
{ question: 'Quelles sont les deux fonctions principales de la cavité orale ?', answer: 'Préhension et mastication des aliments (mécanique), digestion par sucs salivaires (chimique).', },
{ question: 'Quelles sont les deux fonctions principales du pharynx ?', answer: 'Passage de l’air et progression du bol alimentaire.', },
{ question: 'Quelles fonctions annexes sont assurées par le pharynx ?', answer: 'Déglutition, respiration, phonation et audition.', },
{ question: 'Quelles sont les deux parties de la cavité orale ?', answer: 'Le vestibule et la cavité buccale.', },
{ question: 'Où se situe le vestibule de la cavité orale ?', answer: 'Entre lèvres/joues en dehors et gencives/dents en dedans.', },
{ question: 'Quel conduit s’ouvre en face de la 2e molaire supérieure ?', answer: 'Le canal de Sténon de la glande parotide.', },
{ question: 'Que contient la cavité buccale ?', answer: 'La langue.', },
{ question: 'Quelles sont les limites hautes de la cavité orale ?', answer: 'Palais dur en avant, palais mou en arrière.', },
{ question: 'Quelles structures forment le plancher buccal ?', answer: 'Le frein de la langue, le canal de Wharton et le pli sublingual avec les canaux de Rivinus et Walther.', },
{ question: 'Quelles sont les limites arrière de la cavité orale ?', answer: 'L’isthme du gosier.', },
{ question: 'Quels éléments forment l’isthme du gosier ?', answer: 'Arcs palato-glosse et palato-pharyngien, luette, fosse tonsillaire.', },
{ question: 'Quelle est la structure lymphoïde présente entre les piliers du gosier ?', answer: 'L’amygdale palatine.', },
{ question: 'Quelle est la forme générale du pharynx ?', answer: 'Un demi-entonnoir musculomembraneux.', },
{ question: 'Quels sont les trois étages du pharynx ?', answer: 'Nasopharynx, oropharynx, laryngopharynx.', },
{ question: 'Le nasopharynx appartient-il au tube digestif ?', answer: 'Non.', },
{ question: 'Quelle est la fonction de la trompe d’Eustache ?', answer: 'Communiquer le nasopharynx avec l’oreille moyenne.', },
{ question: 'Quel étage du pharynx appartient au carrefour aéro-digestif ?', answer: 'L’oropharynx.', },
{ question: 'Quel étage contient les cordes vocales ?', answer: 'Le laryngopharynx.', },
{ question: 'Quelle est la longueur de l’œsophage ?', answer: '25 cm.', },
{ question: 'Quel est le diamètre de l’œsophage ?', answer: '15 mm.', },
{ question: 'Quels sont les trois segments de l’œsophage ?', answer: 'Cervical, thoracique, abdominal.', },
{ question: 'Où se situe le premier rétrécissement de l’œsophage ?', answer: 'À la bouche œsophagienne de Killian en C6.', },
{ question: 'Où se situe le deuxième rétrécissement de l’œsophage ?', answer: 'Au niveau de la crosse de l’aorte (T4) et la bronche souche gauche (T5).', },
{ question: 'Où se situe le troisième rétrécissement de l’œsophage ?', answer: 'À l’orifice œsophagien du diaphragme (T10).', },
{ question: 'Entre quelles vertèbres s’étend l’œsophage abdominal ?', answer: 'De T10 à T11.', },
{ question: 'Qu’est-ce que le cardia ?', answer: 'Le sphincter inférieur de l’œsophage.', },
{ question: 'Quel est le risque si le cardia reste ouvert après le passage des aliments ?', answer: 'Œsophagite par reflux acide.', },
{ question: 'Quels sont les trois étages superficiels de l’abdomen ?', answer: 'Épigastre, ombilic, hypogastre.', },
{ question: 'Quels sont les étages latéraux superficiels de l’abdomen ?', answer: 'Hypochondres, flancs, fosses iliaques.', },
{ question: 'Quelles sont les limites de la cavité abdominale ?', answer: 'Diaphragme thoracique en haut, diaphragme pelvien en bas.', },
{ question: 'Quels espaces contient la cavité abdominale ?', answer: 'Cavité péritonéale, espaces rétro- et sous-péritonéaux, mésos.', },
{ question: 'Qu’est-ce que le péritoine ?', answer: 'Une membrane séreuse à deux feuillets, viscéral et pariétal.', },
{ question: 'Qu’est-ce qu’un méso ?', answer: 'Un repli péritonéal reliant un segment digestif à l’espace rétro-péritonéal.', },
{ question: 'Quelle est la capacité moyenne de l’estomac ?', answer: 'Environ 1,5 L.', },
{ question: 'Quelle est la forme de l’estomac ?', answer: 'Une forme de J avec une petite et une grande courbure.', },
{ question: 'Quelles sont les quatre parties de l’estomac ?', answer: 'Cardia, fundus, corps, pylore.', },
{ question: 'Quel est le rôle du fundus ?', answer: 'Réservoir supérieur séparé du cardia par l’incisure cardiale.', },
{ question: 'Quelle est la fonction du pylore ?', answer: 'Réguler la vidange gastrique vers le duodénum.', },
{ question: 'Quel est le pH du suc gastrique ?', answer: 'Inférieur à 2.', },
{ question: 'Quelle vitamine nécessite le facteur intrinsèque pour être absorbée ?', answer: 'La vitamine B12.', },
{ question: 'Quel est le nom de l’anémie causée par un manque de facteur intrinsèque ?', answer: 'L’anémie de Biermer.', },
{ question: 'Quelle est la longueur totale de l’intestin grêle ?', answer: 'Environ 5 mètres.', },
{ question: 'Quelles sont les trois parties de l’intestin grêle ?', answer: 'Duodénum, jéjunum, iléon.', },
{ question: 'Quelle est la fonction générale de l’intestin grêle ?', answer: 'Digestion et absorption des nutriments.', },
{ question: 'Quelle est la longueur du duodénum ?', answer: '25 cm.', },
{ question: 'Quelle est la forme du duodénum ?', answer: 'Un C entourant le pancréas.', },
{ question: 'Quelles sont les portions du duodénum ?', answer: 'D1, D2, D3, D4.', },
{ question: 'Où se jettent les canaux pancréatiques et biliaires ?', answer: 'Dans D2 via les papilles duodénales.', },
{ question: 'Quel angle marque la transition duodénum–jéjunum ?', answer: 'L’angle de Treitz.', },
{ question: 'Quelle bactérie est responsable des ulcères gastroduodénaux ?', answer: 'Helicobacter pylori.', },
{ question: 'Quel segment de l’intestin grêle représente 2/5 de sa longueur ?', answer: 'Le jéjunum.', },
{ question: 'Quel segment représente 3/5 de l’intestin grêle ?', answer: 'L’iléon.', },
{ question: 'Avec quel segment du gros intestin s’abouche l’iléon ?', answer: 'Le caecum.', },
{ question: 'Qu’est-ce qu’une anse intestinale ?', answer: 'Un segment mobile dépendant d’une branche artérielle mésentérique.', },
{ question: 'Qu’est-ce que le mésentère du jéjuno-iléon ?', answer: 'Un repli péritonéal reliant le jéjuno-iléon à l’espace rétro-péritonéal et contenant ses vaisseaux.', },
{ question: 'Quels sont les deux éléments constituant la partie terminale du tube digestif ?', answer: 'Le côlon et le rectum.', },
{ question: 'Quelle est la longueur du gros intestin ?', answer: '1,8 m.', },
{ question: 'De quel segment à quel segment s’étend le gros intestin ?', answer: 'De l’angle iléo-caecal à l’anus.', },
{ question: 'Quelle est la fonction principale du gros intestin ?', answer: 'Réabsorption de l’eau et stockage des matières fécales.', },

{ question: 'Où se situe le caecum ?', answer: 'Dans la fosse iliaque droite.', },
{ question: 'Quel organe s’abouche dans le caecum ?', answer: 'L’intestin grêle.', },
{ question: 'Quel appendice anatomique se trouve dans le caecum ?', answer: 'L’appendice vermiforme.', },

{ question: 'De quel niveau part le côlon ascendant ?', answer: 'De la fosse iliaque droite, au niveau de L5.', },
{ question: 'Où se termine le côlon ascendant ?', answer: 'Dans l’hypochondre droit, au niveau de L1.', },

{ question: 'Dans quelle région se situe l’angle colique droit ?', answer: 'Dans l’hypochondre droit.', },

{ question: 'Entre quelles régions le côlon transverse s’étend-il ?', answer: 'De l’hypochondre droit à l’hypochondre gauche.', },
{ question: 'Quel trajet suit le côlon transverse ?', answer: 'Un trajet transversal passant par la partie supérieure de la région ombilicale.', },

{ question: 'Dans quelle région se situe l’angle colique gauche ?', answer: 'Dans l’hypochondre gauche.', },

{ question: 'Où commence et finit le côlon descendant ?', answer: 'De l’hypochondre gauche vers la fosse iliaque gauche (L4).', },

{ question: 'Quelle est la particularité du côlon sigmoïde ?', answer: 'Il s’enroule sur lui-même en boucle en S et se prolonge par le rectum.', },

{ question: 'Quels segments du côlon sont accolés au rétro-péritoine ?', answer: 'Le côlon ascendant et le côlon descendant.', },
{ question: 'Quels segments du côlon sont mobiles grâce à leur méso ?', answer: 'Le caecum, le côlon transverse et le côlon sigmoïde.', },
{ question: 'Quelle pathologie touche essentiellement les segments mobiles du côlon ?', answer: 'Le volvulus.', },
{ question: 'Quelles sont les conséquences d’un volvulus ?', answer: 'Torsion, obstruction du bol alimentaire, et nécrose par occlusion artérielle.', },

{ question: 'Quels sont les trois éléments visibles sur la surface externe du côlon ?', answer: 'Ténias coliques, haustrations, appendices épiploïques.', },
{ question: 'Combien existe-t-il de ténias coliques ?', answer: 'Trois.', },
{ question: 'À quoi correspondent les haustrations ?', answer: 'À des bosselures séparées par des sillons transversaux.', },
{ question: 'À quoi correspondent les plis semi-lunaires ?', answer: 'Aux sillons transversaux visibles en lumière colique.', },

{ question: 'Quelle est la longueur de l’appendice vermiculaire ?', answer: '7 cm.', },
{ question: 'Dans quel segment s’ouvre l’appendice ?', answer: 'Dans le caecum, via l’orifice caeco-appendiculaire.', },
{ question: 'Quel est le nom de la valvule de l’appendice ?', answer: 'La valvule de Gerlach.', },
{ question: 'Quel est le rôle digestif de l’appendice ?', answer: 'Aucun.', },
{ question: 'Quel est le rôle immunitaire de l’appendice chez l’enfant ?', answer: 'Former des lymphoïdes pour apprendre la tolérance aux bactéries commensales.', },
{ question: 'Dans quelle région survient l’appendicite ?', answer: 'En fosse iliaque droite, au point de McBurney.', },

{ question: 'Où commence le rectum ?', answer: 'Au niveau de la charnière recto-sigmoïdienne, en regard de S3.', },
{ question: 'Quelle est la longueur du rectum ?', answer: '15 cm.', },
{ question: 'Quelle est la forme du rectum dans le plan sagittal ?', answer: 'Un S.', },

{ question: 'Quelle est la longueur de l’ampoule rectale ?', answer: '12 cm.', },
{ question: 'Où se situe l’ampoule rectale ?', answer: 'Dans la concavité du sacrum, au-dessus du plancher pelvien.', },
{ question: 'Quel est le rôle de l’ampoule rectale ?', answer: 'Stocker les matières fécales.', },

{ question: 'Qu’est-ce que l’angle ano-rectal ?', answer: 'Le cap anal entre ampoule rectale et canal anal.', },
{ question: 'Quelle est l’angulation de l’angle ano-rectal ?', answer: 'Environ 100 degrés.', },

{ question: 'Quelle est la longueur du canal anal ?', answer: '3 cm.', },
{ question: 'Où se situe le canal anal ?', answer: 'Dans le périnée, sous le plancher pelvien.', },
{ question: 'Quel appareil musculaire entoure le canal anal ?', answer: 'Deux sphincters : lisse et strié.', },

{ question: 'Quelle est la production quotidienne de salive ?', answer: '1,5 L.', },
{ question: 'Quelles sont les fonctions de la salive ?', answer: 'Lubrification et début de la digestion enzymatique.', },

{ question: 'Quelles sont les glandes salivaires mineures ?', answer: 'Labiales, jugales, linguales, palatines.', },

{ question: 'Quelle est la glande salivaire la plus volumineuse ?', answer: 'La glande parotide.', },
{ question: 'Quels éléments traversent la glande parotide ?', answer: 'L’artère carotide externe et le nerf facial.', },
{ question: 'Quel canal excréteur appartient à la parotide ?', answer: 'Le canal de Sténon.', },
{ question: 'Où s’abouche le canal de Sténon ?', answer: 'Dans le vestibule en regard de la 2e molaire supérieure.', },

{ question: 'Quelle glande salivaire est palpable sous la mandibule ?', answer: 'La glande submandibulaire.', },
{ question: 'Quel canal excréteur appartient à la glande submandibulaire ?', answer: 'Le canal de Wharton.', },
{ question: 'Où s’abouche le canal de Wharton ?', answer: 'De chaque côté du frein de la langue, dans la caroncule sublinguale.', },

{ question: 'Quelle glande salivaire est située sous le bord latéral de la langue ?', answer: 'La glande sublinguale.', },
{ question: 'Quels sont les canaux excréteurs de la glande sublinguale ?', answer: 'Les canaux de Rivinus et Walther.', },

{ question: 'Quel est le poids du foie ?', answer: '1,5 kg.', },
{ question: 'Dans quelle région est situé le foie ?', answer: 'Hypochondre droit et épigastre, débordant partiellement dans l’hypochondre gauche.', },
{ question: 'Quel signe clinique indique une augmentation du volume du foie ?', answer: 'Une hépatomégalie.', },

{ question: 'Quel ligament sépare les lobes droit et gauche du foie sur la face supérieure ?', answer: 'Le ligament falciforme.', },
{ question: 'En combien de lobes la face inférieure du foie est-elle divisée ?', answer: 'Quatre : droit, gauche, carré, caudé.', },

{ question: 'Quels sillons forment un H sur la face viscérale du foie ?', answer: 'Les deux sillons sagittaux et le sillon transversal.', },
{ question: 'Que contient le sillon sagittal droit ?', answer: 'La fosse de la vésicule biliaire et la VCI.', },
{ question: 'Que contient le sillon sagittal gauche ?', answer: 'Le ligament rond et le ligament veineux.', },
{ question: 'Que représente le sillon transversal ?', answer: 'Le hile du foie.', },

{ question: 'Que constituent les voies biliaires intrahépatiques ?', answer: 'Des canalicules intralobulaires.', },
{ question: 'Où confluent les voies biliaires intrahépatiques ?', answer: 'Dans les conduits hépatiques droit et gauche.', },
{ question: 'Que forment les conduits hépatiques droit et gauche ?', answer: 'Le canal hépatique commun.', },

{ question: 'Quelles structures forment la voie biliaire principale ?', answer: 'Canal hépatique commun + canal cystique = canal cholédoque.', },
{ question: 'Où s’abouche le canal cholédoque ?', answer: 'Dans la papille duodénale majeure de D2.', },
{ question: 'Dans quelle ampoule se réunissent le cholédoque et le canal de Wirsung ?', answer: 'Dans l’ampoule hépatopancréatique de Vater.', },
{ question: 'Quel sphincter entoure l’ampoule hépatopancréatique ?', answer: 'Le sphincter d’Oddi.', },

{ question: 'Quel est le rôle de la vésicule biliaire ?', answer: 'Stocker la bile entre les digestions.', },
{ question: 'Quel canal relie la vésicule biliaire au cholédoque ?', answer: 'Le canal cystique.', },

{ question: 'Quel est le risque d’une bile trop riche en lipides ?', answer: 'Formation de calculs biliaires.', },
{ question: 'Que provoque l’obstruction du cholédoque par un calcul ?', answer: 'Une cholécystite.', },

{ question: 'Quelles sont les fonctions exocrines du pancréas ?', answer: 'Production de sucs enzymatiques pour la digestion.', },
{ question: 'Quelles sont ses fonctions endocrines ?', answer: 'Sécrétion d’insuline et de glucagon.', },

{ question: 'Quelle est la localisation du pancréas ?', answer: 'Région épigastrique, devant L1-L2.', },
{ question: 'Quelle est la longueur du pancréas ?', answer: '15 cm.', },
{ question: 'Quelles sont les 4 parties du pancréas ?', answer: 'Tête, isthme, corps, queue.', },

{ question: 'Quel est le rapport anatomique du processus unciné ?', answer: 'Avec les vaisseaux mésentériques supérieurs.', },
{ question: 'Vers quel organe est orientée la queue du pancréas ?', answer: 'Vers la rate.', },

{ question: 'Quelles sont les trois artères digestives principales ?', answer: 'Tronc coeliaque, AMS, AMI.', },
{ question: 'Que vascularise le tronc cœliaque ?', answer: 'Foie, rate, estomac, duodénum, pancréas.', },
{ question: 'Que vascularise l’artère mésentérique supérieure ?', answer: 'Intestin grêle, caecum, côlon ascendant, angle droit, 2/3 du côlon transverse.', },
{ question: 'Que vascularise l’artère mésentérique inférieure ?', answer: '1/3 gauche du côlon transverse, côlon descendant, sigmoïde, rectum.', },

{ question: 'Quelles veines forment la veine porte ?', answer: 'Mésentérique supérieure, mésentérique inférieure, splénique.', },
{ question: 'Où se jette la veine porte ?', answer: 'Dans le foie.', },
{ question: 'Que deviennent les veines intrahépatiques ?', answer: 'Elles forment les veines hépatiques.', },
{ question: 'Où se jettent les veines hépatiques ?', answer: 'Dans la veine cave inférieure.', },

{ question: 'Qu’est-ce que la première barrière hépatique ?', answer: 'Détoxification du sang veineux riche en nutriments.', },
{ question: 'Quelles molécules sont éliminées par le foie ?', answer: 'Alcool, médicaments, excès métaboliques.', },

{ question: 'Quelle est l’unité fonctionnelle du foie ?', answer: 'Le lobule hépatique.', },
{ question: 'Quels éléments y convergent ?', answer: 'Divisions de la veine porte, de l’artère hépatique et des voies biliaires.', },
