{ question: 'Qu’est-ce que le cycle cellulaire ?', answer: 'Le processus fondamental par lequel une cellule-mère donne deux cellules-filles identiques entre elles et identiques à la cellule d’origine.', },
{ question: 'Que montre l’observation de cellules en culture lors d’une division ?', answer: 'Une cellule triangulaire se divise pour former deux cellules identiques.', },
{ question: 'Qu’est-ce que la prolifération cellulaire ?', answer: 'La multiplication et l’augmentation du nombre cellulaire.', },
{ question: 'Pourquoi les cellules doivent-elles se diviser ?', answer: 'Pour participer à l’homéostasie générale et assurer le fonctionnement de l’organisme.', },
{ question: 'De quoi dépend la taille d’un organe ?', answer: 'De la taille des cellules et du nombre de divisions cellulaires ainsi que de l’apoptose.', },
{ question: 'Que distingue la coloration nucléaire dans un embryon d’oursin ?', answer: 'Les cellules en interphase (bleu pâle) et les cellules en mitose (chromosomes condensés).', },
{ question: 'Que signifie G, S et M dans le cycle cellulaire ?', answer: 'G = Gap, S = Synthèse, M = Mitose.', },
{ question: 'Qu’est-ce que la phase G0 ?', answer: 'Un état quiescent mais actif.', },
{ question: 'Quels sont les deux devenirs possibles d’une cellule en G1 ?', answer: 'Entrer en cycle ou sortir en G0.', },
{ question: 'Quels sont les devenirs possibles d’une cellule en G0 ?', answer: 'Re-rentrer dans le cycle, différenciation, apoptose ou sénescence.', },
{ question: 'Toutes les cellules d’un tissu se divisent-elles ?', answer: 'Non, il existe une hétérogénéité selon les types cellulaires.', },
{ question: 'Quels types de cellules ne se divisent pas ?', answer: 'Les cellules différenciées en G0 comme les neurones.', },
{ question: 'Quels types de cellules se divisent peu ?', answer: 'Certaines cellules comme les hépatocytes après dédifférenciation.', },
{ question: 'Quels types de cellules se divisent beaucoup ?', answer: 'Les cellules épithéliales grâce à leurs nombreuses cellules souches.', },
{ question: 'Quelle est la technique qui incorpore la thymidine radioactive ?', answer: 'Le marquage à la thymidine-3H pendant la phase S.', },
{ question: 'Comment le BrDU est-il révélé ?', answer: 'Par immunohistochimie avec anticorps couplés à un fluorochrome.', },
{ question: 'Que montre la colocalisation BrDU/DAPI en fluorescence ?', answer: 'Un signal rose indiquant les noyaux en phase S.', },
{ question: 'Que mesure la cytométrie en flux pour étudier le cycle ?', answer: 'La fluorescence issue d’intercalants de l’ADN.', },
{ question: 'Pourquoi ne peut-on pas distinguer G0 de G1 en cytométrie ?', answer: 'Car elles ont la même quantité d’ADN.', },
{ question: 'Pourquoi ne peut-on pas distinguer G2 de M en cytométrie ?', answer: 'Car elles possèdent aussi la même quantité d’ADN.', },
{ question: 'Que représente la surface sous un pic en cytométrie ?', answer: 'Le nombre de cellules dans cette phase.', },
{ question: 'Qu’est-ce qu’une population asynchrone ?', answer: 'Une population avec des cellules dans toutes les phases du cycle.', },
{ question: 'Combien de chromatides possède un chromosome ?', answer: 'Une chromatide correspond à une molécule d’ADN.', },
{ question: 'Quelle est la durée moyenne d’un cycle cellulaire humain ?', answer: '24 heures.', },
{ question: 'Quelle est la durée typique de la phase G1 ?', answer: 'Environ 10 heures.', },
{ question: 'Quelle est la durée de la phase S ?', answer: 'Environ 9 heures.', },
{ question: 'Quelle est la durée de la phase G2 ?', answer: 'Environ 4 heures.', },
{ question: 'Quelle est la durée de la mitose ?', answer: 'Environ 1 heure.', },
{ question: 'Pourquoi les phases G1 et G2 sont-elles variables ?', answer: 'Leur durée dépend des besoins et réserves de la cellule.', },
{ question: 'Quels sont les trois points de contrôle du cycle ?', answer: 'Le point de contrôle G1, celui du fuseau et celui d’entrée en mitose.', },
{ question: 'Quels points de contrôle sont obligatoires ?', answer: 'G1 et fuseau.', },
{ question: 'De quoi dépend le point de contrôle d’entrée en mitose ?', answer: 'Uniquement de l’état de l’ADN.', },
{ question: 'Que signifie CDK ?', answer: 'Cyclin Dependent Kinase.', },
{ question: 'Quel rôle ont les complexes Cdk/cycline ?', answer: 'Ils régulent les phases du cycle cellulaire.', },
{ question: 'La Cdk seule est-elle active ?', answer: 'Non, elle nécessite l’association avec une cycline.', },
{ question: 'Quel est le rôle d’une kinase ?', answer: 'Phosphoryler un substrat en transférant un phosphate de l’ATP.', },
{ question: 'Quel est le rôle des phosphatases ?', answer: 'Retirer des phosphates.', },
{ question: 'Quel est le rôle de CAK ?', answer: 'Phosphorylation activatrice de la Cdk liée à la cycline.', },
{ question: 'Quel est le rôle de Wee1 et Myt1 ?', answer: 'Phosphorylation inhibitrice du complexe Cdk/cycline.', },
{ question: 'Quel est le rôle de Cdc25 ?', answer: 'Déphosphorylation activatrice.', },
{ question: 'Qu’est-ce qu’un CKI ?', answer: 'Un inhibiteur de Cdk.', },
{ question: 'Quels CKI inhibent Cdk4/6 ?', answer: 'p15 et p16.', },
{ question: 'Quels CKI inhibent un complexe déjà formé ?', answer: 'p21 et p27.', },
{ question: 'Quel est l’effet de p27 sur Cdk2/Cycline E ?', answer: 'Il l’inhibe.', },
{ question: 'Quel est l’effet des facteurs mitogènes sur p27 ?', answer: 'Ils favorisent son association avec Cdk4/Cycline D et libèrent Cdk2/Cycline E.', },
{ question: 'Quel est l’ordre d’apparition des cyclines ?', answer: 'D puis E puis A puis B.', },
{ question: 'Quelle cycline active Cdk4/6 ?', answer: 'La cycline D.', },
{ question: 'Quelle cycline active Cdk2 en fin de G1 ?', answer: 'La cycline E.', },
{ question: 'Quelle cycline active Cdk2 en S ?', answer: 'La cycline A.', },
{ question: 'Quelle cycline active Cdk1 en G2/M ?', answer: 'La cycline B.', },
{ question: 'Pourquoi G1 est-elle une phase de croissance ?', answer: 'Pour reconstituer les réserves et synthétiser ARN et protéines.', },
{ question: 'Qu’est-ce que le point de restriction ?', answer: 'Une transition critique rendant le cycle indépendant des facteurs extérieurs.', },
{ question: 'Que se passe-t-il si une cellule n’a pas assez de facteurs mitogènes ?', answer: 'Elle reste en G1 ou sort en G0.', },
{ question: 'Quel récepteur activent les facteurs mitogènes ?', answer: 'Un récepteur transmembranaire à activité tyrosine kinase.', },
{ question: 'Que provoque la liaison ligand–récepteur ?', answer: 'Dimérisation et autophosphorylation du récepteur.', },
{ question: 'Quelle cascade mène à l’activation de Myc ?', answer: 'Activation MAPK → entrée dans le noyau → phosphorylation d’un facteur → expression de Myc.', },
{ question: 'Quels gènes Myc active-t-il ?', answer: 'Cycline D, E2F, Cdc25A, p21/p27.', },
{ question: 'Que produit la phosphorylation de Rb ?', answer: 'La libération d’E2F.', },
{ question: 'Que permet E2F ?', answer: 'La transcription de gènes de la phase S.', },
{ question: 'Quel complexe permet l’entrée en S ?', answer: 'Cycline E/Cdk2.', },
{ question: 'Quel est le rôle des CKI pour sortir vers G0 ?', answer: 'Ils bloquent la poursuite du cycle.', },
{ question: 'Quel est le rôle de SCF sur p27 ?', answer: 'Il l’ubiquitine et mène à sa dégradation par le protéasome.', },
