{ question: 'Quelles sont les caractéristiques générales de la phase S ?', answer: 'Réplication de l’ADN avec transcription active tant que l’ADN est décondensé, mise en place et maintien de la cohésine, duplication du centrosome, phosphorylation puis ubiquitination de la cycline E par SCF.', },
{ question: 'Quel complexe participe à la réplication en phase S ?', answer: 'Le complexe cycline A-Cdk2.', },
{ question: 'Quel est le rôle de cycline A/Cdk2 dans la phase S ?', answer: 'Former le complexe de pré-amorçage et l’amorçage des fourches de réplication.', },
{ question: 'Toutes les régions d’ADN sont-elles répliquées simultanément ?', answer: 'Non, certaines portions se répliquent plus tôt et d’autres restent transcriptionnellement actives.', },
{ question: 'Qu’est-ce que la cohésine ?', answer: 'Un complexe protéique formant un anneau (Smc3/Smc1/Scc1/Scc3) permettant de maintenir deux brins d’ADN ensemble.', },
{ question: 'Quand la cohésine est-elle chargée ?', answer: 'En phase G1 grâce au complexe SCC2/4, puis maintenue durant toute la réplication en phase S.', },
{ question: 'Quel est le rôle fondamental de la cohésine ?', answer: 'Maintenir ensemble les deux chromatides sœurs jusqu’à leur séparation en mitose.', },
{ question: 'Qu’est-ce que le centrosome ?', answer: 'Un complexe constitué de deux centrioles perpendiculaires entourés de matériel péricentriolaire.', },
{ question: 'Quel est le rôle du centrosome en interphase ?', answer: 'Nucléation et organisation du réseau de microtubules.', },
{ question: 'Quel est le rôle du centrosome en mitose ?', answer: 'Former les deux pôles du fuseau mitotique après duplication.', },
{ question: 'Quel type de microtubules composent les centrioles ?', answer: 'Des microtubules organisés en 9 triplets (A, B, C).', },
{ question: 'Les microtubules des centrioles sont-ils sensibles au nocodazole ?', answer: 'Non, ils sont non dépolymérisables par les drogues comme le nocodazole.', },
{ question: 'Qu’est-ce que le complexe γ-TuRC ?', answer: 'Un complexe contenant la γ-tubuline permettant l’ancrage et la nucléation des microtubules par leur extrémité (-).', },
{ question: 'Par quelles kinases le γ-TuRC est-il régulé ?', answer: 'Plk et Aurora A.', },
{ question: 'Quand se produisent les duplications du centrosome et de l’ADN ?', answer: 'En phase S.', },
{ question: 'Quel est le type de duplication du centrosome ?', answer: 'Une duplication semi-conservative et synchronisée avec la réplication de l’ADN.', },
{ question: 'Quel complexe moléculaire contrôle à la fois la réplication de l’ADN et la duplication du centrosome ?', answer: 'Le complexe Cdk2/Cycline A.', },
{ question: 'Comment se déroule la première séparation des centrioles en fin de G1 ?', answer: 'Cdk2/Cycline E phosphoryle la nucléophosmine (NPM), permettant sa reconnaissance par SCF et sa dégradation, ce qui écarte légèrement les centrioles.', },
{ question: 'Quand apparaissent les pro-centrioles ?', answer: 'En phase S.', },
{ question: 'Que deviennent les pro-centrioles en fin de phase S ?', answer: 'Ils deviennent deux centrosomes complets formés chacun de deux centrioles perpendiculaires.', },
{ question: 'Quelle kinase contrôle la deuxième séparation des centrosomes en G2 ?', answer: 'Aurora A associée aux kinases Plk et Cdk1/Cycline B.', },
{ question: 'Qu’est-ce qui entraîne la troisième séparation des centrosomes en mitose ?', answer: 'L’allongement du fuseau mitotique par polymérisation des microtubules.', },
{ question: 'Quel complexe moléculaire phosphoryle la kinésine-5 en mitose ?', answer: 'Cdk1/Cycline B.', },
{ question: 'Quel est l’effet d’une mutation de Plk sur le centrosome ?', answer: 'Absence de duplication des centrosomes, formation d’un fuseau anormal et incapacité de la cellule à se diviser correctement.', },
{ question: 'Qu’est-ce qu’un fuseau tripolaire ?', answer: 'Un fuseau formé par trois centrosomes provoquant une répartition incorrecte des chromosomes.', },
{ question: 'Qu’est-ce qu’un fuseau monopolaire ?', answer: 'Un fuseau dérivé d’un seul centrosome non dupliqué empêchant la séparation des chromatides.', },
{ question: 'Quelles sont les kinases impliquées dans la phase S ?', answer: 'Cdk2/Cycline E et Cdk2/Cycline A.', },
{ question: 'Quel est le point de contrôle principal en G2 ?', answer: 'Le contrôle d’entrée en mitose.', },
{ question: 'Quelles anomalies activent ATR/ATM en G2 ?', answer: 'Les lésions de l’ADN causées par exemple par les UV.', },
{ question: 'Quel est le rôle d’ATR/ATM ?', answer: 'Activer les kinases de réparation et instaurer un arrêt du cycle.', },
{ question: 'Quelle est la réponse immédiate à une lésion de l’ADN en G2 ?', answer: 'Phosphorylation de Cdc25 par Chk et sa dégradation par SCF, empêchant l’activation de Cdk1/Cycline B.', },
{ question: 'Pourquoi la dégradation de Cdc25 empêche l’entrée en mitose ?', answer: 'Car Cdc25 ne peut plus retirer les phosphates inhibiteurs ajoutés par Wee1 et Myt1.', },
{ question: 'Que se passe-t-il si le signal de lésion persiste en G2 ?', answer: 'Activation de p53, synthèse de p21 et inhibition durable de Cdk1/Cycline B.', },
{ question: 'Comment Cdk1/Cycline B est-elle régulée en G2 ?', answer: 'Par CAK, Wee1, Myt1, Cdc25 et Plk.', },
{ question: 'Comment est activé MPF en fin de G2 ?', answer: 'Plk phosphoryle Cdc25 qui active Cdk1/Cycline B.', },
{ question: 'Quelle découverte a révélé l’existence du MPF ?', answer: 'L’injection du cytoplasme d’un œuf mature dans un ovocyte bloqué en G2 déclenche la mitose.', },
{ question: 'Quelle est la composition biochimique du MPF ?', answer: 'Cdk1/Cycline B.', },
{ question: 'Quel est le principal point de contrôle de la mitose ?', answer: 'Le point de contrôle du fuseau en métaphase/anaphase.', },
{ question: 'Quelles sont les phases de la mitose ?', answer: 'Prophase, prométaphase, métaphase, anaphase, télophase, cytodiérèse.', },
{ question: 'Quels événements caractérisent la prophase ?', answer: 'Condensation de la chromatine, désassemblage du nucléole, formation des kinétochores, organisation du fuseau, séparation des centrosomes.', },
{ question: 'Pourquoi l’activité MPF augmente-t-elle de manière exponentielle en prophase ?', answer: 'Cdk1/Cycline B s’autophosphoryle, inactive Wee1, active Cdc25 et reste séquestrée dans le noyau.', },
{ question: 'Quels acteurs permettent la condensation de la chromatine ?', answer: 'Histones H1 et H3, topoisomérase, condensine, Aurora B et Cdk1/Cycline B.', },
{ question: 'Quel est le rôle de la condensine ?', answer: 'Former des boucles de chromatine et compacter les chromatides.', },
{ question: 'Quel est le rôle de la topoisomérase II ?', answer: 'Désenchevêtrer l’ADN et permettre la compaction correcte.', },
{ question: 'Quel changement microtubulaire initie la formation du fuseau mitotique ?', answer: 'Destruction du réseau interphasique et augmentation de la dynamique des microtubules.', },
{ question: 'Quel est le rôle des dynéines dans la prophase ?', answer: 'Séparer et écarter les centrosomes en marchant vers les pôles (-) des microtubules.', },
{ question: 'Quel est le rôle de la kinésine-14 ?', answer: 'Rapprocher les centrosomes en marchant vers le pôle (-).', },
{ question: 'Qu’est-ce que le centromère dans la mise en place du kinétochore ?', answer: 'Une région d’ADN constituée d’hétérochromatine et d’ADN satellite alpha où se forme le kinétochore.', },
{ question: 'Combien de protéines environ constituent le kinétochore ?', answer: 'Environ 90 protéines.', },
{ question: 'Quand débute la mise en place du kinétochore ?', answer: 'En phase G2.', },
{ question: 'Quel est le rôle du kinétochore ?', answer: 'Faire le lien entre le chromatide et les microtubules.', },
{ question: 'Quelle histone spécifique est présente au niveau du centromère ?', answer: 'L’histone CENP-H3.', },
{ question: 'Que comporte la plaque interne du kinétochore ?', answer: 'Des protéines constitutives présentes tout le long du cycle et des protéines passagères présentes en G2.', },
{ question: 'Quand les microtubules peuvent-ils entrer en contact avec le kinétochore ?', answer: 'Après la rupture de l’enveloppe nucléaire, pas en prophase.', },
{ question: 'Quels sont les évènements du début de prométaphase ?', answer: 'Centrosomes séparés, chromatine condensée, existence de microtubules, individualisation des chromosomes.', },
{ question: 'Quel évènement marque le milieu de la prométaphase ?', answer: 'La formation du fuseau mitotique.', },
{ question: 'Que se passe-t-il en fin de prométaphase ?', answer: 'Les chromosomes commencent à s’aligner sur le plan équatorial.', },
{ question: 'Quels sont les quatre évènements de la prométaphase ?', answer: 'Réorganisation du Golgi et du RE, rupture de l’enveloppe nucléaire, capture des chromosomes, centrage et allongement du fuseau.', },
{ question: 'Quel est le rôle de Cdk1/CyclineB2 et Plk sur l’appareil de Golgi ?', answer: 'Phosphorylent les protéines responsables de l’empilement des sacs, induisant leur dissociation en tubules puis en vésicules.', },
{ question: 'Quelle phosphorylation provoque le désassemblage des pores nucléaires ?', answer: 'La phosphorylation des protéines du pore nucléaire, potentiellement par Cdk1/Cycline B.', },
{ question: 'Quelle enzyme phosphoryle les lamines A/C en prométaphase ?', answer: 'MPF (Cdk1/Cycline B).', },
{ question: 'Quelles sont les deux conséquences principales de la rupture de l’enveloppe nucléaire en prométaphase ?', answer: 'Les microtubules entrent en contact avec les chromosomes et le fuseau est stabilisé par des facteurs nucléaires.', },
{ question: 'Quel type d’attachement se fait d’abord lors de la capture des chromosomes ?', answer: 'Un attachement monopolaire.', },
{ question: 'Que permet la dépolymérisation du microtubule kinétochorien lors de la capture ?', answer: 'Le rapprochement du chromosome vers le centrosome d’origine.', },
{ question: 'Quand l’attachement bipolaire se met-il en place ?', answer: 'Après capture par des microtubules du pôle opposé.', },
{ question: 'Comment la kinésine 5 participe-t-elle à l’allongement du fuseau ?', answer: 'En marchant vers le pôle plus des microtubules opposés, séparant les centrosomes.', },
{ question: 'Quel effet provoque l’ablation d’un chromosome sur les microtubules ?', answer: 'Une baisse locale de la densité en microtubules.', },
{ question: 'Quels sont les trois types de microtubules du fuseau ?', answer: 'Microtubules kinétochoriens, polaires et astériens.', },
{ question: 'Qu’est-ce que la plaque métaphasique ?', answer: 'L’alignement bipolaire des chromosomes au centre du fuseau.', },
{ question: 'Quel est le rôle de la cohésine en métaphase ?', answer: 'Maintenir les chromatides sœurs malgré les tensions opposées.', },
{ question: 'Pourquoi la longueur du fuseau reste-t-elle constante en métaphase ?', answer: 'Car les microtubules se polymérisent au pôle + et se dépolymérisent au pôle –.', },
{ question: 'Quel est le rôle d’Aurora B en cas d’attachement unipolaire ?', answer: 'Dissocier un kinétochore pour permettre un attachement bipolaire correct.', },
{ question: 'À quelle phase réalise-t-on un caryotype ?', answer: 'En métaphase.', },
{ question: 'Quels sont les critères de classement des chromosomes en caryotype ?', answer: 'Longueur, position du centromère, présence de constrictions secondaires.', },
{ question: 'Qu’est-ce qu’un chromosome métacentrique ?', answer: 'Un chromosome dont le centromère est situé au centre.', },
{ question: 'Qu’est-ce qu’un chromosome acrocentrique ?', answer: 'Un chromosome dont le centromère est proche d’une extrémité.', },
{ question: 'Quel est le rôle du point de contrôle mitotique ?', answer: 'Vérifier l’attachement bipolaire de tous les chromosomes avant l’anaphase.', },
{ question: 'Quelle condition permet l’activation de l’APC en métaphase ?', answer: 'L’attachement bipolaire de tous les chromosomes sur la plaque.', },
{ question: 'Quel est le rôle de l’APC ?', answer: 'Ubiquitiner des protéines non phosphorylées comme les cyclines A et B et la sécurine.', },
{ question: 'Quel complexe active l’APC ?', answer: 'Cdk1/Cycline B et Plk par phosphorylation puis association à Cdc20.', },
{ question: 'Pourquoi l’APC ne peut-il pas être actif si un chromosome est mal attaché ?', answer: 'Parce qu’une protéine de contrôle du fuseau reste fixée sur l’APC.', },
{ question: 'Quels sont les deux évènements majeurs de l’anaphase ?', answer: 'Séparation des chromatides sœurs et migration des chromosomes fils.', },
{ question: 'Quel mécanisme débute la séparation des chromatides ?', answer: 'Le clivage de la cohésine par la séparase.', },
{ question: 'Quel est le rôle de Plk sur la cohésine en prophase ?', answer: 'Départ de la cohésine des bras des chromatides.', },
{ question: 'Quel est le rôle de la séparase ?', answer: 'Cliver la cohésine au niveau du kinétochore.', },
{ question: 'Quelle protéine inhibe la séparase tant qu’elle n’est pas dégradée ?', answer: 'La sécurine.', },
{ question: 'Qu’est-ce qui déclenche l’activation finale de la séparase ?', answer: 'L’ubiquitination de la sécurine par l’APC.', },
{ question: 'Qu’est-ce que l’anaphase A ?', answer: 'La dépolymérisation des microtubules kinétochoriens qui attire les chromosomes vers les pôles.', },
{ question: 'Qu’est-ce que l’anaphase B ?', answer: 'L’allongement du fuseau par glissement des microtubules polaires et action des moteurs moléculaires.', },
{ question: 'Qu’entraîne la dégradation de la cycline B en anaphase ?', answer: 'L’inactivation du MPF.', },
{ question: 'Pourquoi l’inactivation du MPF permet-elle la télophase ?', answer: 'Car les lamines, condensines et autres protéines phosphorylées sont déphosphorylées.', },
{ question: 'Quels sont les évènements clés de la télophase ?', answer: 'Arrivée des chromosomes aux pôles, reformation de l’enveloppe nucléaire, décondensation, formation de l’anneau contractile.', },
{ question: 'Qu’est-ce que la cytodiérèse ?', answer: 'La séparation physique du cytoplasme en deux cellules filles.', },
{ question: 'De quoi est composé l’anneau contractile ?', answer: 'D’actine et de myosine.', },
{ question: 'Quel événement permet l’activation de la myosine lors de la cytodiérèse ?', answer: 'La déphosphorylation de la MLC après la protéolyse de la cycline B.', },
{ question: 'Qu’est-ce que le corps intermédiaire ?', answer: 'Le pont cytoplasmique final reliant les deux cellules filles avant rupture.', },
{ question: 'Que peut provoquer un dérèglement du cycle cellulaire ?', answer: 'Un cancer.', },
{ question: 'Quel est le rôle d’Aurora A ?', answer: 'Séparation des centrosomes.', },
{ question: 'Quel est le rôle d’Aurora B ?', answer: 'Condensation de l’ADN et appariement bipolaire des chromosomes.', },
{ question: 'Que provoque Cdk1/Cycline B sur la condensine ?', answer: 'La condensation de l’ADN.', },
{ question: 'Quel est l’effet de Plk sur Cdc25 ?', answer: 'Permet l’accumulation de MPF dans le noyau.', },
{ question: 'Quelles protéines sont ciblées par l’APC ?', answer: 'Cycline A, cycline B et sécurine.', },
