#!/usr/bin/env python3
"""Append FC4, FC5, FC6 to l3_data_promo.py"""

TARGET = "/Users/cyrilwisa/Desktop/diploma/scripts/l3_data_promo.py"

fc4 = [
    ("Quelle est la définition de la prévention selon l\u2019OMS (1948) ?", "L\u2019ensemble des actions, attitudes et comportements qui tendent à éviter la survenue de maladies ou de traumatismes, ou à maintenir et améliorer la santé."),
    ("Quel est l\u2019objectif de la prévention primaire ?", "Empêcher l\u2019apparition d\u2019une maladie en ciblant les individus en bonne santé (indemnes de la maladie)."),
    ("Quel est l\u2019objectif de la prévention secondaire ?", "Détecter précocement une maladie chez des individus malades dans les premiers stades, afin de commencer un traitement plus efficace."),
    ("Quel est l\u2019objectif de la prévention tertiaire ?", "Réduire les conséquences de la maladie, prévenir les complications et favoriser la réinsertion sociale et professionnelle."),
    ("Sur quoi agit la prévention primaire en termes épidémiologiques ?", "Elle vise à réduire l\u2019incidence (apparition de nouveaux cas) d\u2019une maladie dans une population."),
    ("Sur quoi agit la prévention secondaire en termes épidémiologiques ?", "Elle vise à diminuer la prévalence (nombre total de malades et durée de la maladie) dans une population."),
    ("Qu\u2019est-ce que la loi Evin en matière de prévention primaire ?", "Une loi interdisant de fumer dans les lieux publics et restreignant la publicité du tabac pour limiter la consommation. C\u2019est un acte législatif de prévention primaire."),
    ("Donnez un exemple d\u2019acte médical de prévention primaire.", "La vaccination : prévention spécifique contre certaines maladies infectieuses."),
    ("Donnez un exemple d\u2019acte social de prévention primaire.", "Les groupes de parole pour les proches aidants de patients Alzheimer."),
    ("La prévention primaire peut-elle être active et passive ?", "Oui. Active : actions volontaires (vaccination). Passive : mesures environnementales (interdiction du tabac dans les lieux publics)."),
    ("La prévention primaire peut-elle être sanitaire et non sanitaire ?", "Oui. Sanitaire : vaccination, éducation à la santé. Non sanitaire : amélioration des conditions de vie, développement économique."),
    ("Comment la prévention primaire peut-elle agir sur le diabète de type 2 ?", "Par l\u2019éducation nutritionnelle, la réduction du poids, l\u2019augmentation de l\u2019activité physique, la réduction des graisses saturées et l\u2019augmentation des fibres."),
    ("Qu\u2019est-ce que le dépistage en prévention secondaire ?", "L\u2019identification des maladies au plus tôt pour permettre une prise en charge rapide et réduire la progression de la maladie."),
    ("Pourquoi le dépistage peut-il augmenter la prévalence ?", "Davantage de cas sont reconnus (dépistage plus systématique) et la durée de vie des patients peut être allongée grâce à un traitement précoce."),
    ("Donnez un exemple de dépistage en prévention secondaire.", "La mammographie pour le dépistage du cancer du sein chez les femmes."),
    ("Quels sont les avantages du dépistage ?", "Découverte précoce, réduction de la morbi-mortalité, traitements moins lourds, réconfort des négatifs, sensibilisation des professionnels."),
    ("Quels sont les inconvénients du dépistage ?", "Durée apparente plus longue de la maladie, risques liés aux tests invasifs, faux positifs (traitements inutiles, anxiété) et faux négatifs (retard de traitement)."),
    ("Qu\u2019est-ce qu\u2019un faux positif ?", "Le test indique que la personne a la maladie alors qu\u2019elle ne l\u2019a pas, pouvant mener à des traitements inutiles et de l\u2019anxiété."),
    ("Qu\u2019est-ce qu\u2019un faux négatif ?", "Le test indique que la personne n\u2019a pas la maladie alors qu\u2019elle l\u2019a, pouvant retarder le traitement et aggraver la maladie."),
    ("Qu\u2019est-ce qu\u2019un dépistage simple ?", "1 ou 2 tests simples sur une population a priori en bonne santé, peu coûteux mais peu précis. Ex : mammographie, test immunologique des selles."),
    ("Qu\u2019est-ce qu\u2019un dépistage complexe ?", "Plusieurs examens diagnostiques sur une population a priori malade, coûteux mais précis. Ex : biopsie, coloscopie, examen bactériologique."),
    ("Qu\u2019est-ce que le dépistage individuel ?", "Un dépistage chez des individus qui ont déjà recours aux soins (hospitalisation, consultation). Ex : glycémie chez les patients à risque de diabète."),
    ("Qu\u2019est-ce que le dépistage organisé (de masse) ?", "Un dépistage où les individus sont recrutés activement dans la communauté via des campagnes. Ex : mammographie pour les femmes de 50-74 ans."),
    ("Qu\u2019est-ce que le dépistage ciblé ?", "Un dépistage de sous-populations à haut risque selon des critères définis. Ex : coloscopie dans le syndrome de Lynch."),
    ("Qu\u2019est-ce que le dépistage systématique ?", "Un dépistage de toute la population sans critères de sélection (sauf l\u2019âge). Ex : mammographie tous les 2 ans pour les femmes de 50 à 74 ans."),
    ("Quels sont les paramètres justifiant un dépistage concernant la maladie ?", "Fréquence, gravité, curabilité, évolution naturelle connue, diagnostic possible et impact positif du traitement précoce."),
    ("Quels sont les paramètres justifiant un dépistage concernant la population ?", "Sensibilisation à la maladie, acceptation du test, accessibilité des structures, données démographiques disponibles et priorité du dépistage."),
    ("Quelles sont les propriétés d\u2019un bon test de dépistage ?", "Simplicité, acceptabilité, sécurité, coût faible, efficience, reproductibilité et validité."),
    ("Qu\u2019est-ce que la simplicité d\u2019un test de dépistage ?", "Résultat rapide, mise en œuvre étendue sur tout le territoire, facilité d\u2019utilisation avec possibilité de formation large."),
    ("Qu\u2019est-ce que l\u2019acceptabilité d\u2019un test de dépistage ?", "Une notion subjective influencée par des facteurs personnels et socioculturels. La volonté des individus à participer est clé."),
    ("Qu\u2019est-ce que la reproductibilité d\u2019un test ?", "La capacité à donner des résultats constants lorsqu\u2019il est effectué par deux examinateurs différents ou par le même examinateur à différents moments."),
    ("Qu\u2019est-ce que la validité d\u2019un test de dépistage ?", "La capacité à isoler correctement les malades des sujets sains, mesurée par la sensibilité et la spécificité."),
    ("Qu\u2019est-ce que le gold standard en dépistage ?", "L\u2019examen de référence considéré comme le plus fiable pour diagnostiquer la maladie. Tous les autres tests sont comparés à ce standard."),
    ("Quelle est la formule de la sensibilité ?", "Sensibilité = VP / (VP + FN). C\u2019est la proportion de vrais malades correctement identifiés par le test."),
    ("Quelle est la formule de la spécificité ?", "Spécificité = VN / (VN + FP). C\u2019est la proportion de vrais non-malades correctement identifiés par le test."),
    ("Quelle est la formule de la VPP ?", "VPP = VP / (VP + FP). C\u2019est la probabilité qu\u2019un individu testé positif soit réellement malade."),
    ("Quelle est la formule de la VPN ?", "VPN = VN / (VN + FN). C\u2019est la probabilité qu\u2019un individu testé négatif soit réellement non malade."),
    ("Sensibilité et spécificité sont-elles intrinsèques ou extrinsèques ?", "Intrinsèques : elles mesurent la performance du test indépendamment de la prévalence dans la population."),
    ("VPP et VPN sont-elles intrinsèques ou extrinsèques ?", "Extrinsèques : elles dépendent de la prévalence de la maladie dans la population testée."),
    ("Comment varie la VPP si la prévalence augmente ?", "Si la prévalence augmente, la VPP augmente également (plus de vrais malades parmi les positifs)."),
    ("Qu\u2019est-ce que la courbe ROC ?", "Une courbe représentant la sensibilité (ordonnée) en fonction de 1 - spécificité (abscisse) pour différents seuils du test."),
    ("Où se situe le test optimal sur la courbe ROC ?", "Le plus proche du point de coordonnées (Se = 1, 1 - Sp = 0), c\u2019est-à-dire sensibilité maximale et spécificité maximale."),
    ("Qu\u2019est-ce que l\u2019AUC de la courbe ROC ?", "L\u2019aire sous la courbe mesurant la capacité globale de discrimination du test. AUC = 0,5 = nul, > 0,9 = excellent."),
    ("Que signifie une AUC entre 0,7 et 0,8 ?", "Une capacité de discrimination modérée. Le test montre une classification décente mais pas optimale."),
    ("Que signifie une AUC entre 0,8 et 0,9 ?", "Une bonne capacité de discrimination. Le test est assez performant pour distinguer malades et non malades."),
    ("Comment le choix du seuil affecte-t-il sensibilité et spécificité ?", "Abaisser le seuil augmente la sensibilité (moins de FN) mais diminue la spécificité (plus de FP), et inversement."),
    ("Quel est le but de la prévention tertiaire ?", "Réduire la prévalence des incapacités chroniques ou des récidives, limiter les complications et favoriser l\u2019autonomie."),
    ("Donnez un exemple de prévention tertiaire pour le diabète.", "Apprentissage de la prise de glycémie, éducation alimentaire, soins de pédicurie-podologie pour prévenir le mal perforant plantaire."),
    ("Qu\u2019est-ce que le mal perforant plantaire chez le diabétique ?", "Une lésion grave du pied (ulcération) liée à la neuropathie et à l\u2019artériopathie diabétique, pouvant mener à l\u2019amputation."),
    ("Comment prévenir les lésions des pieds chez le diabétique ?", "Soins de pédicurie réguliers, éducation du patient, évaluation du chaussage adapté et évaluation régulière du risque podologique."),
    ("Qu\u2019est-ce que l\u2019éducation thérapeutique comme prévention tertiaire ?", "L\u2019apprentissage par le patient des stratégies d\u2019autogestion de sa maladie pour limiter les conséquences et améliorer l\u2019adhésion au traitement."),
    ("Qu\u2019est-ce que la prévention universelle ?", "Des actions de prévention destinées à toute la population sans distinction. Ex : PNNS (Programme National Nutrition Santé)."),
    ("Qu\u2019est-ce que la prévention orientée ?", "Des actions ciblant des sous-groupes exposés à des risques spécifiques. Ex : vaccination antigrippale chez les plus de 65 ans, prévention des addictions chez les jeunes."),
    ("Qu\u2019est-ce que la prévention ciblée ?", "Des actions destinées aux malades reposant sur l\u2019apprentissage de la gestion de la maladie et de son traitement. Ex : éducation thérapeutique."),
    ("Qu\u2019est-ce que le PNNS (Programme National Nutrition Santé) ?", "Un programme lancé en janvier 2001 visant à améliorer la nutrition et l\u2019activité physique. Il en est au PNNS 4 (2017-2021)."),
    ("Quelles sont les missions du PNNS ?", "Définir les objectifs nutritionnels, éduquer la population, prévenir les troubles nutritionnels, surveiller l\u2019état nutritionnel, développer la formation et la recherche."),
    ("Quels sont les 3 types de grippe saisonnière ?", "Type A (le plus courant et grave), type B (moins répandu et sévère), type C (rare, généralement bénin)."),
    ("Combien de cas graves et de décès la grippe cause-t-elle mondialement chaque année ?", "3 à 5 millions de cas graves et 250 000 à 500 000 décès, principalement chez les plus de 65 ans."),
    ("Quelles personnes sont à risque de complications grippales ?", "Personnes âgées (\u2265 65 ans), immunodéprimés, femmes enceintes, jeunes enfants et personnes atteintes de maladies chroniques."),
    ("Comment se transmet la grippe saisonnière ?", "Par inhalation de gouttelettes respiratoires (toux, éternuements) et par contact avec des surfaces contaminées via les mains."),
    ("Quel est le seuil diagnostique du diabète par glycémie veineuse à jeun ?", "Si GAJ \u2265 2 g/l : diabète confirmé. Si GAJ entre 1,26 et 2 g/l : un second test est nécessaire. Confirmation si deuxième GAJ \u2265 1,26 g/l."),
    ("Quel rythme de dépistage du diabète si la GAJ est < 1,10 g/l ?", "Un dépistage est recommandé tous les 1 à 3 ans (HAS 2014)."),
    ("Quel rythme de dépistage du diabète si la GAJ est entre 1,10 et 1,25 g/l ?", "Un nouveau test doit être effectué un an plus tard pour confirmer la situation."),
    ("Depuis quand le dépistage du cancer du sein est-il organisé en France ?", "Depuis 2004, ciblant les femmes de 50 à 74 ans par mammographie tous les 2 ans."),
    ("Depuis quand le dépistage du cancer colorectal est-il organisé en France ?", "Depuis 2009, ciblant les hommes et femmes de 50 à 74 ans par test immunologique de recherche de sang dans les selles."),
    ("Quand le dépistage organisé du cancer du col de l\u2019utérus a-t-il été généralisé ?", "En 2018, après une expérimentation dans 13 départements de 2010 à 2014 ayant atteint 62 % de couverture."),
    ("Quelle est la population cible du dépistage du cancer du col de l\u2019utérus ?", "Toutes les femmes de 25 à 65 ans, soit environ 17 millions de femmes en France."),
    ("Quel est le rythme du dépistage du cancer du col de l\u2019utérus ?", "Les femmes n\u2019ayant pas réalisé de frottis dans les 3 dernières années sont invitées par courrier. Le frottis est pris en charge à 100 %."),
    ("Combien de cas annuels de cancer du col de l\u2019utérus en France ?", "Environ 3 000 nouveaux cas et plus de 1 100 décès par an."),
    ("Combien le dépistage du cancer du sein a-t-il coûté en 2008 ?", "216 millions d\u2019euros, mais il a permis une détection précoce et une réduction de la mortalité."),
    ("Qu\u2019est-ce que l\u2019expérimentation du dépistage du col a révélé ?", "323 cancers invasifs et 5 180 lésions précancéreuses détectés. 231 000 femmes dépistées sur invitation, 48 000 après relance."),
    ("Quelles conditions éthiques encadrent le dépistage ?", "Les avantages doivent l\u2019emporter sur les inconvénients, le niveau de preuve scientifique doit être élevé, et il y a une obligation de résultats."),
    ("Pourquoi l\u2019éthique est-elle particulièrement importante en dépistage ?", "Le dépistage concerne des personnes bien portantes qui n\u2019ont pas sollicité l\u2019intervention, d\u2019où l\u2019impératif de bénéfices clairs."),
    ("Qu\u2019est-ce que la prévention participative ?", "Une approche associant les populations concernées à la conception et mise en œuvre des actions de prévention pour une meilleure appropriation."),
    ("Quelle est la différence entre dépistage simple et dépistage complexe ?", "Le dépistage simple est peu coûteux et peu précis (population saine). Le complexe est coûteux et précis (population malade, confirmation diagnostique)."),
    ("Qu\u2019est-ce qu\u2019un vrai positif (VP) ?", "Un individu malade correctement identifié comme malade par le test de dépistage."),
    ("Qu\u2019est-ce qu\u2019un vrai négatif (VN) ?", "Un individu non malade correctement identifié comme non malade par le test de dépistage."),
    ("Comment interpréter une spécificité de 90 % ?", "90 % des non-malades sont correctement identifiés comme non malades par le test. 10 % sont des faux positifs."),
    ("Comment interpréter une VPP de 80 % ?", "Si le test est positif, il y a 80 % de chances que la personne soit effectivement malade."),
    ("Comment interpréter une VPN de 90 % ?", "Si le test est négatif, il y a 90 % de chances que la personne soit réellement non malade."),
    ("Que se passe-t-il si on abaisse le seuil d\u2019un test de dépistage ?", "La sensibilité augmente (moins de faux négatifs) mais la spécificité diminue (plus de faux positifs)."),
    ("Que se passe-t-il si on élève le seuil d\u2019un test de dépistage ?", "La spécificité augmente (moins de faux positifs) mais la sensibilité diminue (plus de faux négatifs)."),
    ("Qu\u2019est-ce que la couverture sociale en prévention tertiaire ?", "Assurer l\u2019accès aux soins médicaux nécessaires pour les maladies chroniques et garantir les droits aux soins indépendamment du statut socio-économique."),
    ("Qu\u2019est-ce que l\u2019articulation sanitaire-social en prévention tertiaire ?", "Le travail en réseau entre professionnels de santé et acteurs sociaux pour intégrer soins médicaux et soutien social (aide à domicile, réinsertion)."),
    ("Pourquoi un test sans intérêt se situe-t-il sur la diagonale de la courbe ROC ?", "La diagonale représente un test ne discriminant pas mieux que le hasard (AUC = 0,5), où sensibilité = 1 - spécificité."),
    ("Qu\u2019est-ce qu\u2019un test choquable au niveau d\u2019une AUC > 0,9 ?", "Un test ayant une AUC > 0,9 a une capacité de discrimination excellente, distinguant très bien les malades des non malades."),
    ("Quel impératif éthique majeur encadre le dépistage ?", "S\u2019assurer que pour la population cible, les avantages l\u2019emportent sur les inconvénients, avec un niveau de preuve scientifique élevé."),
    ("Qu\u2019est-ce que la prévention des traumatismes comme prévention primaire ?", "Les actions visant à éviter les accidents (sécurité routière, protection au travail, prévention des chutes chez les personnes âgées)."),
    ("Qu\u2019est-ce que le repérage précoce des comportements à risque ?", "Identifier les individus présentant des comportements risqués (tabagisme, alcoolisme) pour intervenir avant l\u2019apparition de pathologies graves."),
    ("Comment la prévention secondaire utilise-t-elle les campagnes de dépistage ?", "Par la sensibilisation et l\u2019incitation des populations à se faire dépister, permettant une détection précoce des maladies."),
    ("Qu\u2019est-ce que l\u2019accès précoce aux soins comme prévention secondaire ?", "La mise en place de dispositifs permettant un accès rapide aux soins médicaux pour traiter précocement certaines maladies."),
    ("Qu\u2019est-ce que le signalement d\u2019enfants maltraités comme prévention secondaire ?", "L\u2019identification et le signalement des cas de maltraitance infantile pour assurer une prise en charge rapide et éviter des séquelles graves."),
    ("Comment la prévention primaire agit-elle sur l\u2019environnement ?", "Par la protection de l\u2019environnement (réduction de la pollution), l\u2019amélioration de l\u2019habitat et le développement économique des territoires."),
    ("Qu\u2019est-ce que le plan cancer 2014-2019 en lien avec le dépistage ?", "Il a défini le dépistage du cancer du col de l\u2019utérus comme priorité de prévention et a conduit à la généralisation du programme en 2018."),
]

fc5 = [
    ("Qu\u2019est-ce que l\u2019hésitation vaccinale ?", "Le retard ou le refus de se faire vacciner malgré la disponibilité des vaccins. En 2019, l\u2019OMS l\u2019a classée parmi les dix principales menaces mondiales."),
    ("Quand l\u2019OMS a-t-elle classé l\u2019hésitation vaccinale comme menace mondiale ?", "En 2019, l\u2019OMS l\u2019a classée parmi les dix principales menaces pesant sur la santé mondiale, aux côtés du bioterrorisme."),
    ("Qu\u2019est-ce que la variolisation ?", "L\u2019inoculation volontaire de matériel provenant de lésions de variole pour induire une forme atténuée de la maladie, pratiquée avant la vaccination."),
    ("Qui a développé le premier vaccin et contre quelle maladie ?", "Edward Jenner a développé le vaccin contre la variole en 1796, en utilisant le virus de la vaccine (cowpox)."),
    ("Quand la variole a-t-elle été déclarée éradiquée ?", "En 1979, la variole a été déclarée éradiquée à l\u2019échelle mondiale grâce à la vaccination."),
    ("Qu\u2019est-ce qu\u2019un vaccin vivant atténué ?", "Un vaccin contenant un agent pathogène affaibli mais vivant, induisant une réponse immunitaire forte et durable. Ex : ROR, BCG, varicelle."),
    ("Qu\u2019est-ce qu\u2019un vaccin inactivé ?", "Un vaccin contenant un agent pathogène tué ou des fragments (sous-unités, toxoïdes), nécessitant souvent des rappels. Ex : grippe, hépatite B, tétanos."),
    ("Qu\u2019est-ce qu\u2019un vaccin conjugué ?", "Un vaccin où un polysaccharide bactérien est lié à une protéine porteuse pour améliorer l\u2019immunogénicité, surtout chez le nourrisson. Ex : Prevenar, Nimenrix."),
    ("Depuis quand 11 vaccins sont-ils obligatoires pour les nourrissons en France ?", "Depuis le 1er janvier 2018, portant les obligations de 3 (DTP) à 11 vaccins."),
    ("Quels sont les 11 vaccins obligatoires pour les nourrissons en France ?", "Diphtérie, tétanos, poliomyélite, coqueluche, Haemophilus influenzae b, hépatite B, pneumocoque, méningocoque C, rougeole, oreillons, rubéole."),
    ("Depuis 2025, quels nouveaux vaccins sont obligatoires pour les nourrissons ?", "Le vaccin méningocoque ACWY (au lieu de C seul) et le vaccin méningocoque B (Bexsero) sont devenus obligatoires depuis le 1er janvier 2025."),
    ("Qu\u2019est-ce que le pneumocoque ?", "Streptococcus pneumoniae, un diplocoque encapsulé à Gram positif avec 91 sérotypes, colonisant fréquemment le rhinopharynx."),
    ("Quelles maladies cause le pneumocoque ?", "Méningites, pneumonies, arthrites septiques, bactériémies, otites moyennes aiguës et sinusites."),
    ("Quel impact la vaccination anti-pneumococcique a-t-elle eu ?", "La mortalité infantile par méningite à pneumocoque est passée d\u2019environ 1 000 décès/an à environ 50 décès/an en France."),
    ("Qu\u2019est-ce que le Prevenar 13 ?", "Un vaccin pneumococcique conjugué 13-valences (Pfizer), obligatoire chez les enfants depuis 2018, schéma M2, M4, M11."),
    ("Qu\u2019est-ce que le Prevenar 20 ?", "Un vaccin pneumococcique conjugué 20-valences (Pfizer) réservé à l\u2019adulte, offrant une couverture élargie en dose unique."),
    ("Quel schéma vaccinal simplifié existe pour l\u2019adulte à risque contre le pneumocoque depuis 2024 ?", "Une seule injection de Prevenar 20 suffit, au lieu du schéma précédent VPC13 puis VPP23."),
    ("Qu\u2019est-ce que le vaccin ROR ?", "Un vaccin vivant atténué protégeant contre la rougeole, les oreillons et la rubéole, obligatoire depuis 2018."),
    ("Quel est le R0 de la rougeole ?", "Entre 15 et 20, ce qui en fait l\u2019une des maladies infectieuses les plus contagieuses au monde."),
    ("Quel schéma vaccinal pour le ROR ?", "1ère dose à 12 mois, 2e dose à 16-18 mois. La 2e dose n\u2019est pas un rappel mais assure une réponse immunitaire complète pour les 3 valences."),
    ("Pourquoi y a-t-il eu une épidémie de rougeole en France en 2011 ?", "En raison d\u2019une couverture vaccinale insuffisante (61 % à deux doses à 2 ans en 2010), avec plus de 15 000 cas."),
    ("Quelles complications la rougeole peut-elle entraîner ?", "Pneumopathies, encéphalites, voire décès. Les complications sont plus fréquentes avant 1 an et après 20 ans."),
    ("Pourquoi la rubéole est-elle dangereuse pendant la grossesse ?", "L\u2019infection dans les premières semaines peut provoquer de graves malformations fœtales ou une mort in utero. Le vaccin ROR est contre-indiqué pendant la grossesse."),
    ("Quelles complications les oreillons peuvent-ils entraîner chez l\u2019adulte ?", "Une orchite (inflammation testiculaire) pouvant affecter la fertilité, et des atteintes neurologiques rares mais graves."),
    ("Combien de sérotypes de méningocoques sont principalement pathogènes ?", "5 sérotypes : A, B, C, W135 et Y. En France, la répartition est équilibrée entre B, C et W135."),
    ("Pourquoi les méningites à méningocoque sont-elles des urgences absolues ?", "Risque de décès élevé en l\u2019absence de traitement dans les 24 premières heures, avec risque de purpura fulminans."),
    ("Qu\u2019est-ce que le purpura fulminans ?", "Une éruption cutanée hémorragique d\u2019évolution rapide, notamment sur les membres inférieurs, indiquant une atteinte vasculaire sévère dans les méningites à méningocoque."),
    ("Combien de cas d\u2019infections invasives à méningocoque sont recensés en France par an ?", "Environ 500 cas, avec deux pics : chez les nourrissons et chez les adolescents/jeunes adultes (15-24 ans)."),
    ("Quel schéma vaccinal pour le méningocoque ACWY depuis 2025 ?", "1ère dose à 6 mois, rappel à 12 mois (Nimenrix, Menveo ou MenQuadfi). Vaccination recommandée entre 11 et 14 ans avec rattrapage jusqu\u2019à 24 ans."),
    ("Quel est le schéma vaccinal du méningocoque B chez le nourrisson ?", "Bexsero : 3 doses à 3 mois, 5 mois et 12 mois, obligatoire depuis le 1er janvier 2025."),
    ("Qu\u2019est-ce que les papillomavirus humains (HPV) ?", "Des virus à transmission sexuelle, l\u2019IST la plus répandue au monde. Plus de 200 sérotypes dont une quinzaine à haut risque oncogène (16 et 18 surtout)."),
    ("Quel pourcentage des cancers du col de l\u2019utérus est dû aux HPV ?", "100 % des cancers du col de l\u2019utérus sont causés par les HPV oncogènes."),
    ("Quel pourcentage des cancers HPV-induits concerne les hommes ?", "Environ 25 % (cancers ORL, anaux, péniens)."),
    ("Qu\u2019est-ce que le Gardasil 9 ?", "Un vaccin nonavalent contre les HPV couvrant 90 % des sérotypes responsables de cancers et 90 % de ceux causant les condylomes génitaux."),
    ("Quel est le schéma vaccinal HPV entre 11 et 14 ans ?", "Deux doses espacées de 6 à 13 mois (J0 - M6/13)."),
    ("Quel est le schéma vaccinal HPV en rattrapage (après 14 ans) ?", "Trois doses selon le schéma J0 - M2 - M6, jusqu\u2019à 19 ans chez les filles et 26 ans chez les garçons."),
    ("Quand la vaccination HPV a-t-elle été étendue aux garçons en France ?", "Généralisée à tous les garçons à partir de 2022. Depuis 2025, accès pour tous les jeunes jusqu\u2019à 26 ans sans distinction."),
    ("Qu\u2019est-ce que la campagne de vaccination HPV dans les collèges ?", "Depuis 2023-24, des équipes mobiles vaccinent les élèves de 5e, augmentant la couverture de 23 à 25 points (environ 50-60 % actuellement)."),
    ("Quelle est l\u2019efficacité du vaccin HPV chez l\u2019homme ?", "90,4 % d\u2019efficacité contre les lésions liées aux HPV 6-11-16-18 et 85,6 % sur les infections persistantes (essai randomisé, 4065 hommes)."),
    ("Quel pays est pionnier dans la vaccination HPV ?", "L\u2019Australie, avec début en 2007 chez les filles et 2013 chez les garçons, atteignant 80 % de couverture chez les filles et 76 % chez les garçons."),
    ("Qu\u2019est-ce que le BCG ?", "Le vaccin contre la tuberculose, mis au point en 1921 (bacille de Calmette et Guérin), vaccin vivant atténué. Efficacité modeste chez l\u2019adulte, bonne chez le nourrisson."),
    ("Depuis quand le BCG n\u2019est-il plus obligatoire en France ?", "Depuis 2007. Il reste recommandé pour les enfants à risque (pays endémique, Île-de-France, Guyane, Mayotte)."),
    ("Quelle est l\u2019efficacité du BCG chez l\u2019enfant de moins de 5 ans ?", "75 à 86 % d\u2019efficacité contre les formes graves (disséminées et neuroméningées) de la tuberculose."),
    ("Combien de cas et de décès la grippe saisonnière cause-t-elle en France par an ?", "2 à 6 millions de cas et 8 000 à 21 000 décès, dont 90 % chez les plus de 65 ans."),
    ("Qu\u2019est-ce que l\u2019immunosénescence ?", "La diminution de la réponse immunitaire liée à l\u2019âge, limitant l\u2019efficacité des vaccins standards chez les personnes âgées."),
    ("Pourquoi des vaccins grippaux haute dose ont-ils été développés ?", "Pour compenser l\u2019immunosénescence chez les personnes âgées dont la réponse immunitaire aux vaccins standards est diminuée."),
    ("Depuis quand la vaccination grippe est-elle recommandée pour les enfants de 2 à 17 ans ?", "Depuis 2023, la HAS recommande la vaccination annuelle de tous les enfants de 2 à 17 ans en raison de leur rôle dans la transmission."),
    ("Qu\u2019est-ce que le vaccin contre le zona SHINGRIX ?", "Un vaccin recommandé à partir de 65 ans (ou dès 18 ans si immunodépression), 2 doses espacées de 2 mois, remplaçant le ZOSTAVAX."),
    ("Pour qui la vaccination contre la varicelle est-elle recommandée ?", "Adolescents de 12-18 ans sans antécédent, femmes en âge de procréer sans antécédent, personnes en contact avec immunodéprimés, cas contacts dans les 3 jours."),
    ("Qu\u2019est-ce que la Mpox ?", "Une infection causée par un Orthopoxvirus (96 % d\u2019homologie avec la variole), avec une épidémie en 2022 (5 000 cas en France, 86 000 dans le monde)."),
    ("Quels vaccins ont été utilisés contre la Mpox en 2022 ?", "Des vaccins antivarioliques de 3e génération (Imvanex/Jynneos) mobilisés à partir des stocks stratégiques de l\u2019État."),
    ("Qu\u2019est-ce que l\u2019affaire du Mediator en lien avec la défiance vaccinale ?", "Le scandale du Mediator et d\u2019autres crises sanitaires ont alimenté la défiance envers les institutions médicales, amplifiant l\u2019hésitation vaccinale en France."),
    ("Qu\u2019est-ce que la controverse sur le vaccin hépatite B en France ?", "Dans les années 1990, une suspicion de lien avec la sclérose en plaques a été soulevée, entraînant une suspension de la vaccination scolaire, bien que le lien n\u2019ait jamais été prouvé."),
    ("Qu\u2019est-ce que l\u2019adjuvant aluminique et pourquoi est-il controversé ?", "Un composant des vaccins améliorant la réponse immunitaire. Controversé en raison de craintes sur la myofasciite à macrophages, bien que les données scientifiques ne confirment pas de danger."),
    ("Quelle est la couverture vaccinale actuelle du ROR à deux doses en France ?", "Environ 83 %, permettant une forte réduction de l\u2019incidence : 16 cas en 2021 (mesures barrières COVID) et 117 cas en 2023."),
    ("Pour qui la vaccination méningocoque est-elle obligatoire pour le pèlerinage à la Mecque ?", "La vaccination ACWY est obligatoire pour les pèlerins se rendant à la Mecque."),
    ("Qu\u2019est-ce que la ceinture de la méningite en Afrique ?", "Une zone d\u2019Afrique subsaharienne (du Sénégal à l\u2019Éthiopie) où les épidémies de méningite à méningocoque sont fréquentes."),
    ("Quelle est la différence entre un vaccin conjugué et un vaccin non conjugué ?", "Le conjugué lie un polysaccharide à une protéine porteuse, induisant une réponse mémoire T-dépendante durable. Le non conjugué (ex : Pneumovax 23) est moins immunogène et sans mémoire."),
    ("Qu\u2019est-ce que le Pneumovax 23 ?", "Un vaccin non conjugué 23-valences contre le pneumocoque, moins immunogène chez les moins de 2 ans, sans mémoire immunitaire, protection de 3-5 ans."),
    ("Qu\u2019est-ce que la vaccination en anneau ?", "Une stratégie de vaccination ciblée en urgence autour d\u2019un cas index pour limiter la propagation, utilisée notamment pour le méningocoque."),
    ("Quelles surinfections bactériennes sont fréquentes après la grippe ?", "Les surinfections à pneumocoque et à staphylocoque doré sont les plus fréquentes après la grippe."),
    ("Pourquoi dit-on que si un patient doit être vacciné contre la grippe, il doit l\u2019être aussi contre le pneumocoque ?", "Les patients fragiles (personnes âgées, malades chroniques) sont à risque pour les deux infections, et la grippe favorise les surinfections à pneumocoque."),
    ("Quels sont les noms commerciaux du vaccin ROR ?", "Priorix (GSK) et M-M-RVAXPRO (MSD)."),
    ("Qui doit avoir reçu 2 doses de ROR ?", "Toutes les personnes nées après 1980, quel que soit leur statut vaccinal antérieur."),
    ("Qu\u2019est-ce que le R0 et comment influence-t-il la couverture vaccinale nécessaire ?", "Le R0 est le nombre de reproductions de base. Plus il est élevé, plus la couverture vaccinale nécessaire pour l\u2019immunité collective est élevée (formule : 1 - 1/R0)."),
    ("Combien de cas de rougeole y a-t-il eu en France en 2021 et 2023 ?", "16 cas en 2021 (probablement liés aux mesures barrières COVID) et 117 cas en 2023."),
    ("Qu\u2019est-ce que le calendrier vaccinal ?", "Le document officiel publié chaque année définissant les vaccinations recommandées et obligatoires en France selon l\u2019âge et les situations à risque."),
]

fc6 = [
    ("Qu\u2019est-ce qu\u2019une IST ?", "Une infection sexuellement transmissible, transmise principalement lors de rapports sexuels (vaginaux, anaux, oraux) par des agents bactériens, viraux ou parasitaires."),
    ("Quelle est l\u2019IST bactérienne la plus fréquente au monde ?", "Chlamydia trachomatis, environ 50 fois plus fréquente que le gonocoque."),
    ("Qu\u2019est-ce que le VIH ?", "Le virus de l\u2019immunodéficience humaine, un rétrovirus qui infecte les lymphocytes T CD4 et provoque le SIDA en l\u2019absence de traitement."),
    ("Quelle est la cellule cible principale du VIH ?", "Le lymphocyte T CD4, cellule clé du système immunitaire adaptatif."),
    ("Qu\u2019est-ce que la charge virale du VIH ?", "La quantité de virus VIH dans le sang, mesurée en copies/mL. L\u2019objectif du traitement est de la rendre indétectable."),
    ("Qu\u2019est-ce que le principe U = U (Indétectable = Intransmissible) ?", "Un patient VIH sous traitement efficace avec une charge virale indétectable ne transmet pas le virus par voie sexuelle."),
    ("Quel est le traitement standard du VIH ?", "La trithérapie : 2 inhibiteurs nucléosidiques de la transcriptase inverse (INTI) + un 3e agent (inhibiteur d\u2019intégrase, INNTI ou inhibiteur de protéase)."),
    ("Quels sont les objectifs du traitement antirétroviral ?", "Suppression de la réplication virale, maintien des CD4 > 500/mm\u00b3, limitation de l\u2019activation immunitaire, diminution de l\u2019inflammation et arrêt de la transmission."),
    ("En combien de temps la charge virale doit-elle devenir indétectable sous traitement ?", "À 1 mois : baisse de 2 log. À 3 mois : < 400 copies/mL. À 6 mois : charge virale indétectable."),
    ("Qu\u2019est-ce que la PrEP ?", "La prophylaxie pré-exposition : prise d\u2019antirétroviraux par des personnes séronégatives à haut risque pour prévenir l\u2019infection par le VIH."),
    ("Qu\u2019est-ce que le TPE (traitement post-exposition) ?", "Un traitement antirétroviral d\u2019urgence à prendre dans les 48h après une exposition au VIH (rapport à risque, AES) pendant 28 jours."),
    ("Qu\u2019est-ce que la syphilis ?", "Une IST bactérienne causée par Treponema pallidum, hautement contagieuse et non immunisante (réinfection possible malgré les anticorps)."),
    ("Quelles sont les phases de la syphilis ?", "Phase précoce : primaire, secondaire, latente précoce. Phase tardive : tertiaire, latente tardive. La neurosyphilis peut survenir à tout stade."),
    ("Qu\u2019est-ce que le chancre syphilitique ?", "L\u2019ulcération muqueuse de la syphilis primaire : constante, superficielle, indolore, bien circonscrite, surface lisse et rosée, souvent unique, cicatrisant en 3-5 semaines."),
    ("Pourquoi la syphilis primaire est-elle souvent méconnue ?", "Environ la moitié des personnes ne remarquent pas le chancre, qui est indolore et peut avoir une localisation extragénitale."),
    ("Pourquoi la syphilis secondaire est-elle surnommée « la grande simulatrice » ?", "Car ses manifestations cutanées polymorphes peuvent imiter de nombreuses pathologies dermatologiques (toxidermie, lichen, eczéma, psoriasis)."),
    ("Qu\u2019est-ce que la roséole syphilitique ?", "La première floraison de la syphilis secondaire : macules rose pâle, non prurigineuses, < 1 cm, sur le tronc, avec intervalles de peau saine."),
    ("Qu\u2019est-ce que le collier de Vénus ?", "Des cicatrices pigmentées à la base du cou, séquelle de la roséole syphilitique."),
    ("Qu\u2019est-ce que les syphilides ?", "La deuxième floraison : papules cuivrées, à base indurée, 3-5 mm, parfois squameuses, pouvant siéger sur les paumes et les plantes."),
    ("Qu\u2019est-ce que la syphilis tertiaire ?", "Une forme tardive (jusqu\u2019à 30 ans après l\u2019infection) chez les non traités : gommes cutanéo-muqueuses, atteinte osseuse, hépatique, cardiovasculaire (aortite) et neurologique."),
    ("Qu\u2019est-ce que la neurosyphilis ?", "Une atteinte neurologique pouvant survenir à tout stade : méningite, atteinte des paires crâniennes, syphilis vasculaire cérébrale (AVC), tabes dorsalis."),
    ("Qu\u2019est-ce que la syphilis congénitale ?", "La transmission au fœtus après 16-20 SA, pouvant entraîner mort fœtale, fausse couche ou infection latente avec manifestations tardives."),
    ("Quels sont les deux types de tests sérologiques pour la syphilis ?", "Tests tréponémiques (TPHA, FTA : spécifiques mais restent positifs à vie) et tests non tréponémiques (VDRL, RPR : sujets aux faux positifs mais se négativent après guérison)."),
    ("Quel est le traitement de la syphilis précoce ?", "Une injection unique de pénicilline G intramusculaire. Alternative orale de 14 jours en cas d\u2019allergie."),
    ("Quel est le traitement de la syphilis tardive ?", "Trois injections de pénicilline G espacées d\u2019une semaine, ou alternative orale prolongée."),
    ("Qu\u2019est-ce que la réaction de Jarisch-Herxheimer ?", "Une réaction immunoallergique à l\u2019injection d\u2019antibiotiques contre la syphilis : fièvre, exacerbation de l\u2019éruption, adénopathies. Bénigne, traitée par paracétamol."),
    ("Comment surveille-t-on le traitement de la syphilis ?", "Par décroissance du VDRL : contrôle à M3, M6, M12, M24. VDRL divisé par 4 à M6. Négativation à M12 (primaire) ou M24 (secondaire)."),
    ("Qu\u2019est-ce que Chlamydia trachomatis ?", "Un bacille Gram négatif intracellulaire obligatoire, responsable de l\u2019IST bactérienne la plus fréquente. Souvent asymptomatique, surtout chez la femme."),
    ("Quels sont les biovars de Chlamydia trachomatis ?", "Sérotypes A-C (trachome), sérotypes D-K (infections urogénitales), sérotypes L1-L3 (lymphogranulomatose vénérienne/LGV)."),
    ("Pourquoi le dépistage systématique du Chlamydia est-il recommandé chez les femmes < 25 ans ?", "Car l\u2019infection est très souvent asymptomatique et peut entraîner des complications graves : salpingites, endométrites, stérilité tubaire."),
    ("Qu\u2019est-ce que le syndrome de Fitz-Hugh-Curtis ?", "Une périhépatite en « cordes de violon » compliquant une infection à Chlamydia trachomatis, diagnostiquée par cœlioscopie."),
    ("Qu\u2019est-ce que l\u2019arthrite réactionnelle liée au Chlamydia ?", "Une atteinte articulaire stérile d\u2019origine immunitaire, surtout chez les patients HLA-B27+. Peut s\u2019inscrire dans le syndrome oculo-urétro-synovial (Fiessinger-Leroy-Reiter)."),
    ("Comment diagnostique-t-on une infection à Chlamydia ?", "Exclusivement par PCR (biologie moléculaire). La sérologie est inutile en pratique clinique. Premier jet urinaire chez l\u2019homme, autoprélèvement vaginal chez la femme."),
    ("Qu\u2019est-ce que la lymphogranulomatose vénérienne (LGV) ?", "Une infection à Chlamydia sérotypes L1-L3, touchant 98 % des HSH, avec chancre transitoire puis adénite inguinale et rectites. Traitement prolongé (2 x 3 semaines)."),
    ("Qu\u2019est-ce que Neisseria gonorrhoeae ?", "Le gonocoque, une bactérie Gram négatif diplococcique causant une IST souvent très symptomatique chez l\u2019homme (urétrite purulente, « chaude-pisse »)."),
    ("Quelles sont les manifestations du gonocoque chez l\u2019homme ?", "Urétrite gonococcique avec écoulement purulent et brûlures mictionnelles intenses, prostatite, orchiépididymite."),
    ("Quelles sont les manifestations du gonocoque chez la femme ?", "Cervicite, urétrite, salpingite, infections anorectales et pharyngées."),
    ("Quelles sont les formes disséminées du gonocoque ?", "Arthralgies/arthrites et lésions cutanées caractéristiques (pustules à halo érythémateux aux extrémités), reflet d\u2019une bactériémie."),
    ("Quel est le traitement de première intention du gonocoque ?", "Une injection intramusculaire unique de ceftriaxone (C3G). Utilisable pendant la grossesse."),
    ("Pourquoi faut-il un antibiogramme avant de traiter le gonocoque ?", "En raison de l\u2019émergence de souches résistantes : 50 % aux fluoroquinolones, 50-60 % aux tétracyclines, 5-15 % à l\u2019azithromycine."),
    ("Qu\u2019est-ce que la Mpox (monkeypox) ?", "Une infection à Orthopoxvirus avec phase prodromique (fièvre, ADP, myalgies) puis éruption papulo-vésiculeuse-pustuleuse, guérissant en 2-4 semaines."),
    ("Comment se transmet la Mpox ?", "Par lésions cutanéo-muqueuses, sécrétions respiratoires et contacts étroits. L\u2019épidémie 2022 touchait surtout les HSH multipartenaires."),
    ("Combien de cas de Mpox ont été recensés en France en 2022 ?", "Près de 5 000 cas, plus de la moitié en Île-de-France, 88 % confirmés par PCR, aucun décès."),
    ("Quels diagnostics différentiels évoquer devant une Mpox ?", "Varicelle (prurit, cuir chevelu, plusieurs poussées), coxsackie (PMB), syphilis secondaire, herpès, dermatose bulleuse."),
    ("Quelles sont les formes graves de Mpox ?", "Éruptions massives (> 100 lésions), lésions muqueuses hyperalgiques, pneumopathie, sepsis, myocardite, méningo-encéphalite."),
    ("Qu\u2019est-ce que la prévention combinée des IST ?", "L\u2019association de préservatif, dépistage régulier, PrEP, TPE, vaccination HPV et traitement comme prévention (TasP) pour réduire le risque de transmission."),
    ("Qu\u2019est-ce que le TasP (Treatment as Prevention) ?", "Le traitement antirétroviral du VIH comme outil de prévention : un patient indétectable ne transmet pas le virus (U = U)."),
    ("Pourquoi diversifier les sites de prélèvement pour le dépistage IST ?", "Les IST peuvent toucher le pharynx, le rectum et les sites génitaux selon les pratiques sexuelles. Il faut adapter le prélèvement."),
    ("Quels prélèvements réaliser pour le dépistage Chlamydia/gonocoque ?", "PCR 1er jet urinaire, autoprélèvement vaginal, autoprélèvement anal, PCR pharyngée. Pas de sérologie."),
    ("Qu\u2019est-ce que la sérologie syphilitique obligatoire pendant la grossesse ?", "Un dépistage systématique de la syphilis chez toute femme enceinte pour prévenir la syphilis congénitale et ses complications graves."),
    ("Pourquoi faut-il aussi dépister le futur père pour la syphilis ?", "Pour éviter toute recontamination de la mère pendant la grossesse, qui pourrait provoquer une syphilis congénitale."),
    ("Qu\u2019est-ce que le contrôle PCR post-traitement pour le Chlamydia ?", "Une PCR de contrôle à M3 pour vérifier l\u2019absence de réinfection, ou à M1 en cas de grossesse."),
    ("Quels sont les rapports protégés recommandés après traitement d\u2019une IST ?", "Rapports protégés (ou abstinence) jusqu\u2019à 7 jours après la fin du traitement et disparition complète des symptômes."),
    ("Quelle est la particularité des macrolides dans le traitement de la syphilis ?", "L\u2019azithromycine ne doit pas être utilisée car 86 % des souches en France présentent des mutations de résistance (gène A2058G/A2059G)."),
    ("Qu\u2019est-ce que l\u2019ophtalmie néonatale à gonocoque ?", "Une infection oculaire grave du nouveau-né transmise lors de l\u2019accouchement, pouvant évoluer vers la cécité sans traitement rapide."),
    ("Quelles complications le Chlamydia peut-il entraîner chez le nouveau-né ?", "Conjonctivites néonatales et pneumopathies alvéolo-interstitielles à début retardé (2-16 semaines)."),
    ("Pourquoi les IST sont-elles souvent co-infectantes ?", "La présence d\u2019une IST (ulcération, inflammation muqueuse) facilite la transmission d\u2019autres agents, notamment le VIH."),
    ("Qu\u2019est-ce que la DO (déclaration obligatoire) pour la Mpox ?", "L\u2019obligation de déclarer les cas de Mpox aux autorités sanitaires pour assurer la surveillance épidémiologique."),
    ("Qu\u2019est-ce que la prophylaxie Bactrim chez le patient VIH ?", "Un traitement préventif contre la pneumocystose et la toxoplasmose prescrit lorsque les CD4 < 200/mm\u00b3 (15 %)."),
    ("En combien de temps faut-il initier le traitement VIH après la découverte ?", "Le plus rapidement possible, en moins de 7 jours. Seules la cryptococcose et la tuberculose neuroméningées justifient un retard."),
    ("Qu\u2019est-ce que le titre VDRL et les dilutions ?", "Le VDRL est testé sur sérum pur puis en dilutions par pas de 2. Le titre correspond au dernier palier positif. Ex : VDRL 1/64 > VDRL 1/4 en gravité."),
    ("Comment interprète-t-on une réascension du VDRL (x4) ?", "C\u2019est un signe d\u2019échec de traitement ou de réinfection nécessitant un nouveau traitement."),
    ("Les tests tréponémiques se négativent-ils après guérison ?", "En général non, ils restent positifs à vie, bien que certaines personnes puissent séronégativer."),
    ("Chez la femme, quel est le prélèvement de référence pour Chlamydia ?", "L\u2019autoprélèvement vaginal, qui donne de meilleurs résultats que le premier jet urinaire."),
    ("Chez l\u2019homme, quel est le prélèvement de référence pour Chlamydia ?", "Le premier jet urinaire, de préférence les premières urines du matin."),
]

# Read current file
with open(TARGET, 'r') as f:
    content = f.read()

# Remove trailing } and whitespace
content = content.rstrip()
if content.endswith('}'):
    content = content[:-1]

def format_tuples(key, tuples):
    lines = [f'"SP_Promotion_Prevention/{key}": [']
    for q, a in tuples:
        lines.append(f'    ("{q}", "{a}"),')
    lines.append('],')
    return '\n'.join(lines)

content += format_tuples("fc4.html", fc4) + '\n'
content += format_tuples("fc5.html", fc5) + '\n'
content += format_tuples("fc6.html", fc6) + '\n'
content += '}\n'

with open(TARGET, 'w') as f:
    f.write(content)

# Verify
import re
for key in ['fc1', 'fc2', 'fc3', 'fc4', 'fc5', 'fc6']:
    pattern = f'{key}.html'
    idx = content.find(pattern)
    bracket_start = content.find('[', idx)
    depth = 0
    for i in range(bracket_start, len(content)):
        if content[i] == '[': depth += 1
        elif content[i] == ']': depth -= 1
        if depth == 0:
            bracket_end = i
            break
    section = content[bracket_start:bracket_end+1]
    tuples = re.findall(r'\("', section)
    print(f'{key}: {len(tuples)} flashcards')
