"""Flashcard data for SP Géographie de la santé courses 1-10 (~100 flashcards each)."""

FLASHCARDS = {
"SP_Geographie_Sante/fc1.html": [
    ("Quelle est la définition de la géographie ?", "La géographie est une science qui étudie les rapports entre les sociétés humaines et leurs espaces."),
    ("Quelles sont les deux grandes branches de la géographie ?", "La géographie humaine (ou sociale) et la géographie physique (environnementale)."),
    ("Quelles sont les trois questions principales communes à toutes les branches de la géographie ?", "« Où ? », « Pourquoi ici et pas ailleurs ? » et « Pourquoi ici différemment d\u2019ailleurs ? »."),
    ("À partir de quand la géographie de la santé s\u2019est-elle structurée comme discipline en France ?", "À partir des années 1970-1980."),
    ("Qui est considéré comme l\u2019un des premiers à avoir théorisé le lien entre espace et santé dans l\u2019Antiquité ?", "Hippocrate, médecin et philosophe grec."),
    ("À quelle époque vivait Hippocrate ?", "Au IVe et Ve siècle avant J.-C."),
    ("Quel est le titre du traité fondateur d\u2019Hippocrate sur les liens entre environnement et santé ?", "Le traité « Des Airs, des Eaux et des Lieux »."),
    ("Qu\u2019est-ce que le déterminisme hippocratique ?", "C\u2019est l\u2019idée selon laquelle les conditions environnementales (air, eau, climat) influencent directement l\u2019état de santé des populations."),
    ("Quel est l\u2019apport majeur d\u2019Hippocrate à la médecine ?", "Il a posé les bases d\u2019une séparation entre médecine et religion, en insistant sur l\u2019étude des facteurs multiples déterminant la santé."),
    ("Que signifie « Ayurvéda » ?", "« Science de la vie » en sanskrit."),
    ("À quelle période l\u2019Ayurvéda s\u2019est-il développé ?", "Au Ier et IIe millénaire avant J.-C."),
    ("Sur quoi repose l\u2019approche de l\u2019Ayurvéda ?", "Sur une vision holistique englobant la santé physique, mentale, les relations sociales et l\u2019équilibre spirituel, avec une forte dimension préventive."),
    ("L\u2019Ayurvéda est-il reconnu par une institution internationale ?", "Oui, l\u2019OMS le reconnaît comme un système de santé traditionnel."),
    ("Qui était Avicenne (Ibn Sina) ?", "Un médecin et philosophe perse né en 980, dont l\u2019œuvre a profondément influencé des générations de médecins."),
    ("Comment s\u2019appelle l\u2019encyclopédie médicale d\u2019Avicenne ?", "Al-Qanûn (Le Canon), premier manuel médical de référence."),
    ("Quelles traditions médicales Al-Qanûn synthétise-t-il ?", "Les traditions gréco-romaines, arabes et indiennes."),
    ("Jusqu\u2019à quand Al-Qanûn est-il resté une référence en médecine ?", "Jusqu\u2019à la Renaissance."),
    ("Quelles sont les trois grandes pandémies de peste documentées ?", "La Peste Justinienne (VIe-VIIIe siècles), la Peste Noire (XIVe siècle) et la Peste du XIXe siècle."),
    ("Combien de morts la Peste Justinienne a-t-elle causé ?", "Entre 25 et 50 millions de personnes."),
    ("Par où la Peste Noire s\u2019est-elle propagée vers l\u2019Europe ?", "Par les routes commerciales, notamment la Route de la Soie et les itinéraires maritimes."),
    ("Combien de morts la Peste Noire a-t-elle causé en Europe ?", "Environ 25 millions, soit près d\u2019un tiers de la population."),
    ("Quel est l\u2019agent pathogène de la peste ?", "Yersinia pestis, identifié en 1894 par Alexandre Yersin."),
    ("Qui a identifié les puces comme vecteurs de la peste et en quelle année ?", "Paul-Louis Simond en 1898."),
    ("Quelles sont les deux formes principales de la peste ?", "La peste bubonique (ganglions enflés, transmission par puces) et la peste pulmonaire (transmission aérienne entre humains)."),
    ("Qu\u2019est-ce que la théorie des miasmes ?", "La croyance selon laquelle certaines maladies étaient dues à la mauvaise qualité de l\u2019air (« mauvais air »)."),
    ("Quelle ville a créé le premier Conseil Sanitaire et en quelle année ?", "Venise en 1348."),
    ("Pourquoi Venise était-elle un point stratégique face aux épidémies ?", "C\u2019était une plaque tournante du commerce entre l\u2019Orient et l\u2019Occident, concentrant de nombreux échanges."),
    ("Quelles mesures Venise a-t-elle mises en place en 1348 ?", "L\u2019isolement des malades, le contrôle des voyageurs et l\u2019utilisation de l\u2019île de Santa Maria di Nazareth pour l\u2019isolement."),
    ("Quelle ville a mis en place la désinfection des marchandises au Moyen Âge ?", "Milan."),
    ("Qu\u2019est-ce que la Société royale de médecine a commandé au XVIIIe siècle ?", "Des enquêtes sanitaires sous forme de topographies médicales décrivant les conditions environnementales et de vie des habitants."),
    ("Qu\u2019est-ce qu\u2019une topographie médicale ?", "Une description chiffrée et illustrée d\u2019un lieu sous un angle médical, tenant compte de facteurs environnementaux et des conditions de vie."),
    ("Comment la Révolution industrielle au XIXe siècle a-t-elle transformé les conditions sanitaires ?", "Par l\u2019urbanisation rapide, la hausse de la densité de population dans des logements insalubres et de nouvelles dynamiques de transmission des maladies."),
    ("Qui est John Snow et quel est son apport ?", "Il est l\u2019un des premiers à utiliser la cartographie comme outil d\u2019analyse épidémiologique, localisant les cas de choléra à Londres."),
    ("Comment John Snow a-t-il réfuté la théorie des miasmes ?", "En démontrant que la transmission du choléra était liée à l\u2019eau contaminée, pas à la qualité de l\u2019air."),
    ("Quelle pompe John Snow a-t-il identifiée comme source de contamination ?", "La pompe de Broad Street."),
    ("Quels concepts John Snow a-t-il mobilisés dans son analyse ?", "Les concepts d\u2019espace et de distance en géographie."),
    ("Qu\u2019ont révélé les travaux de Louis-René Villermé en 1840 ?", "Une corrélation entre classe sociale, conditions de logement et espérance de vie, influençant l\u2019adoption de lois sociales comme la limitation du travail des enfants."),
    ("Quelle est la différence entre les travaux de Villermé et ceux de Chadwick ?", "Villermé remet en cause le système de classes sociales, tandis que Chadwick analyse les conditions sanitaires sans remettre en question le système économique."),
    ("Qu\u2019a apporté la théorie microbienne de Louis Pasteur ?", "Le remplacement de la théorie des miasmes par la découverte des bactéries pathogènes, une conception monoétiologique des maladies et le développement des vaccins."),
    ("Comment les villes ont-elles été transformées suite aux découvertes de Pasteur ?", "Par la réorganisation des espaces urbains (élargissement des rues), l\u2019amélioration des infrastructures (eau potable, égouts) et la limitation de la densité humaine."),
    ("Qui a dirigé les grands travaux d\u2019urbanisme à Paris au XIXe siècle ?", "Le Baron Haussmann."),
    ("Qu\u2019est-ce que le « complexe pathogène » de Maximilien Sorre ?", "Une association parasitaire d\u2019êtres vivants dans laquelle l\u2019homme est la victime, avec des conditions de transmission dépendant du milieu naturel et des modifications anthropiques."),
    ("En quelle année Sorre a-t-il introduit le concept de complexe pathogène ?", "En 1933."),
    ("Sur quel exemple Sorre s\u2019appuie-t-il pour illustrer le complexe pathogène ?", "Le paludisme, dont la transmission repose sur l\u2019interaction entre l\u2019environnement, le moustique Anopheles et l\u2019homme."),
    ("Que sont les modifications anthropiques selon Sorre ?", "Les transformations du milieu naturel dues aux activités humaines (urbanisation, déforestation, aménagements hydrauliques, etc.)."),
    ("Qui a introduit la notion de « désert médical » ?", "Henri Picheral."),
    ("Que recouvre la géographie des soins développée à partir des années 1970 ?", "L\u2019hypothèse que la prévalence des maladies peut s\u2019expliquer par un déficit ou une inadaptation de l\u2019offre de soins."),
    ("Quelle est la définition de la santé selon l\u2019OMS (1946) ?", "« Un état de complet bien-être physique, mental et social, et ne consiste pas seulement en une absence de maladie ou d\u2019infirmité. »"),
    ("En quelle année la Charte d\u2019Ottawa a-t-elle été adoptée ?", "En 1986."),
    ("Qu\u2019est-ce que le concept de One Health ?", "Une approche qui met en évidence les liens entre la santé humaine, la santé animale et la santé des écosystèmes."),
    ("Qu\u2019est-ce que le franchissement de la barrière d\u2019espèce ?", "Le phénomène par lequel un pathogène passe d\u2019une espèce animale à l\u2019homme, favorisé par les perturbations environnementales."),
    ("Quelle est la définition de la géographie des maladies ?", "L\u2019étude de la distribution sociale et spatiale des maladies."),
    ("Quelle est la définition de la géographie des soins ?", "L\u2019analyse sociale et spatiale des ressources sanitaires (offre de soins), du recours aux soins et du niveau de médicalisation."),
    ("Quelle est la définition de la géographie de la santé ?", "L\u2019analyse sociale et spatiale de l\u2019offre de soins, du recours aux soins, des inégalités de santé et des déterminants de santé, en référence à la définition holistique de l\u2019OMS."),
    ("Quels chercheurs continuent les travaux de Sorre sur les maladies infectieuses ?", "Jean-Pierre Hervouët, Pascal Handschumacher et Antoine Pascal à l\u2019université de Strasbourg."),
    ("Quels sont les principaux déterminants de la santé mentionnés dans la Charte d\u2019Ottawa ?", "Le mode de vie, les conditions de travail, l\u2019accès à l\u2019eau et à une alimentation de qualité, le logement, l\u2019environnement urbain et l\u2019accessibilité des soins."),
    ("Comment Avicenne a-t-il contribué à la médecine préventive ?", "En mettant en évidence l\u2019importance de l\u2019hygiène, des conditions de vie et des facteurs environnementaux, notamment le lavage des mains."),
    ("Qu\u2019est-ce que l\u2019analyse multi-échelles en géographie de la santé ?", "C\u2019est la capacité de zoomer et dézoomer pour analyser les phénomènes de santé à différentes échelles (locale, régionale, nationale)."),
    ("Quels sont les deux grands thèmes du semestre en géographie de la santé ?", "L\u2019offre et l\u2019accès aux soins, et l\u2019environnement urbain et la santé."),
    ("Quelle différence y a-t-il entre système de soins et système de santé ?", "Le système de santé est plus englobant : il comprend le système de soins mais aussi les facteurs et acteurs hors sphère sanitaire (éducation, social, aménagement) qui participent à la santé."),
    ("Quelles mesures de protection individuelles étaient prises contre la peste selon la théorie des miasmes ?", "Fuir vers des régions à air plus pur, s\u2019enfermer chez soi, respirer du parfum, faire des fumigations et des feux purificateurs."),
    ("Pourquoi certaines vallées pyrénéennes ou alpines ont-elles été épargnées par la Peste Noire ?", "Leur faible connexion aux réseaux commerciaux a limité l\u2019introduction du pathogène."),
    ("Comment les pandémies de peste ont-elles contribué à l\u2019émergence de la santé publique ?", "Par la mise en place de mesures de prévention et d\u2019isolement des malades, posant les bases des futures politiques sanitaires."),
    ("En quoi l\u2019approche géographique permet-elle de comprendre les inégalités de santé ?", "En cartographiant les inégalités et en analysant les effets de lieu, montrant que les inégalités sont à la fois sociales et spatiales."),
    ("Quels sont les concepts clés abordés en géographie de la santé ?", "L\u2019espace, la distance, le territoire, l\u2019accès et l\u2019accessibilité, les inégalités et les fractures territoriales."),
    ("Pourquoi est-il important de ne pas adopter une vision eurocentrée de l\u2019histoire de la médecine ?", "Parce que d\u2019autres traditions médicales anciennes (Inde, Chine, Moyen-Orient) ont également joué un rôle majeur dans l\u2019histoire des sciences de la santé."),
    ("Comment les épidémies ont-elles influencé les politiques économiques et sociales ?", "Par l\u2019effondrement démographique, la désorganisation économique, les crises sociales et religieuses et l\u2019évolution des politiques sanitaires."),
    ("Quel rôle joue la géographie politique dans la géographie de la santé ?", "Elle permet d\u2019étudier l\u2019impact des décisions gouvernementales sur la gestion des maladies, la prévention et l\u2019aménagement du territoire."),
    ("Qu\u2019est-ce qui distingue la géographie de la santé des autres sciences sociales ?", "L\u2019étude de l\u2019espace, de la distance, du territoire et la pratique de l\u2019analyse multi-échelles."),
    ("Comment la géographie physique contribue-t-elle à la géographie de la santé ?", "Par l\u2019étude des moustiques vecteurs, la localisation des eaux, et la compréhension des interactions entre humains et non-humains dans la transmission des maladies."),
    ("Quel Master est proposé en lien avec la géographie de la santé ?", "Le Master Territoire, Ville et Santé, partagé entre les universités de Créteil et de Nanterre."),
    ("En quoi les travaux de Villermé ont-ils eu un impact politique ?", "Ses études sur la corrélation entre classe sociale et espérance de vie ont influencé l\u2019adoption de lois sociales, comme la limitation du travail des enfants."),
    ("Comment les réformes haussmanniennes ont-elles renforcé les inégalités urbaines ?", "En repoussant les classes populaires vers des zones plus éloignées lors de la transformation des quartiers."),
    ("En quelle année la Constitution de l\u2019OMS définissant la santé a-t-elle été signée ?", "En 1946, signée par 61 États."),
    ("Qu\u2019est-ce que la capacité d\u2019agir sur sa propre santé ?", "Un concept développé dans les travaux sur la promotion de la santé, issu de l\u2019approche holistique de la Charte d\u2019Ottawa."),
    ("Comment la déforestation peut-elle favoriser l\u2019émergence de maladies ?", "Elle peut provoquer la disparition d\u2019espèces animales jouant un rôle de réservoir naturel de pathogènes, facilitant la transmission à l\u2019homme."),
    ("Quel rôle jouent les ARS en France ?", "Elles utilisent les travaux de géographie de la santé pour comprendre et anticiper les disparités territoriales dans l\u2019accès aux soins."),
    ("Pourquoi la Révolution industrielle a-t-elle changé les dynamiques de transmission des maladies ?", "Les usines et logements collectifs facilitaient la contagion à grande échelle, contrairement à l\u2019époque préindustrielle où les malades étaient isolés."),
    ("Quelles sont les quelles questions que pose la géographie dans l\u2019étude des différences d\u2019un territoire à l\u2019autre ?", "Les questions d\u2019échelle (local, régional, national), de fracture, de disparité et de comparaison des espaces."),
    ("Comment le COVID-19 illustre-t-il le concept de One Health ?", "Il montre l\u2019importance des interactions écosystémiques et du franchissement de la barrière d\u2019espèce dans l\u2019apparition des maladies."),
    ("Quel est l\u2019Atlas de référence conseillé par la professeure ?", "L\u2019Atlas de la santé en France, volumes 1 et 2."),
    ("Quelle est la différence entre une maladie transmissible et une maladie non transmissible ?", "Une maladie transmissible se propage d\u2019un individu à un autre ou par un vecteur, tandis qu\u2019une maladie non transmissible (chronique) n\u2019est pas contagieuse."),
    ("Quel effet social les réformes hygiénistes du XIXe siècle ont-elles eu ?", "Elles ont favorisé les classes aisées et contribué à la gentrification des centres-villes en détruisant les quartiers ouvriers."),
    ("En quoi la notion de territoire vécu est-elle importante en géographie de la santé ?", "Un même espace peut être perçu différemment selon les populations, ce qui influence l\u2019accès aux soins et l\u2019état de santé."),
    ("À quoi correspond le seuil de renouvellement des générations ?", "À 2 enfants par femme en moyenne, en dessous duquel une population ne peut se renouveler naturellement."),
    ("Qu\u2019est-ce qu\u2019une enquête de cohorte ?", "Une enquête qui suit les mêmes individus dans le temps, contrairement à une enquête transversale qui étudie un échantillon différent à chaque vague."),
    ("Pourquoi dit-on que l\u2019objet santé est un outil en géographie ?", "Parce qu\u2019il aide à comprendre les rapports entre sociétés et espaces, les inégalités territoriales et les dynamiques sociales."),
    ("Quels sont les principaux concepts de la géographie de la santé abordés en cours ?", "L\u2019espace, la distance, le territoire, l\u2019accès, l\u2019accessibilité, les inégalités et les fractures territoriales."),
    ("Quel est le lien entre la qualité de l\u2019air et la théorie des miasmes au XIXe siècle ?", "La théorie des miasmes supposait que certaines maladies étaient dues à la mauvaise qualité de l\u2019air, ce qui a été réfuté par la théorie microbienne de Pasteur."),
    ("Quelle est la contribution d\u2019Emmanuel Vigneron à la géographie de la santé ?", "Il a contribué à structurer la discipline, en participant au débat terminologique entre géographie médicale, des maladies et des soins."),
    ("Qu\u2019est-ce que la conception monoétiologique des maladies ?", "L\u2019idée que chaque maladie est liée à une cause spécifique identifiable, liée à la découverte des bactéries pathogènes."),
    ("Comment l\u2019analyse des pandémies de peste montre-t-elle le lien entre santé et mondialisation ?", "Les épidémies suivaient les routes commerciales, illustrant l\u2019interaction entre échanges humains et propagation des maladies."),
    ("Qu\u2019a permis la quarantaine mise en place à Venise ?", "D\u2019isoler les individus et les marchandises suspectées d\u2019être infectées pour limiter la propagation de la peste."),
],
"SP_Geographie_Sante/fc2.html": [
    ("Qui a publié des travaux précurseurs sur le choléra en Normandie en 1932 ?", "Le docteur Hellis et des médecins de l\u2019hôtel-dieu de Rouen."),
    ("Pourquoi Rouen était-elle un lieu clé pour l\u2019étude du choléra ?", "Parce que c\u2019était une ville en lien avec les échanges maritimes et commerciaux."),
    ("Comment Hellis explique-t-il l\u2019éclosion d\u2019une épidémie ?", "Elle correspond à la somme de la marche de l\u2019épidémie (contagion de proche en proche) avec les circonstances locales."),
    ("Qu\u2019a observé Villermé sur la mortalité au XIXe siècle ?", "Que la mortalité n\u2019est pas seulement liée à la mauvaise qualité de l\u2019air mais aussi au niveau de pauvreté, associant facteurs territoriaux et sociaux."),
    ("Quelle nouveauté Villermé a-t-il apportée dans l\u2019analyse de la mortalité ?", "Il caractérise les individus selon leur statut social, en lien avec l\u2019apparition de la classe ouvrière lors de la révolution industrielle."),
    ("Quel ouvrage Villermé a-t-il publié en 1840 ?", "Un tableau de l\u2019état des ouvriers dans une fabrique de coton."),
    ("Quel type de travaux Edwin Chadwick a-t-il mené en Angleterre ?", "Il a décrit les conditions de vie des habitants les plus pauvres à Londres et en Grande-Bretagne, corrélant mortalité des ouvriers et localisation des usines textiles."),
    ("Quelle est la différence entre Villermé et Chadwick concernant les classes sociales ?", "Villermé remet en cause le système de classes, tandis que Chadwick s\u2019attaque aux effets de la répartition sans remettre en question le système lui-même."),
    ("Quel est le titre de l\u2019ouvrage d\u2019Engels sur les classes ouvrières ?", "« The conditions of the working class in England in 1844 »."),
    ("Que montre Engels dans son ouvrage ?", "Que la mortalité peut être classée en trois classes et que la souffrance des enfants marque de manière indéniable la santé des adultes."),
    ("John Snow a localisé les cas de choléra à Londres en utilisant quel outil ?", "La cartographie."),
    ("Quelle année l\u2019étude de Snow sur le choléra à Londres a-t-elle été réalisée ?", "En 1854."),
    ("Quels concepts Snow a-t-il mobilisés dans son étude du choléra ?", "Les concepts d\u2019espace et de distance."),
    ("Quelle est la contribution de Snow à la géographie de la santé ?", "Il a introduit une méthode précurseure en épidémiologie en utilisant la cartographie pour analyser la répartition spatiale des maladies."),
    ("Qu\u2019a commandé la Royal Commission à Edwin Chadwick en 1832 ?", "Une topographie médicale de Londres, cartographiant la répartition des maladies et des populations vulnérables."),
    ("Comment les cartes de Chadwick annoncent-elles les SIG ?", "Par la superposition de plusieurs couches d\u2019informations (mortalité, pollution, infrastructures urbaines)."),
    ("Qu\u2019est-ce que le mouvement hygiéniste du XIXe siècle ?", "Un mouvement impliquant des médecins de santé publique, prônant une transformation de l\u2019espace urbain à trois échelles : la ville, la rue et le logement."),
    ("Quels étaient les objectifs du mouvement hygiéniste ?", "Aérer, ventiler, dédensifier et purifier l\u2019air des villes."),
    ("Quelles méthodes le mouvement hygiéniste a-t-il utilisées ?", "Lutte contre les logements insalubres, éloignement des activités insalubres, séparation des activités, développement des égouts, élargissement de la voirie et invention de la boîte à ordures."),
    ("Quel personnage emblématique a mené les grands travaux hygiénistes à Paris ?", "Le Baron Haussmann sous le Second Empire."),
    ("Comment les transformations hygiénistes ont-elles affecté les populations modestes ?", "De nombreux quartiers ouvriers ont été détruits, forçant les populations à se déplacer vers la périphérie."),
    ("Qu\u2019est-ce que la transition urbaine ?", "Le passage d\u2019un peuplement majoritairement rural à un peuplement en majorité urbain, avec des activités secondaires et tertiaires."),
    ("Par quels processus la transition urbaine se fait-elle ?", "Par l\u2019exode rural (migration vers les villes) et l\u2019accroissement naturel (différence entre naissances et décès)."),
    ("En quelle année la transition urbaine mondiale a-t-elle eu lieu ?", "En 2008, quand plus de 50 % de l\u2019humanité vit en ville."),
    ("Quel est le taux d\u2019urbanisation mondial en 2020 ?", "Environ 56,2 %."),
    ("Quel est le taux d\u2019urbanisation en France ?", "80,5 %."),
    ("Quels États sont urbanisés à 100 % ?", "Singapour, le Vatican et Monaco."),
    ("Quels pays sont très faiblement urbanisés (10-15 %) ?", "Le Népal et le Bhoutan."),
    ("Quelle était la ville la plus peuplée en 1950 ?", "New York."),
    ("Quelle ville est devenue la plus peuplée en 1980 ?", "Tokyo."),
    ("Selon Denise Pumain, quel est le lien entre taille des villes et inégalités ?", "« Plus les villes sont grandes, plus les inégalités de revenus sont importantes. »"),
    ("Qu\u2019est-ce qu\u2019une carte selon la définition géographique ?", "Une image simplifiée et codifiée de l\u2019espace géographique, représentant ses caractéristiques et/ou son organisation."),
    ("Qu\u2019est-ce que la cartographie ?", "La discipline artistique, scientifique et technique ayant pour objet la construction de cartes."),
    ("Qui a utilisé pour la première fois le mot « Kartograph » et en quelle année ?", "Karl Ritter (Société géographique de Berlin) en 1828."),
    ("En quelle année la Société française de cartographie a-t-elle employé le mot « Cartographie » ?", "En 1929."),
    ("Quelles sont les trois fonctions principales d\u2019une carte ?", "Se repérer (orientation), comprendre l\u2019espace (visualiser et analyser l\u2019information) et communiquer (transmettre une information)."),
    ("Que permettent les SIG (Systèmes d\u2019Information Géographique) en cartographie de santé ?", "De superposer plusieurs couches d\u2019informations (densité de population, pollution, accès aux soins) pour des analyses précises."),
    ("Quelle est la différence entre échelle et maille en cartographie ?", "L\u2019échelle désigne tout le territoire observable (mondiale, nationale), tandis que la maille est le périmètre auquel l\u2019indication est donnée (départementale, régionale)."),
    ("Qu\u2019est-ce que la sémiologie graphique ?", "L\u2019ensemble des règles régissant l\u2019usage des couleurs, symboles et formes dans la représentation cartographique."),
    ("Pourquoi dit-on qu\u2019une carte n\u2019est jamais neutre ?", "Parce que les données sont choisies et agencées par un auteur, avec des choix de couleurs et de classification qui influencent l\u2019interprétation."),
    ("Quel est le RGPD et comment affecte-t-il les données de santé ?", "Le Règlement Général de Protection des Données interdit en principe de recueillir les données de santé, sauf exceptions motivées pour la recherche ou l\u2019évaluation d\u2019intérêt public."),
    ("Quelles exceptions au RGPD permettent l\u2019utilisation des données de santé ?", "L\u2019information sur la santé, les politiques de santé, les dépenses de santé, l\u2019information des professionnels, l\u2019innovation et la surveillance sanitaire."),
    ("Pourquoi l\u2019OMS souligne-t-elle l\u2019importance des données de santé ?", "Parce que « aucun système de santé ne peut fonctionner sans information de qualité » et plus des 2/3 de la population mondiale n\u2019a pas de statistiques de mortalité détaillées."),
    ("Quels problèmes identifie le rapport de l\u2019OMS (2000) sur les systèmes d\u2019information sanitaire ?", "L\u2019absence de données dans les pays qui en ont le plus besoin, les difficultés de repérage des besoins et la péremption des données existantes."),
    ("Quels enjeux contemporains lient ville et santé ?", "La santé mentale, le bruit, le vieillissement et handicap, la sédentarité, les pollutions, les inégalités d\u2019accès aux soins, la prévention et la promotion de la santé."),
    ("En quoi la Seine-Saint-Denis est-elle un exemple de désert médical urbain ?", "C\u2019est une zone urbaine de la banlieue parisienne qui pose une vraie problématique d\u2019accès aux soins malgré sa proximité avec Paris."),
    ("Quel est le défi principal pour les pays « du Nord » concernant la santé urbaine ?", "L\u2019accès aux services pour une population vieillissante et les fortes inégalités sociales de santé."),
    ("Quel est le défi principal pour les pays « du Sud » concernant la santé urbaine ?", "La gestion des déchets, l\u2019accès à l\u2019eau potable, les maladies vectorielles et les inégalités extrêmes entre quartiers riches et bidonvilles."),
    ("Pourquoi l\u2019image de la France rurale persiste-t-elle malgré un taux d\u2019urbanisation de 80,5 % ?", "En raison du patrimoine culturel et agricole et d\u2019une mythologie nationale liée aux terroirs et traditions locales."),
    ("Que signifie le « double modèle explicatif » du XIXe siècle en matière de santé urbaine ?", "L\u2019opposition entre le modèle du lien environnement-santé et le nouveau modèle monoétiologique de la théorie microbienne."),
    ("Qu\u2019est-ce qu\u2019un urbanisme favorable à la santé ?", "Un type d\u2019urbanisme qui promeut la santé et le bien-être des populations en agissant sur l\u2019aménagement urbain."),
    ("Quelles problématiques contemporaines lient pollution et santé en ville ?", "La pollution de l\u2019air (microparticules des véhicules en milieu urbain) et l\u2019utilisation de pesticides en milieu rural."),
    ("Pourquoi les leviers d\u2019action en santé urbaine varient-ils selon les contextes ?", "Parce que les défis diffèrent entre les villes (Paris vs Lagos vs Jakarta), nécessitant des approches adaptées."),
    ("Que révèle la citation « La géographie, ça sert d\u2019abord à faire la guerre » ?", "La dimension géopolitique des cartes : elles sont utilisées pour influencer les perceptions et justifier des décisions politiques ou militaires."),
    ("Comment la classification des données influence-t-elle la perception d\u2019une carte ?", "Selon les seuils choisis, une même carte peut apparaître très différente, influençant l\u2019interprétation."),
    ("Quel est l\u2019impact du Japon en matière de vieillissement de la population ?", "Le Japon est un exemple emblématique où le vieillissement constitue un enjeu de santé publique crucial, avec un déséquilibre entre jeunes actifs et personnes âgées."),
    ("Quelles sont les spécificités des villes de Mumbai, Lagos ou Rio de Janeiro ?", "L\u2019urbanisation rapide y entraîne une forte concentration des inégalités sociales avec une juxtaposition entre quartiers riches et bidonvilles."),
    ("Quelle est la citation d\u2019Yves Lacoste sur la subjectivité des données géographiques ?", "Les données géographiques sont choisies et classées par le géographe ; un autre géographe fournirait probablement des données différentes."),
    ("Pourquoi est-il indispensable d\u2019avoir un regard critique sur les données cartographiques ?", "Pour s\u2019interroger sur la précision, la crédibilité, le contexte de production, le fournisseur et le discours construit à partir des données."),
    ("Comment les couleurs influencent-elles l\u2019interprétation des cartes ?", "Le rouge signale une intensité croissante, le bleu/vert des données neutres ou favorables ; ces choix ne sont pas neutres et influencent la perception instinctive."),
    ("Qu\u2019est-ce que l\u2019information sanitaire perçue comme « obscure » ?", "Elle est considérée comme spécifique aux épidémiologistes et pas très accessible aux décideurs publics."),
    ("À quelle date a eu lieu la transition urbaine mondiale ?", "En 2008."),
    ("Quels pays ont des taux d\u2019urbanisation supérieurs à 75 % ?", "Quasi-totalité du continent américain, Australie, Afrique du Sud, Europe, Japon."),
    ("Qu\u2019observe-t-on en termes de glissement dans l\u2019urbanisation mondiale ?", "Un rattrapage des grandes villes d\u2019Amérique du Nord et d\u2019Europe par des villes situées dans les pays du Sud ou États émergents."),
    ("Quelle est la ville la plus peuplée en 2010 ?", "Tokyo et Bombay dépassent New York, illustrant le dépassement des pays du Nord par les pays du Sud."),
    ("Quels sont les défis majeurs des métropoles gigantesques du Sud global ?", "Le logement, les transports, les infrastructures et l\u2019accès aux services."),
    ("Pourquoi la connaissance du producteur de données cartographiques est-elle importante ?", "Parce que la production de données et leur divulgation ne sont jamais neutres ; il faut savoir qui les construit et à quelles fins."),
    ("Comment l\u2019hygiénisme du XIXe siècle a-t-il transformé Paris concrètement ?", "Par la création de caniveaux, l\u2019élargissement de la voirie, les lois sur les logements insalubres, le développement des égouts et l\u2019éloignement des activités insalubres."),
    ("Quel rapport existe entre les premiers urbanistes et la médecine ?", "Les premiers urbanistes étaient des médecins, ce qui a eu une répercussion sur leurs travaux et leur manière de voir la ville."),
    ("Comment l\u2019urbanisation croissante influence-t-elle la gestion des ressources ?", "Elle accentue les enjeux de gestion des ressources, d\u2019aménagement et de qualité de vie, surtout dans les villes en croissance rapide."),
    ("Quels penseurs du XIXe siècle ont abordé les inégalités sous l\u2019angle des rapports de classe ?", "Karl Marx et Hegel."),
    ("Qu\u2019est-ce que le processus d\u2019urbanisation variable selon les régions ?", "Le fait que l\u2019urbanisation se fait dans des temporalités et des intensités différentes selon les pays et les régions du monde."),
    ("Quel est le rôle de la taille et de la forme des éléments graphiques sur une carte ?", "Ils influencent la perception des données ; un même phénomène peut paraître différent selon les choix de représentation."),
    ("Quel est le lien entre industrie textile et santé au XIXe siècle en Angleterre ?", "Les usines textiles étaient source de pollution pour les travailleurs et les quartiers ouvriers adjacents, cumulant conditions de travail et de vie néfastes."),
],
"SP_Geographie_Sante/fc3.html": [
    ("Comment est organisée l\u2019offre de soins en France ?", "C\u2019est un système mixte combinant intervention publique et privée, avec trois niveaux de recours de plus en plus spécialisés."),
    ("Quels sont les trois acteurs principaux du système de soins français ?", "L\u2019acteur public (État et assurance maladie), les entreprises et la population (financeurs et bénéficiaires)."),
    ("Quel rôle jouent les Agences Régionales de Santé (ARS) ?", "Elles déclinent la politique de santé publique au niveau régional, organisent l\u2019offre de soins et la veille sanitaire."),
    ("Quelle loi a créé les ARS et en quelle année ?", "La loi Hôpital Patient Santé Territoire (HPST), dite loi Bachelot, en 2009."),
    ("Quels sont les quatre titres de la loi HPST ?", "Modernisation des établissements de santé, amélioration de l\u2019accès aux soins, prévention et santé publique, organisation territoriale du système de santé."),
    ("Quelle est la différence entre égalité et équité dans l\u2019accès aux soins ?", "L\u2019égalité implique une offre uniforme sur tout le territoire, tandis que l\u2019équité reconnaît que certains territoires nécessitent des ressources spécifiques."),
    ("Quels sont les trois axes principaux de la loi de modernisation de janvier 2016 ?", "Prévention, accès aux soins et innovation."),
    ("Quelles mesures de prévention la loi de 2016 a-t-elle instaurées ?", "Le paquet neutre de cigarettes, le logo nutritionnel sur les emballages et l\u2019expérimentation de salles de consommation à moindre risque."),
    ("Où ont été installées les salles de consommation à moindre risque ?", "Une à Paris et une à Strasbourg."),
    ("Quelles améliorations de l\u2019accès aux soins la loi de 2016 a-t-elle apportées ?", "Généralisation du tiers payant, numéro d\u2019appel unique pour médecin de garde, médecin traitant pour les enfants de 0 à 16 ans."),
    ("Qu\u2019est-ce que le droit à l\u2019oubli créé par la loi de 2016 ?", "Le droit pour les anciens malades du cancer et d\u2019autres pathologies lourdes de ne plus être discriminés (emploi, prêt bancaire)."),
    ("Qu\u2019est-ce que la loi « Ma Santé 2022 » de 2019 ?", "Une réforme visant à réorganiser l\u2019offre de soins avec la fin du numerus clausus, la création d\u2019assistants médicaux et le développement de la télémédecine."),
    ("Qu\u2019est-ce que le numerus clausus ?", "La limitation du nombre d\u2019étudiants en médecine, supprimée par la loi Ma Santé 2022."),
    ("Qu\u2019est-ce qu\u2019une Maison de Santé Pluridisciplinaire (MSP) ?", "Un mode d\u2019exercice collectif et coordonné créé en 2007, regroupant des professionnels de santé libéraux de soins primaires autour d\u2019un projet de santé commun."),
    ("Quelle est la différence entre besoin en soins et demande de soins ?", "Le besoin correspond à l\u2019état de santé et aux soins nécessaires, la demande dépend des comportements individuels et collectifs influencés par des facteurs économiques et sociaux."),
    ("Qu\u2019est-ce que le non-recours aux soins ?", "Le fait que des personnes éligibles à des aides d\u2019accès aux soins n\u2019y recourent pas, pour des raisons économiques, géographiques ou culturelles."),
    ("Quelle est la liberté d\u2019installation en France ?", "Le principe fondamental permettant aux médecins, infirmiers et autres professionnels de choisir librement leur lieu d\u2019exercice."),
    ("Quelle profession de santé est soumise à des quotas d\u2019implantation ?", "Les pharmaciens, dont les quotas sont définis par l\u2019Ordre des Pharmaciens."),
    ("Combien coûte le système de santé français par an ?", "240 milliards d\u2019euros par an, soit environ 12 % du PIB."),
    ("Comment est financé le système de soins français ?", "75 % par l\u2019assurance maladie, 15 % par les mutuelles et 10 % par les ménages."),
    ("Qu\u2019est-ce que la PUMA (Protection Universelle Maladie) ?", "Le dispositif qui garantit la prise en charge des frais de santé à toute personne travaillant ou résidant en France de manière stable et régulière."),
    ("Quelles sont les conditions d\u2019accès à la PUMA ?", "Résider en France de manière régulière (nationalité française ou titre de séjour) et stable (depuis plus de trois mois)."),
    ("Qu\u2019est-ce que l\u2019AME (Aide Médicale d\u2019État) ?", "Une prise en charge à 100 % permettant aux personnes sans papiers résidant en France depuis plus de 3 mois et sous un plafond de ressources d\u2019accéder à des soins gratuits."),
    ("Pourquoi l\u2019AME est-elle essentielle pour la santé publique ?", "Elle permet d\u2019éviter la propagation de maladies faute de prise en charge des populations vulnérables."),
    ("Quel rôle jouent les associations comme Médecins du Monde pour l\u2019AME ?", "Elles accompagnent les populations en leur fournissant une domiciliation administrative nécessaire pour bénéficier des aides."),
    ("Combien de médecins y avait-il en France entre 1979 et 2015 ?", "De 118 842 en 1979 à 281 087 en 2015, soit une augmentation de 136,5 %."),
    ("Quelle est la densité médicale moyenne en France en 2021 ?", "3,2 médecins pour 1 000 habitants."),
    ("Combien de médecins de moins de 70 ans sont en activité en France en 2021 ?", "215 000, dont 94 500 généralistes et 120 000 spécialistes."),
    ("Quelle est la densité médicale moyenne à l\u2019échelle départementale en 2015 ?", "266,4 médecins pour 100 000 habitants."),
    ("Quelles spécialités médicales sont particulièrement touchées par la pénurie ?", "L\u2019obstétrique, l\u2019anesthésie-réanimation, la chirurgie et la psychiatrie."),
    ("Quelle est la tendance du mode d\u2019exercice médical en France ?", "Un exercice de plus en plus salarié : 62 % des nouveaux médecins inscrits au Conseil de l\u2019Ordre en 2019 sont salariés."),
    ("Quel pourcentage de médecins exercent en libéral en 2022 ?", "51,8 % en activité libérale ou mixte contre 48,1 % en salariat."),
    ("Quel phénomène démographique affecte la profession médicale ?", "Le vieillissement des professionnels en exercice, avec de nombreux médecins approchant l\u2019âge de la retraite."),
    ("Comment la féminisation de la profession médicale évolue-t-elle ?", "La profession est de plus en plus féminisée, ce qui influence les modes d\u2019exercice et les aspirations professionnelles."),
    ("Qu\u2019est-ce qu\u2019un désert médical ?", "Un territoire où les populations rencontrent des difficultés d\u2019accès aux soins : délais d\u2019attente, impossibilité de trouver un médecin traitant, renoncement aux soins."),
    ("Quelles sont les causes multiples des déserts médicaux ?", "La raréfaction de l\u2019offre, les comportements d\u2019installation des médecins, les inégalités territoriales et les fractures plus larges (peuplement, attractivité, emploi, enclavement)."),
    ("Quelles mesures sont proposées pour lutter contre les déserts médicaux ?", "Primes à l\u2019installation (jusqu\u2019à 50 000 euros), exonérations fiscales, aides au logement et soutien aux MSP."),
    ("Qu\u2019est-ce que le marketing territorial dans le contexte médical ?", "Des stratégies mises en place par les communes pour attirer des médecins, incluant communication et incitations à l\u2019installation."),
    ("Qu\u2019est-ce que la Complémentaire Santé Solidaire (ex-CMU-C) ?", "Un dispositif sous conditions de plafond de revenu et de résidence stable offrant une couverture santé complémentaire."),
    ("De combien le tarif des consultations a-t-il augmenté le 1er novembre 2023 ?", "De 1,50 euro en métropole et de 1,80 euro dans les DROM."),
    ("Quels sont les objectifs globaux d\u2019un système de santé ?", "La satisfaction des usagers, la qualité des soins et l\u2019accessibilité à tous sur tout le territoire."),
    ("Qu\u2019est-ce que l\u2019ONDAM ?", "L\u2019Objectif National des Dépenses de l\u2019Assurance Maladie, outil de contrôle des dépenses de santé."),
    ("Qu\u2019est-ce que les CPTS ?", "Les Communautés Professionnelles Territoriales de Santé, qui contractualisent avec les ARS pour améliorer l\u2019organisation des soins à l\u2019échelle locale."),
    ("Quelle organisme a été créé par la loi de 2016 pour la prévention ?", "Santé Publique France, fusionnant plusieurs structures existantes."),
    ("Pourquoi le phénomène de désert médical va-t-il perdurer ?", "À cause de l\u2019extension des zones sous-dotées et de la latence des mesures (exemple : réforme du numerus clausus)."),
    ("Qu\u2019est-ce que le « territoire de vie » en démographie médicale ?", "Un périmètre prenant en compte les mobilités domicile-travail et les mobilités d\u2019achats pour analyser l\u2019accès aux soins."),
    ("Pourquoi l\u2019échelle régionale efface-t-elle des disparités ?", "Parce qu\u2019elle masque des disparités locales très importantes à l\u2019intérieur des départements."),
    ("Quelle est la proportion de médecins en libéral à Paris ?", "63 % des médecins parisiens sont salariés, en raison de la présence des hôpitaux."),
    ("Qu\u2019est-ce que la médicalisation croissante de la société ?", "Le recours de plus en plus fréquent à la médecine, y compris pour des maux légers, grâce à l\u2019accroissement des connaissances et des capacités de soins."),
    ("Quels facteurs expliquent le vieillissement de la population française comme enjeu de santé ?", "L\u2019accroissement de la demande en soins, la détérioration de la santé avec l\u2019âge et les contraintes de mobilité."),
    ("Quel pourcentage de jeunes médecins souhaitent exercer en cabinet de groupe ou MSP ?", "Plus de la moitié des jeunes médecins concernés."),
    ("Quel est le principal facteur de renoncement au métier chez les jeunes médecins ?", "Le syndrome d\u2019épuisement professionnel (burn-out)."),
    ("Quel pourcentage de jeunes médecins sont attachés à l\u2019équilibre vie familiale ?", "86 % se déclarent attachés à l\u2019équilibre de leur vie familiale."),
    ("Pourquoi les jeunes médecins préfèrent-ils l\u2019exercice en groupe ?", "Pour rompre l\u2019isolement, partager les responsabilités, mutualiser les tâches administratives et avoir un meilleur équilibre vie pro/perso."),
    ("Quels sont les avantages d\u2019une MSP pour les patients ?", "Offre de soins de proximité, prise en charge globale, continuité des soins et parcours de soins simplifié."),
    ("Quels sont les avantages d\u2019une MSP pour les professionnels ?", "Exercice coordonné, échanges interprofessionnels, souplesse d\u2019organisation, mutualisation des frais et rémunération spécifique."),
    ("Quel est l\u2019exemple de la maison de santé d\u2019Espéraza ?", "Une MSP inaugurée en 2018 dans les Pyrénées audoises, accueillant 17 professionnels, portée par un médecin et soutenue par la communauté de communes et l\u2019ARS."),
    ("Que représentent les Contrats Locaux de Santé Mentale (CLSM) ?", "Des contrats développés par les ARS avec des collectivités territoriales, hôpitaux et associations de prévention."),
    ("Qu\u2019est-ce que la suppression du délai de réflexion pour l\u2019IVG apportée par la loi de 2016 ?", "La suppression du délai obligatoire de 7 jours de réflexion avant une IVG."),
    ("Quel enjeu majeur concerne le reste à charge pour les patients en France ?", "Certains soins restent peu ou pas remboursés, créant des inégalités financières d\u2019accès aux soins."),
    ("Comment le système de cotisations finance-t-il le système de santé ?", "Par des cotisations patronales (employeurs) et des cotisations sociales (prélèvements sur les revenus de la population)."),
    ("Combien de professionnels la maison de santé d\u2019Espéraza accueille-t-elle ?", "17 professionnels : 5 médecins généralistes, 2 dentistes, 3 cabinets d\u2019infirmiers, 2 diététiciennes, un pédicure-podologue et un kinésithérapeute."),
    ("Quel a été le coût des travaux de la MSP d\u2019Espéraza ?", "651 493 euros HT, financés par l\u2019État, le conseil régional, le conseil départemental et la communauté de communes."),
    ("Quelle est la part de l\u2019État dans le financement de la MSP d\u2019Espéraza ?", "225 452 euros."),
    ("Qu\u2019est-ce que l\u2019action de groupe en santé créée par la loi de 2016 ?", "Un droit permettant à un groupe de patients de mener une action collective en justice pour obtenir réparation."),
    ("Quel phénomène caractérise la montée en puissance des centres de santé ?", "62 % des nouveaux médecins inscrits en 2019 sont salariés, reflétant le développement des centres pluridisciplinaires."),
    ("Quels trois défis majeurs le système de santé français doit-il relever ?", "Réduire les inégalités territoriales, adapter le système au vieillissement et intégrer les nouvelles technologies et la télémédecine."),
    ("Qu\u2019est-ce que la planification sanitaire ?", "L\u2019objectif de répartir équitablement les services de santé sur le territoire, passant de la planification nationale à régionale via la loi HPST."),
    ("Quel exemple illustre la différence de priorités entre ARS régionales ?", "En Île-de-France, l\u2019accent est sur la pollution de l\u2019air ; en Auvergne, la priorité est la lutte contre la désertification médicale."),
    ("Pourquoi les pharmaciens sont-ils soumis à des quotas contrairement aux médecins ?", "L\u2019Ordre des Pharmaciens définit des quotas d\u2019implantation, tandis que les médecins bénéficient de la liberté d\u2019installation."),
    ("Quelle est la conséquence de la liberté d\u2019installation sur la répartition des médecins ?", "Une concentration dans les grandes villes et des déficits en zones rurales, créant des déserts médicaux."),
    ("Comment les ARS soutiennent-elles financièrement les projets locaux de santé ?", "Via des appels à projets destinés aux municipalités, associations et équipes médicales."),
    ("Quel rôle joue la télémédecine dans la lutte contre les déserts médicaux ?", "Elle améliore la continuité des soins et l\u2019accès aux spécialistes à distance, réduisant la dépendance à la proximité géographique."),
    ("Quelle est la proportion de jeunes médecins prêts à renoncer à la profession ?", "Près de 66 % se disent prêts à renoncer dans les prochaines années pour des raisons liées aux conditions d\u2019exercice."),
    ("Quels sont les principaux indicateurs de la démographie médicale en France ?", "Le nombre total de médecins, la densité pour 1000 habitants, la répartition par spécialité et par territoire, le mode d\u2019exercice et l\u2019âge des praticiens."),
    ("Qu\u2019est-ce que le Code de la santé publique ?", "Le cadre réglementaire qui régit l\u2019organisation et le fonctionnement du système de santé en France."),
    ("Comment la réforme du numerus clausus affecte-t-elle la démographie médicale ?", "Elle augmente le nombre d\u2019étudiants en médecine mais les effets ne se feront sentir qu\u2019avec un délai de plusieurs années."),
    ("Quel est le lien entre augmentation des maladies chroniques et pression sur l\u2019offre de soins ?", "L\u2019augmentation du diabète, des maladies cardiovasculaires et du cancer accroît la demande de soins de manière continue."),
],
}
