{ question: 'Quel est l’objectif de la biologie du développement ?', answer: 'Comprendre comment une cellule unique, le zygote, donne naissance à un individu composé de centaines de types cellulaires différents.', },
{ question: 'Quel est le premier phénomène observé lors du développement ?', answer: 'La prolifération cellulaire.', },
{ question: 'Pourquoi l’étude de la prolifération cellulaire est-elle importante ?', answer: 'Parce que ces programmes peuvent se réactiver chez l’adulte dans le cancer.', },
{ question: 'Quel est l’enjeu de l’étude de la détermination et de la différenciation des cellules souches ?', answer: 'Orienter des cellules souches vers la formation d’organes spécifiques pour la médecine régénérative.', },
{ question: 'Que permettent les connaissances sur la morphogenèse ?', answer: 'Déceler des malformations fines et adapter le suivi de la grossesse.', },
{ question: 'Quel est le rôle des gènes Hox ?', answer: 'Définir le plan d’organisation selon l’axe rostro-caudal.', },
{ question: 'Qu’est-ce qu’une transformation homéotique ?', answer: 'La transformation d’un organe en une autre structure.', },
{ question: 'Qu’est-ce qu’un agent tératogène ?', answer: 'Un agent provoquant des malformations pendant les périodes critiques du développement.', },
{ question: 'Quel effet avait le Distilbène sur les fœtus ?', answer: 'Il affectait les gènes Hox entraînant des malformations utérines et l’infertilité.', },
{ question: 'Quel est l’effet du Roaccutane lors d’une grossesse ?', answer: 'Une postériorisation de l’embryon et des défauts des structures neurales antérieures.', },
{ question: 'Quel est l’effet morphogénétique de l’acide rétinoïque ?', answer: 'C’est une molécule postériorisante.', },
{ question: 'Quelles sont les principales étapes du cycle de développement du xénope ?', answer: 'Fécondation, clivage, gastrulation, neurulation, organogenèse, croissance, stade larvaire ou adulte, maturité sexuelle.', },
{ question: 'Que disait la théorie de la préformation ?', answer: 'L’adulte est déjà présent en miniature dans le gamète mâle.', },
{ question: 'Quelle théorie défendait Aristote ?', answer: 'L’épigénèse : les organes se forment de novo à chaque génération.', },
{ question: 'Quel stade embryonnaire vertébré témoigne d’un ancêtre commun ?', answer: 'Le stade phylotypique.', },
{ question: 'Quelle affirmation centrale a permis la théorie cellulaire ?', answer: 'La cellule est l’unité de base des êtres vivants.', },
{ question: 'Quelle est la contribution parentale au noyau du zygote selon Hertwig ?', answer: 'Une contribution équivalente de chromosomes de chaque parent.', },
{ question: 'Quelles sont les méthodes de l’embryologie expérimentale ?', answer: 'Destruction, isolement, greffe de cellules, lignage cellulaire.', },
{ question: 'Quelle conclusion découle du développement mosaïque ?', answer: 'Les cellules héritent de déterminants qui fixent leur destin.', },
{ question: 'Pour quels organismes le développement mosaïque est-il vrai ?', answer: 'L’ascidie.', },
{ question: 'Quelle conclusion apporte Driesch sur le développement ?', answer: 'Le développement des vertébrés est régulé et peut se rétablir après séparation des blastomères.', },
{ question: 'Qu’est-ce que la spécification cellulaire ?', answer: 'Un engagement réversible d’une cellule dans une voie de différenciation.', },
{ question: 'Qu’est-ce que la détermination cellulaire ?', answer: 'Un engagement irréversible dans une voie de différenciation.', },
{ question: 'Qu’est-ce que la différenciation cellulaire ?', answer: 'L’acquisition de caractéristiques morphologiques et fonctionnelles propres.', },
{ question: 'Quel est l’objectif du lignage cellulaire ?', answer: 'Étudier le devenir d’une cellule et établir la carte des territoires présomptifs.', },
{ question: 'Qu’a démontré l’expérience de Spemann et Mangold ?', answer: 'L’existence d’un centre organisateur capable d’induire un second axe de développement.', },
{ question: 'Quels sont les deux phénomènes à l’origine de la différenciation cellulaire ?', answer: 'La ségrégation de déterminants et l’induction embryonnaire.', },
{ question: 'Dans une induction, qu’est-ce qu’une cellule inductrice ?', answer: 'La cellule émettrice du signal.', },
{ question: 'Qu’est-ce qu’une cellule induite ?', answer: 'Une cellule compétente possédant les récepteurs nécessaires.', },
{ question: 'Qu’illustre le modèle du drapeau français ?', answer: 'L’effet dose-dépendant d’un signal inducteur.', },
{ question: 'Quel type d’approche a été utilisée par Nüsslein-Volhard et Wieschaus ?', answer: 'Approche génétique du phénotype au génotype via mutants de drosophile.', },
{ question: 'Quels sont les 3 feuillets embryonnaires ?', answer: 'Ectoderme, mésoderme, endoderme.', },
{ question: 'Que donne l’ectoderme ?', answer: 'Épiderme et système nerveux.', },
{ question: 'Quels sont les dérivés du neurectoderme ?', answer: 'Cerveau et moelle épinière.', },
{ question: 'Quels sont les dérivés des crêtes neurales ?', answer: 'Squelette de la face, nerfs crâniens, cellules pigmentaires, médullosurrénales.', },
{ question: 'Que donne le mésoderme axial ?', answer: 'La chorde.', },
{ question: 'Que donne le sclérotome ?', answer: 'Le squelette vertébral.', },
{ question: 'Que donne le myotome ?', answer: 'Les muscles.', },
{ question: 'Quels sont les dérivés du mésoderme intermédiaire ?', answer: 'Reins et gonades.', },
{ question: 'Que donne le mésoderme latéral somatopleural ?', answer: 'Péricarde, derme latéral, crêtes génitales.', },
{ question: 'Que donne la splanchnopleure ?', answer: 'Muscles lisses, rate, cœur, appareil circulatoire, mésentère.', },
{ question: 'Quels sont les dérivés de l’endoderme ?', answer: 'Tube digestif, trachée, poumons, thyroïde, foie, pancréas.', },
{ question: 'Quels sont les quatre niveaux de potentialité cellulaire ?', answer: 'Totipotente, pluripotente, multipotente, unipotente.', },
{ question: 'Que permet une cellule totipotente ?', answer: 'Former l’embryon et les annexes extra-embryonnaires.', },
{ question: 'Que permet une cellule pluripotente ?', answer: 'Former les trois feuillets embryonnaires.', },
{ question: 'Qu’est-ce qui caractérise la multipotence ?', answer: 'Différenciation possible dans plusieurs types d’un même feuillet.', },
{ question: 'Qu’est-ce que l’unipotence ?', answer: 'La capacité à produire un seul type cellulaire.', },
{ question: 'Quel modèle est utilisé pour l’étude de l’axe PA-PV ?', answer: 'Le xénope.', },
{ question: 'Quelles enveloppes protègent l’ovocyte de xénope ?', answer: 'La membrane vitelline et la gangue.', },
{ question: 'Quel est le rôle du vitellus ?', answer: 'Réserve alimentaire lipidique.', },
{ question: 'Comment est déterminé le pôle animal chez le xénope ?', answer: 'Par la pigmentation.', },
{ question: 'En quelle phase de méiose est bloqué l’ovocyte fécondable ?', answer: 'Métaphase II.', },
{ question: 'Qu’est-ce qu’un œuf hétérolécithe ?', answer: 'Un œuf dont les réserves sont distribuées de façon hétérogène.', },
{ question: 'Quels ARNm sont spécifiques de l’hémisphère végétatif ?', answer: 'Vg1, VegT, Xwnt11.', },
{ question: 'Quel événement met en place l’axe dorso-ventral ?', answer: 'La fécondation.', },
{ question: 'Quel est le rôle du centrosome spermatique ?', answer: 'Organiser les microtubules dans le cortex végétatif.', },
{ question: 'Qu’est-ce que la rotation corticale ?', answer: 'Un basculement de 30° du cortex vers le point d’entrée du spermatozoïde.', },
{ question: 'Que marque le croissant gris ?', answer: 'La future face dorsale de l’embryon.', },
{ question: 'Que donnera le pôle animal ?', answer: 'Le pôle antérieur.', },
{ question: 'Que donnera le pôle végétatif ?', answer: 'Le pôle postérieur.', },
{ question: 'Quel rôle jouent les microtubules dans la rotation corticale ?', answer: 'Transport du contenu cortical et formation des structures dorsales.', },
{ question: 'Que provoque une irradiation UV du pôle végétatif ?', answer: 'Une désorganisation des microtubules et une ventralisation.', },
{ question: 'Comment prouve-t-on la nécessité des microtubules ?', answer: 'Leur blocage empêche la rotation corticale et les structures dorsales.', },
{ question: 'Comment peut-on sauver un embryon irradié aux UV ?', answer: 'Par injection de cytoplasme végétatif contenant les déterminants dorsalisants.', },
{ question: 'Que prouve la microdissection du croissant gris ?', answer: 'Son rôle indispensable dans la formation des structures dorsales.', },
{ question: 'Que provoque la greffe d’un croissant gris au pôle ventral ?', answer: 'La formation de deux régions dorsales.', },
{ question: 'Quand se met en place l’axe dorso-ventral ?', answer: 'Avant la segmentation.', },
