{ question: 'Quels sont les deux grands types de segmentation ?', answer: 'La segmentation holoblastique (totale) et la segmentation méroblastique (incomplète).', },
{ question: 'Dans quels organismes la segmentation est-elle holoblastique ?', answer: 'Chez les amphibiens et l’Homme.', },
{ question: 'Dans quels organismes la segmentation est-elle méroblastique ?', answer: 'Chez les céphalopodes, poissons et insectes.', },
{ question: 'Quand apparaît le premier sillon de division chez le xénope ?', answer: 'Juste après la fécondation.', },
{ question: 'Quel est le résultat du premier clivage chez le xénope ?', answer: 'Deux blastomères identiques.', },
{ question: 'Quel est le résultat du deuxième clivage chez le xénope ?', answer: 'Quatre blastomères identiques.', },
{ question: 'Quand apparaît l’asymétrie de clivage ?', answer: 'Au stade 8 cellules.', },
{ question: 'Qu’est-ce qu’un micromère ?', answer: 'Un blastomère de petite taille au pôle animal.', },
{ question: 'Qu’est-ce qu’un macromère ?', answer: 'Un blastomère de grande taille au pôle végétatif.', },
{ question: 'Quel est l’aspect de l’embryon au stade 32 cellules ?', answer: 'Une morula ressemblant à une petite mûre.', },
{ question: 'Qu’est-ce que le blastocèle ?', answer: 'Une cavité transitoire située au pôle animal au stade blastula.', },
{ question: 'Quelles glycoprotéines composent la matrice extracellulaire du toit du blastocèle ?', answer: 'La fibronectine et la laminine.', },
{ question: 'Quelle est la structure de la fibronectine ?', answer: 'Deux sous-unités liées par ponts disulfures avec domaines d’interaction.', },
{ question: 'Quelle est la structure de la laminine ?', answer: 'Trois chaînes polypeptidiques en triple hélice avec sites de liaison aux intégrines.', },
{ question: 'Quels types de jonctions présentent les micromères du pôle animal ?', answer: 'Jonctions serrées en externe et jonctions GAP en interne.', },
{ question: 'Quelles sont les deux grandes familles de molécules d’adhérence ?', answer: 'Les cadhérines et les intégrines.', },
{ question: 'Quel est le rôle des cadhérines ?', answer: 'Assurer les interactions cellule-cellule via les jonctions adhérentes.', },
{ question: 'Quelle est la structure fonctionnelle des intégrines ?', answer: 'Des hétérodimères interagissant avec la matrice extracellulaire.', },
{ question: 'Quelle est la particularité du cycle cellulaire durant les 10-12 premiers cycles ?', answer: 'Absence de G1, alternance rapide entre phases S et M.', },
{ question: 'Qu’est-ce que la transition blastuléenne ?', answer: 'Le moment où les divisions deviennent asynchrones avec apparition de G1 et allongement de G2.', },
{ question: 'Quels feuillets sont spécifiés avant 32 cellules ?', answer: 'L’ectoderme et l’endoderme.', },
{ question: 'Quand apparaît la spécification du mésoderme ?', answer: 'Entre le stade 32 et 64 cellules.', },
{ question: 'Quelle expérience permet de visualiser la spécification au stade blastula ?', answer: 'L’isolement et la culture in vitro des blastomères puis analyse histologique.', },
{ question: 'Quel est le destin des blastomères animaux isolés ?', answer: 'Ils se différencient en épiderme.', },
{ question: 'Quel est le destin des blastomères végétatifs isolés ?', answer: 'Ils donnent de l’endoderme.', },
{ question: 'Quel est le destin des blastomères de la zone marginale ?', answer: 'Ils donnent du mésoderme.', },
{ question: 'Quelle était la question de Nieuwkoop concernant le mésoderme ?', answer: 'Les cellules mésodermiques proviennent-elles de la calotte animale ou des blastomères végétatifs ?', },
{ question: 'Qu’a montré le marquage des cellules de la calotte animale dans les recombinaisons ?', answer: 'Seules les cellules de la calotte animale deviennent mésodermiques.', },
{ question: 'Quel est le rôle des blastomères végétatifs dans l’induction du mésoderme ?', answer: 'Ils sont la source du signal inductif.', },
{ question: 'Quel résultat donne l’interposition d’un filtre étanche entre calotte animale et blastomères végétatifs ?', answer: 'Absence d’induction mésodermique.', },
{ question: 'Quel résultat donne l’utilisation d’un filtre poreux ?', answer: 'Induction mésodermique.', },
{ question: 'Quelle conclusion tire-t-on des expériences avec filtres ?', answer: 'L’induction du mésoderme dépend d’un signal diffusible.', },
{ question: 'Que montrent les expériences de Dale et Slack ?', answer: 'L’induction mésodermique est régionalisée selon l’axe dorso-ventral.', },
{ question: 'Que produit la calotte animale seule ?', answer: 'Uniquement de l’épiderme.', },
{ question: 'Que produit la calotte animale + D1 ?', answer: 'Épiderme, chorde, muscle, endoderme.', },
{ question: 'Que produit la calotte animale + D2 ?', answer: 'Épiderme, mésenchyme, cellules sanguines, endoderme.', },
{ question: 'Quelle conclusion sur l’induction dorso-ventrale ?', answer: 'Les blastomères végétatifs dorsaux induisent du mésoderme dorsal et les ventraux du mésoderme ventral.', },
{ question: 'Quel phénotype caractérise un embryon ventralisé ?', answer: 'Tube digestif isolé, absence de pigmentation, absence d’yeux.', },
{ question: 'Quel phénotype caractérise un embryon dorsalisé ?', answer: 'Structures neurales, yeux, pigmentation, peu de tube digestif.', },
{ question: 'Quelle est la stratégie d’identification des molécules inductrices ?', answer: 'Analyse des protéines sécrétées, banques d’ADNc, expression et test des protéines candidates.', },
{ question: 'Comment teste-t-on une molécule candidate in vitro ?', answer: 'En ajoutant la molécule à des calottes animales mises en culture.', },
{ question: 'Quels facteurs testés induisent du mésoderme ?', answer: 'FGF, Vg1, Activine.', },
{ question: 'Quelle est la nature de Vg1 ?', answer: 'Un TGF-β maternel localisé dans l’hémisphère végétatif.', },
{ question: 'Quel est l’effet dose-dépendant de Vg1 ?', answer: 'Faible dose : mésoderme ; forte dose : mésoderme dorsal.', },
{ question: 'Quelle est la nature d’Activine ?', answer: 'Un facteur zygotique membre des TGF-β.', },
{ question: 'Quel est l’effet d’une forte dose d’Activine ?', answer: 'Induction de mésoderme dorsal (chorde).', },
{ question: 'Quel est l’effet d’une faible dose d’Activine ?', answer: 'Induction de mésoderme ventral (cellules sanguines).', },
{ question: 'Quelle voie de signalisation activent les FGF ?', answer: 'La voie Raf-Mek-MAPK.', },
{ question: 'Que provoque l’expression d’un récepteur FGF tronqué ?', answer: 'Un défaut de mésoderme intermédiaire/ventral et absence de queue.', },
{ question: 'Quelle voie activent les TGF-β ?', answer: 'La voie des SMAD.', },
{ question: 'Quelle méthode permet de visualiser l’ARNm Vg1 ?', answer: 'Hybridation in situ avec sonde anti-sens marquée.', },
{ question: 'Quel est le principe des expériences de restauration in vivo ?', answer: 'Injecter des ARNm candidats dans des embryons irradiés pour tester leur capacité à restaurer l’axe dorsal.', },
{ question: 'Pourquoi irradie-t-on les œufs aux UV ?', answer: 'Pour bloquer la rotation corticale et empêcher l’induction du mésoderme dorsal.', },
{ question: 'Quel est le résultat du test de restauration pour Vg1 ?', answer: 'Vg1 ne restaure pas l’axe dorso-ventral.', },
{ question: 'Quel est le résultat du test de restauration pour Activine ?', answer: 'Activine permet une restauration partielle de l’axe dorso-ventral.', },
{ question: 'Quel est le principe des morpholinos dans les expériences de perte de fonction ?', answer: 'Ils empêchent la traduction de l’ARNm par encombrement stérique sans le dégrader.', },
{ question: 'Quel est le principe des oligonucléotides antisens ?', answer: 'Ils empêchent la traduction de l’ARNm en provoquant sa dégradation.', },
{ question: 'Quel est le principe des ARN interférents ?', answer: 'Ils empêchent la traduction de l’ARNm.', },
{ question: 'Quel est l’objectif d’une stratégie de dominant négatif ?', answer: 'Inhiber la fonction d’une protéine en surexprimant une forme mutante de cette protéine.', },
{ question: 'Quel est l’effet de l’ARNm codant un récepteur FGF tronqué ?', answer: 'Développement anormal avec absence de queue.', },
{ question: 'Que révèle l’absence de queue après blocage de la voie FGF ?', answer: 'Les FGFs sont nécessaires à l’induction des mésodermes intermédiaire et ventral.', },
{ question: 'Quel est le principe des expériences de perte de fonction pour tester un inducteur ?', answer: 'Utilisation d’oligonucléotides antisens complémentaires de l’ARNm endogène.', },
{ question: 'Quel est le contrôle dans les expériences antisens ?', answer: 'Injection d’oligonucléotides antisens avec de l’ARNm codant la protéine candidate.', },
{ question: 'Quel phénotype indique la perte d’un inducteur du mésoderme dorsal ?', answer: 'Un embryon ventralisé.', },
{ question: 'Que provoque un dominant négatif du récepteur FGF ?', answer: 'Perte des muscles et des mésodermes intermédiaire et ventral.', },
{ question: 'Que provoque un dominant négatif du récepteur de l’activine ?', answer: 'Absence de mésoderme.', },
{ question: 'Quel est l’effet de l’injection d’oligonucléotides antisens contre la β-caténine ?', answer: 'Obtention d’embryons ventralisés sans structures dorsales.', },
{ question: 'Quelles molécules sont nécessaires à l’induction du mésoderme ?', answer: 'FGF, activine et β-caténine.', },
{ question: 'Que se passe-t-il en absence de ligand Wnt ?', answer: 'GSK3β est active et la β-caténine est dégradée.', },
{ question: 'Que se passe-t-il en présence de ligand Wnt ?', answer: 'Inhibition de GSK3β et stabilisation de la β-caténine qui va au noyau.', },
{ question: 'Quel est le principe du gain de fonction ectopique ?', answer: 'Injecter un ARNm codant la protéine d’intérêt dans un blastomère ventral.', },
{ question: 'Que provoque un gain de fonction dorsal ectopique ?', answer: 'Apparition de structures dorsales ectopiques et embryon siamois.', },
{ question: 'Quel est l’effet de l’injection ventro-végétative d’ARNm Wnt8 ou β-caténine ?', answer: 'Formation d’un embryon siamois avec deux axes.', },
{ question: 'Quel est le résultat du gain de fonction de Vg1 dans les blastomères ventraux ?', answer: 'Pas d’induction d’un second axe.', },
{ question: 'Quel est l’effet du gain de fonction de Nodal à faible dose ?', answer: 'Induction ventrale.', },
{ question: 'Quel est l’effet du gain de fonction de Nodal à forte dose ?', answer: 'Induction dorsale.', },
{ question: 'Quel est l’effet d’un gain de fonction de β-caténine ?', answer: 'Induction d’un second axe.', },
{ question: 'Quel est l’effet d’un gain de fonction de siamois ?', answer: 'Induction d’un second axe.', },
{ question: 'FGF est-il suffisant pour induire le mésoderme ?', answer: 'Oui, les FGF sont suffisants pour l’induction mésodermique.', },
{ question: 'FGF est-il nécessaire pour les structures postérieures ?', answer: 'Oui, il est nécessaire à leur développement.', },
{ question: 'Vg1 est-il suffisant pour induire le mésoderme in vivo ?', answer: 'Non, Vg1 seul n’est pas suffisant.', },
{ question: 'Activine est-elle nécessaire à l’induction du mésoderme ?', answer: 'Oui, mais elle nécessite d’autres facteurs pour l’axe dorso-ventral.', },
{ question: 'La β-caténine est-elle suffisante pour induire le mésoderme et un second axe ?', answer: 'Oui, elle est nécessaire et suffisante.', },
{ question: 'Siamois est-il suffisant pour induire un second axe ?', answer: 'Oui.', },
{ question: 'Quel matériel génétique l’embryon utilise-t-il très tôt ?', answer: 'Les ARNm maternels stockés dans l’ovocyte.', },
{ question: 'Quand commence l’activation du génome zygotique ?', answer: 'À la transition blastuléenne après 10-12 divisions.', },
{ question: 'Quels ARNm maternels sont localisés au cortex végétatif ?', answer: 'Vg1, VegT, Wnt11 et Dsh.', },
{ question: 'Quel est le rôle de la rotation corticale sur les déterminants dorsaux ?', answer: 'Elle relocalise Dsh et Wnt11 vers le croissant gris.', },
{ question: 'Quelle est l’origine de l’identité dorsale ?', answer: 'La relocalisation des déterminants maternels par la rotation corticale.', },
{ question: 'Où la β-caténine est-elle présente au stade blastula ?', answer: 'Dans les noyaux des blastomères dorsaux.', },
{ question: 'Quels déterminants contiennent les blastomères végétatifs ?', answer: 'Vg1 et VegT.', },
{ question: 'Quelles protéines sont combinées dans les blastomères dorso-végétatifs ?', answer: 'Vg1, VegT et β-caténine.', },
{ question: 'Quelle protéine est produite grâce à la combinaison Vg1 + VegT + β-caténine ?', answer: 'Nodal.', },
{ question: 'Quel est le rôle de Nodal ?', answer: 'Induire le mésoderme selon un gradient dorso-ventral.', },
{ question: 'Qu’est-ce qu’un morphogène ?', answer: 'Une substance soluble diffusant en gradient et induisant des réponses dépendantes de seuils.', },
{ question: 'Quel concept est illustré par le « French Flag » ?', answer: 'Différenciations différentes selon la concentration du morphogène.', },
{ question: 'Comment se forme un gradient morphogénique ?', answer: 'Diffusion depuis une source localisée et dégradation progressive.', },
{ question: 'Qu’est-ce que le centre de Nieuwkoop ?', answer: 'Un centre organisateur composé de blastomères dorso-végétatifs.', },
{ question: 'À quel feuillet appartiennent les blastomères du centre de Nieuwkoop ?', answer: 'À l’endoderme.', },
{ question: 'Quel est le rôle du centre de Nieuwkoop ?', answer: 'Induire le mésoderme dorsal et initier un axe dorsal.', },
{ question: 'Quel gène est un marqueur du centre de Nieuwkoop ?', answer: 'Siamois.', },
{ question: 'Que provoque une greffe du centre de Nieuwkoop dans la région ventrale ?', answer: 'Formation d’une nouvelle face dorsale.', },
{ question: 'Quel événement initie la gastrulation ?', answer: 'Apparition de l’encoche blastoporale.', },
{ question: 'Quelles cellules changent de morphologie au début de la gastrulation ?', answer: 'Les cellules dorso-végétatives D1.', },
{ question: 'Quelle morphologie adoptent les cellules D1 ?', answer: 'Une forme en bouteille.', },
{ question: 'Quelle structure résulte du changement de morphologie des cellules D1 ?', answer: 'L’encoche du blastopore.', },
