{ question: 'Comment sont organisés les feuillets embryonnaires à la fin du stade blastula ?', answer: 'Ectoderme au pôle animal, mésoderme dans la zone marginale, endoderme au pôle végétatif.', },
{ question: 'Comment sont organisés les feuillets embryonnaires après la gastrulation ?', answer: 'Organisation concentrique : ectoderme en surface, mésoderme en couche intermédiaire, endoderme au centre.', },
{ question: 'Quelle structure mésodermique occupe le centre après gastrulation ?', answer: 'Le mésoderme axial, notochorde ou chorde.', },
{ question: 'Quelle structure dérive de l’endoderme après gastrulation ?', answer: 'Le système digestif.', },
{ question: 'Par quoi débute la gastrulation chez le xénope ?', answer: 'Par une petite dépression au niveau des blastomères dorsaux végétatifs formant les cellules en bouteille.', },
{ question: 'Quels facteurs conduisent à la formation des cellules en bouteille ?', answer: 'La combinaison β-caténine, Vg1 et VegT induisant de fortes concentrations de Nodal.', },
{ question: 'Quel mécanisme cellulaire forme les cellules en bouteille ?', answer: 'Contraction des faisceaux d’actine et élongation des microtubules selon l’axe apico-basal.', },
{ question: 'Quel événement marque l’initiation de la gastrulation ?', answer: 'L’apparition de l’encoche du blastopore.', },
{ question: 'Quelle est l’évolution de la forme du blastopore durant la gastrulation ?', answer: 'Anse de panier, fer à cheval, bouchon vitellin, fente blastoporale.', },
{ question: 'Que représente la fente blastoporale ?', answer: 'La future région postérieure de l’embryon, futur anus.', },
{ question: 'Quel était l’objectif des marques colorées de Vogt ?', answer: 'Étudier les mouvements tissulaires durant la gastrulation.', },
{ question: 'Quel mouvement est mis en évidence par l’extension des marques 1 et 2 ?', answer: 'L’épibolie.', },
{ question: 'Quel mouvement est mis en évidence par la disparition de la marque 5 ?', answer: 'L’invagination.', },
{ question: 'Quels mouvements sont observés pour les marques 3, 4, 8 et 9 ?', answer: 'L’extension-convergence.', },
{ question: 'Quel mouvement explique la disparition des marques 6 et 7 ?', answer: 'L’internalisation de l’endoderme.', },
{ question: 'Quels axes apparaissent après les mouvements de gastrulation ?', answer: 'Axe antéro-postérieur et axe gauche-droite.', },
{ question: 'Quelle cavité remplace le blastocœle en fin de gastrulation ?', answer: 'L’archentéron.', },
{ question: 'Quel est l’effet du centre de Nieuwkoop sur les cellules marginales dorsales ?', answer: 'Induction en mésoderme dorsal.', },
{ question: 'Quel mouvement initient les cellules en bouteille ?', answer: 'Le mouvement d’invagination.', },
{ question: 'Quel est le premier mésoderme à s’invaginer ?', answer: 'Le mésoderme céphalique.', },
{ question: 'Quelles cellules mésodermiques s’invaginent après le mésoderme céphalique ?', answer: 'Les cellules du mésoderme axial qui formeront la chorde.', },
{ question: 'Quel composé de la matrice extracellulaire permet la migration des cellules du mésoderme ?', answer: 'La fibronectine.', },
{ question: 'Quelles intégrines interagissent avec la fibronectine ?', answer: 'Les intégrines des cellules mésodermiques.', },
{ question: 'Que montrent les expériences de migration sur différents substrats ?', answer: 'Les cellules ne migrent pas sur plastique ou collagène IV, mais migrent sur fibronectine ou laminine.', },
{ question: 'Que montre la greffe de matrice extracellulaire à l’extérieur de l’embryon ?', answer: 'Les cellules évitent les zones sans matrice, montrant son rôle adhésif.', },
{ question: 'Quelles sont les étapes du mouvement d’épibolie ?', answer: 'Intercalation radiaire, mitoses, aplatissement des cellules externes.', },
{ question: 'Quelle perturbation produit l’injection d’anticorps anti-fibronectine ?', answer: 'Exogastrula avec blastopore circulaire, absence d’invagination et hémisphère animal plissé.', },
{ question: 'Pourquoi une exogastrula se forme-t-elle après perte de fonction fibronectine ?', answer: 'Car la migration mésodermique et l’épibolie ne peuvent pas se dérouler.', },
{ question: 'Que permet l’intercalation médio-latérale des cellules du mésoderme dorsal ?', answer: 'La formation et l’allongement de la chorde.', },
{ question: 'Quel est le rôle de la chorde durant le développement ?', answer: 'Centre organisateur pour l’induction neurale.', },
{ question: 'Quel est le rôle de Wnt11 dans la gastrulation ?', answer: 'Nécessaire à l’extension-convergence et à l’allongement de l’axe antéro-postérieur.', },
{ question: 'Quelles anomalies provoque une perte de fonction Wnt11 ?', answer: 'Défaut d’allongement AP et défaut d’extension-convergence.', },
{ question: 'À quelle voie appartient Wnt11 ?', answer: 'La voie Wnt/PCP de polarité planaire.', },
{ question: 'Quel mouvement est sous contrôle de la voie Wnt/PCP ?', answer: 'Le mouvement d’extension-convergence.', },
{ question: 'Qu’initient les cellules en bouteille dans l’endoderme dorso-végétatif ?', answer: 'L’invagination des cellules du mésoderme.', },
{ question: 'Comment migrent les cellules marginales sur le toit du blastocœle ?', answer: 'Grâce à leur interaction avec la fibronectine.', },
{ question: 'Quel ligand de la voie Wnt contrôle l’extension-convergence ?', answer: 'Wnt11.', },
{ question: 'Quel mécanisme permet l’épibolie des cellules ectodermiques ?', answer: 'Aplatissement, intercalation radiaire et mitoses.', },
{ question: 'Quels mouvements nécessitent la matrice extracellulaire ?', answer: 'Migration mésodermique et épibolie ectodermique.', },
{ question: 'Qu’indique le stade bouchon vitellin en fin de gastrulation ?', answer: 'Disparition des pôles PA-PV, mise en place de l’axe AP, archentéron formé.', },
{ question: 'Quelle est la position finale de l’ectoderme en fin de gastrulation ?', answer: 'Il recouvre toute la surface de l’embryon.', },
{ question: 'Quel est le devenir du blastocœle en fin de gastrulation ?', answer: 'Il disparaît et est remplacé par l’archentéron.', },
