{ question: 'Quels sont les deux modes de spécification cellulaire ?', answer: 'La division cellulaire asymétrique et la communication cellulaire par induction.', },
{ question: 'Qu’est-ce qu’une division cellulaire asymétrique ?', answer: 'Une division donnant deux cellules filles avec des destins différents car héritant de déterminants distincts.', },
{ question: 'Qu’est-ce que l’induction cellulaire ?', answer: 'Une cellule inductrice émet un signal soluble reçu par des cellules compétentes qui adoptent un destin différent selon la concentration du signal.', },
{ question: 'Quel est le rôle de la communication cellulaire dans le développement ?', answer: 'C’est le mode de spécification cellulaire le plus courant aux stades précoces.', },
{ question: 'Que provoque la liaison d’un ligand inducteur à son récepteur ?', answer: 'Une cascade moléculaire conduisant à une différenciation cellulaire.', },
{ question: 'Que signifie qu’une induction inhibe la voie par défaut ?', answer: 'La cellule abandonne la voie de différenciation par défaut pour adopter une voie induite.', },
{ question: 'Quels comportements cellulaires sont observés au cours du développement ?', answer: 'Prolifération, migration, croissance, différenciation et apoptose.', },
{ question: 'Quel exemple illustre l’apoptose embryonnaire ?', answer: 'La formation des espaces interdigitaux des mains.', },
{ question: 'Quel était l’objectif de l’expérience de Spemann et Mangold (1924) ?', answer: 'Mettre en évidence une communication entre cellules embryonnaires : l’induction embryonnaire.', },
{ question: 'Quel marqueur ont utilisé Spemann et Mangold ?', answer: 'La pigmentation naturelle de deux espèces d’amphibiens.', },
{ question: 'Quel était le protocole de Spemann et Mangold ?', answer: 'Greffe de la lèvre dorsale du blastopore dans la région ventrale d’un embryon non pigmenté.', },
{ question: 'Quel fut le résultat global de la greffe de la lèvre dorsale ?', answer: 'Formation d’un embryon siamois avec deux axes antéro-postérieurs.', },
{ question: 'Quelles structures dérivent du greffon pigmenté dans l’expérience de Spemann ?', answer: 'Chorde, plancher du tube neural et portion ventrale des somites.', },
{ question: 'Quelles structures dérivent de l’hôte dans l’axe induit ?', answer: 'Tube neural et somites.', },
{ question: 'Que deviennent les cellules de la lèvre dorsale du blastopore ?', answer: 'Elles se différencient en notochorde.', },
{ question: 'Quel rôle joue la notochorde dans l’embryon ?', answer: 'Elle induit et permet la différenciation neurale.', },
{ question: 'Que montre l’apparition d’un deuxième blastopore après greffe ?', answer: 'Une duplication complète des structures dorsales.', },
{ question: 'Que contient la lèvre dorsale d’une jeune gastrula selon la carte de Vogt ?', answer: 'Les précurseurs du mésoderme dorsal : mésoderme préchordal et chorde.', },
{ question: 'Qu’observe-t-on en greffant la lèvre dorsale dans la région ventrale ?', answer: 'Mise en place d’un second site d’invagination et induction d’une seconde plaque neurale.', },
{ question: 'Quel est le résultat final des greffes de lèvre dorsale ?', answer: 'Un embryon double et siamois.', },
{ question: 'Quelle est la première propriété de la lèvre dorsale du blastopore ?', answer: 'Former une structure axiale : la chorde.', },
{ question: 'Quelle est la deuxième propriété de la lèvre dorsale du blastopore ?', answer: 'Recruter les cellules environnantes pour former tube neural et somites.', },
{ question: 'Quelle est la troisième propriété de la lèvre dorsale du blastopore ?', answer: 'Diriger la mise en place du tube neural sans participer aux structures neurales.', },
{ question: 'Quel nom porte la lèvre dorsale du blastopore en tant que centre inducteur ?', answer: 'Le centre organisateur de Spemann.', },
{ question: 'Quelles structures les cellules du centre de Spemann peuvent-elles former ?', answer: 'Une chorde et des somites ectopiques.', },
{ question: 'Quel est le rôle du centre de Spemann sur le mésoderme ?', answer: 'Il le dorsalise.', },
{ question: 'Que permet le centre de Spemann à l’ectoderme sus-jacent ?', answer: 'S’engager dans la différenciation neurale.', },
{ question: 'Que permet le centre de Spemann pour la régionalisation ?', answer: 'La régionalisation antéro-postérieure du tube neural.', },
{ question: 'Quel fut l’objectif des expériences d’Holtfreter (1936) ?', answer: 'Tester si les propriétés inductrices de la lèvre dorsale changent selon l’âge de la gastrula.', },
{ question: 'Quel est le résultat d’une greffe de lèvre dorsale d’une jeune gastrula ?', answer: 'Induction de structures neurales antérieures et apparition de deux têtes.', },
{ question: 'Quel est le résultat d’une greffe de lèvre dorsale d’une gastrula âgée ?', answer: 'Induction de structures neurales troncales et postérieures.', },
{ question: 'Que conclut-on des greffes de Holtfreter ?', answer: 'Les propriétés inductrices de la lèvre dorsale changent au cours du temps.', },
{ question: 'À quel moment le tissu neural est-il spécifié ?', answer: 'Au cours de la gastrulation.', },
{ question: 'Que montre une greffe ectopique homochronique au stade jeune gastrula ?', answer: 'Le greffon adopte le destin du receveur : il n’est pas déterminé.', },
{ question: 'Que montre une greffe ectopique homochronique au stade gastrula âgée ?', answer: 'Le greffon forme une plaque neurale ectopique : il est déterminé.', },
{ question: 'Quelles molécules induisent le tissu neural selon Spemann ?', answer: 'Des molécules sécrétées par la lèvre dorsale du blastopore.', },
{ question: 'Quel est le principe du modèle d’Activation-Transformation ?', answer: 'Une étape d’activation neurale antérieure puis une transformation en structures neurales postérieures.', },
{ question: 'Quels signaux agissent lors de l’étape d’activation ?', answer: 'Des signaux verticaux issus du centre organisateur de Spemann.', },
{ question: 'Quel est le résultat des signaux d’activation ?', answer: 'Acquisition d’une identité neurale antérieure.', },
{ question: 'Quels signaux agissent lors de l’étape de transformation ?', answer: 'Des signaux postériorisants planaires provenant du mésoderme.', },
{ question: 'Quel acteur moléculaire a été identifié dans les expériences de Noggin ?', answer: 'Noggin, inhibiteur compétitif de la voie BMP.', },
{ question: 'Quel est l’effet de Noggin sur la voie BMP ?', answer: 'Il se fixe au récepteur BMP sans activer la transduction.', },
{ question: 'Quel est l’effet de Noggin sur la calotte animale ?', answer: 'Induction de différenciation neurale.', },
{ question: 'Qu’indiquent Noggin et Chordin sur le plan fonctionnel ?', answer: 'Ce sont des protéines sécrétées dorsalisantes capables d’induire des structures neurales antérieures.', },
{ question: 'Où s’exprime Chordin au cours du développement ?', answer: 'Dans la lèvre dorsale du blastopore puis dans le mésoderme axial.', },
{ question: 'Comment visualise-t-on l’expression de Chordin ou Noggin ?', answer: 'Par hybridation in situ.', },
{ question: 'Quel est le but de la dissociation des cellules de la calotte animale dans l’étude du rôle de Noggin et Chordin ?', answer: 'Elle permet d’inhiber l’activité des cadhérines dépendantes du calcium et d’observer la différenciation par défaut en neurones.', },
{ question: 'Quel est le résultat de l’expérience 1 sans dissociation des cellules de la calotte animale ?', answer: 'Les cellules se différencient en cellules épidermiques.', },
{ question: 'Quel est le résultat de l’expérience 2 avec dissociation des cellules ?', answer: 'Les cellules se différencient en neurones.', },
{ question: 'Quel est le résultat de l’expérience 3 avec dissociation et ajout de BMP ?', answer: 'Les cellules se différencient en cellules épidermiques.', },
{ question: 'Quel est le résultat de l’expérience 4 sans dissociation mais avec ajout de Noggin et Chordin ?', answer: 'Différenciation en cellules épidermiques et en neurones.', },
{ question: 'Quelle est la fonction de BMP dans la calotte animale ?', answer: 'BMP maintient l’identité épidermique et inhibe la différenciation neurale.', },
{ question: 'Comment Noggin et Chordin agissent-ils dans l’induction neurale ?', answer: 'Ils inhibent la voie BMP et permettent la différenciation en neurones.', },
{ question: 'Quel est l’effet d’une surexpression de BMP in vivo ?', answer: 'Obtention d’un embryon totalement ventralisé sans neurones ni SNC.', },
{ question: 'Que démontre la surexpression de BMP sur les structures neurales ?', answer: 'BMP suffit à inhiber la formation des structures neurales in vivo.', },
{ question: 'Quel est l’effet d’une injection ventrale d’ARNm Noggin ou Chordin au stade 32 cellules ?', answer: 'Formation d’un second axe incomplet avec structures neurales réduites.', },
{ question: 'Pourquoi l’axe induit par Noggin ou Chordin est-il incomplet ?', answer: 'Car Noggin et Chordin ne suffisent pas à induire toutes les structures neurales antéro-postérieures.', },
{ question: 'Où s’exprime la protéine Frizbee au début de la gastrulation ?', answer: 'Dans les cellules de la lèvre dorsale du blastopore puis dans le mésoderme préchordal.', },
{ question: 'Quelle est la nature de la protéine Frizbee ?', answer: 'Une forme soluble du récepteur Frizzled, inhibiteur compétitif de Wnt8.', },
{ question: 'Pourquoi Frizbee inhibe-t-elle Wnt8 ?', answer: 'Parce que la voie Wnt8 est impliquée dans la différenciation du mésoderme ventral.', },
{ question: 'Quel est le résultat de l’injection de chordin et noggin au stade 32 cellules ?', answer: 'Induction d’un second axe incomplet sans régionalisation antéro-postérieure.', },
{ question: 'Quel est le résultat de l’injection de chordin et frizbee ?', answer: 'Induction d’un deuxième axe complet avec structures neurales antérieures.', },
{ question: 'Quel est l’effet d’une injection zygotique de Noggin et Frizbee ?', answer: 'Une dorsalisation des embryons.', },
{ question: 'Où l’ARNm Cerberus est-il exprimé ?', answer: 'Dans l’endoderme pharyngien lors de la gastrulation.', },
{ question: 'Quels signaux Cerberus inhibe-t-il ?', answer: 'BMP, Nodal et Wnt8.', },
{ question: 'Quel est le résultat d’une injection ventrale d’ARNm Cerberus ?', answer: 'Obtention d’un embryon avec une tête supplémentaire sans chorde supplémentaire.', },
{ question: 'Quel est le résultat d’une irradiation végétative suivie d’une injection de Cerberus ?', answer: 'Induction de structures neurales antérieures sans axe ni chorde.', },
{ question: 'Quel est le rôle principal de Cerberus ?', answer: 'Induction de structures neurales antérieures.', },
{ question: 'Quels sont les inhibiteurs de BMP impliqués dans les signaux verticaux ?', answer: 'Chordin, Noggin et Follistatin.', },
{ question: 'Quel est le rôle des inhibiteurs de BMP dans l’induction neurale ?', answer: 'Rendre le tissu ectodermique permissif à une différenciation neurale antérieure.', },
{ question: 'Quels inhibiteurs de Wnt sont impliqués dans l’identité antérieure ?', answer: 'Frizbee et Cerberus.', },
{ question: 'Quelle est la source de Cerberus ?', answer: 'L’endoderme pharyngien.', },
{ question: 'Quel est le rôle général des signaux planaires ?', answer: 'Déterminer les structures neurales postérieures.', },
{ question: 'Quel est le but des “sandwiches de Keller” ?', answer: 'Étudier les signaux planaires en absence de signaux verticaux.', },
{ question: 'Quel est le comportement des cellules du mésoderme dorsal dans les sandwiches de Keller ?', answer: 'Elles deviennent allongées et réalisent des mouvements d’extension convergente.', },
{ question: 'Quel est l’intérêt des gènes Engrailed, Krox20 et HoxB9 dans ces expériences ?', answer: 'Ils marquent séquentiellement les régions antéro-postérieures du tissu neural.', },
{ question: 'Que montrent les sandwiches de Keller sur la régionalisation ?', answer: 'Les signaux planaires suffisent à transmettre une information antéro-postérieure.', },
{ question: 'Quel est l’effet d’une augmentation de l’acide rétinoïque ?', answer: 'Induction exclusive de structures postérieures avec perte de l’encéphale et des yeux.', },
{ question: 'Quel est le rôle de l’acide rétinoïque dans l’induction neurale ?', answer: 'Il est suffisant pour postérioriser l’embryon.', },
{ question: 'Quel est le résultat d’une perte de fonction FGF par récepteur tronqué ?', answer: 'Développement uniquement d’une tête, sans structures postérieures.', },
{ question: 'Quel est le rôle de FGF dans l’induction neurale ?', answer: 'FGF est nécessaire à la postériorisation.', },
{ question: 'Quel est le rôle des signaux verticaux dans l’induction neurale ?', answer: 'Inhiber BMP pour permettre l’activation du neuro-ectoderme.', },
{ question: 'Quel est le rôle des signaux planaires dans l’induction neurale ?', answer: 'Postérioriser et organiser l’axe antéro-postérieur.', },
{ question: 'Quels morphogènes postériorisants sont exprimés à la lèvre dorsale ?', answer: 'Acide rétinoïque, Wnt et FGF.', },
{ question: 'Quel gradient est nécessaire pour l’organisation du système nerveux ?', answer: 'Un double gradient vertical et planaire.', },
{ question: 'Que devient l’ectoderme sous inhibition de BMP ?', answer: 'Le neuro-ectoderme ou plaque neurale.', },
{ question: 'Quelles structures sont induites par les inhibiteurs de Wnt dans la région antérieure ?', answer: 'L’encéphale, les yeux et la tête.', },
{ question: 'Quels signaux induisent la moelle épinière postérieure ?', answer: 'FGF, Wnt et acide rétinoïque.', },
{ question: 'Quelle structure sécrète Cerberus après la gastrulation ?', answer: 'L’endoderme pharyngien.', },
{ question: 'Quel est le rôle postérieur de Noggin, Chordin et Frizbee ?', answer: 'La mise en place des régions du cerveau moyen et postérieur.', },
{ question: 'Quel est le rôle de FGF, Wnt et AR après gastrulation ?', answer: 'La différenciation de la moelle épinière jusqu’au niveau sacro-coccygien.', },
{ question: 'Quelle est la conséquence d’une greffe ectopique du nœud de Hensen chez le poulet ?', answer: 'Formation d’un deuxième axe complet.', },
{ question: 'Quel est l’équivalent aviaire du centre de Spemann ?', answer: 'Le nœud de Hensen.', },
