{ question: 'Quel est le rôle du développement humain ?', answer: 'Produire un organisme complet avec ses annexes à partir d’une cellule totipotente.', },
{ question: 'Comment sont les premières divisions du développement humain ?', answer: 'Elles sont holoblastiques, lentes et rotationnelles.', },
{ question: 'À quel stade a lieu la compaction au début du développement humain ?', answer: 'Au stade 8 cellules.', },
{ question: 'Quelles transformations caractérisent la compaction ?', answer: 'Les cellules rétrécissent, s’aplatissent et établissent des jonctions cellulaires.', },
{ question: 'Quelle première différenciation apparaît au stade 16 blastomères ?', answer: 'La distinction entre la masse cellulaire interne et les cellules externes du trophectoderme.', },
{ question: 'Que devient la masse cellulaire interne ?', answer: 'Elle donne l’embryon et les annexes extra-embryonnaires.', },
{ question: 'Que devient le trophectoderme ?', answer: 'Il constitue l’enveloppe externe du blastocyste et participera aux annexes extra-embryonnaires.', },
{ question: 'Quel est le nom de la couche externe du blastocyste en pré-implantation ?', answer: 'Le trophectoderme.', },
{ question: 'En quoi se transforme le trophectoderme après implantation ?', answer: 'Il devient le trophoblaste.', },
{ question: 'Quels sont les deux types cellulaires issus du trophoblaste ?', answer: 'Le cytotrophoblaste et le syncytiotrophoblaste.', },
{ question: 'Quel tissu sécrète la β-hCG ?', answer: 'Le syncytiotrophoblaste.', },
{ question: 'À quel moment apparaît le trophoblaste ?', answer: 'Après implantation, à partir du jour 7 de développement.', },
{ question: 'Quelle est la fonction principale du trophectoderme ?', answer: 'Permettre l’implantation et protéger la masse cellulaire interne.', },
{ question: 'Quelle est la fonction principale du trophoblaste ?', answer: 'Contribuer à la formation du placenta et assurer les échanges nutritifs et oxygénés.', },
{ question: 'Quel tissu envahit activement la muqueuse utérine ?', answer: 'Le syncytiotrophoblaste.', },
{ question: 'Le trophectoderme peut-il être biopsié ?', answer: 'Oui, pour un diagnostic pré-implantatoire.', },
{ question: 'À qui s’adresse le diagnostic pré-implantatoire selon l’article L2131-4 ?', answer: 'Aux couples présentant une forte probabilité d’enfant atteint d’une maladie génétique grave et incurable.', },
{ question: 'Où se situe l’embryon à la fin de la deuxième semaine ?', answer: 'Dans la paroi utérine.', },
{ question: 'Comment se définit le syncytiotrophoblaste ?', answer: 'Comme un syncytium issu du trophectoderme et formant la couche externe.', },
{ question: 'Que limite intérieurement le syncytiotrophoblaste ?', answer: 'Le cytotrophoblaste.', },
{ question: 'Quelle est l’origine du mésoderme extra-embryonnaire ?', answer: 'La masse cellulaire interne.', },
{ question: 'Quel est le rôle du mésoderme extra-embryonnaire ?', answer: 'Relier le chorion à la sphère embryonnaire via le pédicule embryonnaire.', },
{ question: 'De quoi est composé le chorion ?', answer: 'Du syncytiotrophoblaste, du cytotrophoblaste et du mésoderme extra-embryonnaire.', },
{ question: 'Qu’est-ce que le cœlome extra-embryonnaire ?', answer: 'Une cavité située entre le mésoderme extra-embryonnaire et le cytotrophoblaste.', },
{ question: 'Quelles structures forment la sphère extra-embryonnaire ?', answer: 'Le chorion et le cœlome extra-embryonnaire.', },
{ question: 'Quel est le diamètre de la sphère extra-embryonnaire ?', answer: '2,5 mm.', },
{ question: 'Quelles structures participent à la formation des annexes extra-embryonnaires ?', answer: 'Le cytotrophoblaste, le syncytiotrophoblaste, l’amnios, la vésicule vitelline secondaire et le mésoderme extra-embryonnaire.', },
{ question: 'Par quoi est délimitée la cavité amniotique ?', answer: 'Par l’épithélium amniotique et le disque embryonnaire.', },
{ question: 'De quoi est constitué le disque embryonnaire à la fin de la deuxième semaine ?', answer: 'De l’épiblaste et de l’endoderme viscéral.', },
{ question: 'Quelle est la taille de l’embryon à la fin de la deuxième semaine ?', answer: 'Environ 200 µm.', },
{ question: 'Quels sont les deux feuillets du disque embryonnaire didermique ?', answer: 'L’épiblaste et l’endoderme viscéral.', },
{ question: 'Comment est définie la vésicule vitelline secondaire ?', answer: 'Par l’endoderme pariétal et l’endoderme viscéral.', },
{ question: 'Quel est le rôle de l’épiblaste ?', answer: 'C’est l’origine de tous les tissus embryonnaires.', },
{ question: 'Quelles sont les questions posées pour la suite du développement ?', answer: 'Comment passer d’un disque didermique à trois feuillets : ectoderme, mésoderme, endoderme ?', },
