{ question: 'Qu’est-ce que la neurulation dans l’espèce humaine ?', answer: 'Une série de transformations de la quatrième semaine permettant à la plaque neurale, située dans l’ectoderme, de se transformer en tube neural.', },
{ question: 'Que devient la plaque neurale à l’issue de la neurulation ?', answer: 'Elle s’internalise sous l’ectoderme de surface et prend une position dorsale intermédiaire entre le mésoderme axial et les somites.', },
{ question: 'Quel est le rôle de la neurulation primaire ?', answer: 'Former le tube neural rostral, le cerveau et la moelle épinière au niveau des vertèbres cervicales et thoraciques hautes.', },
{ question: 'Quelle est la temporalité de la neurulation primaire ?', answer: 'Entre les jours 22 et 26 du développement.', },
{ question: 'Quels sont les deux temps de la neurulation primaire ?', answer: 'Le façonnage (shaping) et la courbure (bending).', },
{ question: 'Quelles modifications cellulaires caractérisent le façonnage ?', answer: 'Les cellules nerveuses présomptives deviennent prismatiques et les cellules latérales deviennent pavimenteuses.', },
{ question: 'Quelles modifications géométriques accompagne le façonnage ?', answer: 'Épaississement dorso-ventral, rétrécissement médio-latéral et extension crânio-caudale de la plaque neurale.', },
{ question: 'Que représente la partie antérieure de la plaque neurale ?', answer: 'Le futur cerveau.', },
{ question: 'Que représente la portion effilée de la plaque neurale ?', answer: 'La future moelle épinière.', },
{ question: 'Quelle conséquence mécanique entraîne l’élongation de la plaque neurale ?', answer: 'La régression de la ligne primitive repoussée vers l’arrière.', },
{ question: 'Qu’est-ce que la charnière médiane lors de la neurulation primaire ?', answer: 'La région de la plaque neurale qui se surélève à cause de la déformation cellulaire conique des cellules situées au-dessus de la chorde.', },
{ question: 'Quelles cellules se déforment pour former la charnière médiane ?', answer: 'Des cellules de la plaque neurale perdant leur forme prismatique pour adopter une forme conique tronquée.', },
{ question: 'Comment se forment les charnières latérales ?', answer: 'Après la charnière médiane, grâce à une modification morphologique favorisée par l’ectoderme de surface.', },
{ question: 'Quel est l’effet de la formation des charnières latérales ?', answer: 'Les bourrelets neuraux se rapprochent, entrent en contact et fusionnent pour former le tube neural.', },
{ question: 'Quelle cadhérine est exprimée par les cellules de la plaque neurale ?', answer: 'La N-cadhérine.', },
{ question: 'Quelle cadhérine est exprimée par l’ectoderme de surface ?', answer: 'La E-cadhérine.', },
{ question: 'Pourquoi l’expression différentielle des cadhérines est-elle importante ?', answer: 'Parce qu’elles assurent une adhérence homophilique permettant la fusion correcte des bourrelets neuraux.', },
{ question: 'Qu’assure la mise en place d’une lame basale ?', answer: 'La séparation de l’ectoderme et du mésoderme.', },
{ question: 'Quel marqueur neural est utilisé dans la neurulation expérimentale ?', answer: 'Sox2.', },
{ question: 'Quel marqueur d’ectoderme de surface est utilisé ?', answer: 'E-cadhérine.', },
{ question: 'Quel composant de matrice extracellulaire est visualisé lors de la neurulation ?', answer: 'La fibronectine (FN).', },
{ question: 'Quel est le marqueur de l’ectoderme neural ?', answer: 'La N-cadhérine.', },
{ question: 'Où débute la fusion des bourrelets neuraux ?', answer: 'Au niveau des premiers somites.', },
{ question: 'La fusion des bourrelets est-elle continue ?', answer: 'Non, elle n’est pas concomitante et présente plusieurs zones de jonction.', },
{ question: 'Comment s’appellent les ouvertures temporaires aux extrémités du tube neural ?', answer: 'Le neuropore antérieur et le neuropore postérieur.', },
{ question: 'Que contiennent les neuropores en cours de neurulation ?', answer: 'Ils communiquent avec la cavité amniotique et contiennent du liquide amniotique.', },
{ question: 'Quelle est la fonction du neurocèle une fois les neuropores fermés ?', answer: 'Il devient isolé du liquide amniotique, et ses pressions internes participent à la morphogenèse du prosencéphale.', },
{ question: 'Quand se ferme le neuropore antérieur ?', answer: 'Au 24ème jour de développement.', },
{ question: 'Quand se ferme le neuropore postérieur ?', answer: 'Au 26ème jour de développement.', },
{ question: 'Combien de sites de fermeture du tube neural existent chez la souris ?', answer: 'Trois sites de fermeture.', },
{ question: 'Combien de sites de fermeture du tube neural existent chez l’Homme ?', answer: 'Deux sites de fermeture.', },
{ question: 'Où commence la fermeture du tube neural chez l’embryon murin au site 1 ?', answer: 'À l’interface entre le cerveau postérieur et les premières vertèbres cervicales.', },
{ question: 'Quel est l’effet d’un défaut de fermeture du site 1 ?', answer: 'Il conduit au craniorachischisis.', },
{ question: 'Où apparaît le site 2 de fermeture chez la souris ?', answer: 'À la jonction du cerveau antérieur et du cerveau moyen.', },
{ question: 'Le site 2 de fermeture est-il présent chez l’Homme ?', answer: 'Non, il n’a pas été observé chez l’Homme.', },
{ question: 'Où se situe le site 3 de fermeture du tube neural ?', answer: 'À la limite très rostrale du cerveau antérieur.', },
{ question: 'Quelles anomalies résultent d’un défaut de fermeture des neuropores antérieur et du cerveau postérieur ?', answer: 'Des anencéphalies.', },
{ question: 'Quelle pathologie résulte d’un défaut de fermeture du neuropore postérieur ?', answer: 'Le spina bifida.', },
{ question: 'Quelle est la prévalence des anomalies de fermeture du tube neural selon EUROCAT (2003-2007) ?', answer: '0,51 pour 1 000 naissances et 0,94 pour 1 000 mortinaissances et interruptions de grossesse.', },
{ question: 'Quelle est l’origine générale des anomalies de fermeture du tube neural ?', answer: 'Elles sont multifactorielle : nutritionnels, autres facteurs ou polluants environnementaux.', },
{ question: 'Qu’est-ce que l’anencéphalie ?', answer: 'Une ouverture au niveau de la tête due à un défaut de neurulation primaire.', },
{ question: 'Qu’est-ce que le craniorachischisis ?', answer: 'Une ouverture totale du tube neural.', },
{ question: 'Quelle est la forme la plus bénigne de spina bifida ?', answer: 'Le spina bifida occulta.', },
{ question: 'Comment se caractérise le spina bifida occulta ?', answer: 'Par une brèche dans les vertèbres recouverte par la peau.', },
{ question: 'Quelles sont les deux formes de spina bifida ouvertes (aperta) ?', answer: 'La méningocèle et la myéloméningocèle.', },
{ question: 'Qu’est-ce qu’une méningocèle ?', answer: 'Une protrusion des méninges par une ouverture de la colonne vertébrale.', },
{ question: 'Qu’est-ce qu’une myéloméningocèle ?', answer: 'La protrusion de la moelle épinière et des méninges à travers une ouverture vertébrale.', },
{ question: 'Quelle protéine est impliquée dans certains Neural Tube Defects (NTD) chez l’Homme ?', answer: 'La protéine VANGL.', },
{ question: 'Quel type de protéine est VANGL ?', answer: 'Une protéine à 4 domaines transmembranaires et 2 domaines intracellulaires sans domaine extracellulaire.', },
{ question: 'Quelles conséquences peuvent avoir des mutations dans les domaines transmembranaires de VANGL ?', answer: 'Un mauvais repliement et un mauvais positionnement dans la membrane.', },
{ question: 'Quelles conséquences peuvent avoir des mutations dans les domaines intracellulaires de VANGL ?', answer: 'Perte d’interaction avec les partenaires cytoplasmiques, absence de transduction du signal ou protéine constitutivement active.', },
{ question: 'Quel mutant spontané de souris est utilisé comme modèle du craniorachischisis ?', answer: 'Le mutant Loop-Tail.', },
{ question: 'Que montre l’analyse du tube neural du mutant Loop-Tail ?', answer: 'Un élargissement du plancher du tube neural, une élévation des bourrelets et une absence de fermeture du tube neural.', },
{ question: 'Quel mouvement cellulaire est affecté chez le mutant Loop-Tail ?', answer: 'Le mouvement d’intercalation médio-latérale.', },
{ question: 'Quel rôle semble avoir VANGL dans la morphogenèse de l’axe ?', answer: 'VANGL semble nécessaire à l’extension convergente et à l’allongement de l’axe embryonnaire.', },
{ question: 'Quel est l’effet d’une perturbation de la voie Wnt-PCP sur le tube neural ?', answer: 'Des défauts d’intercalation, des défauts d’élongation et des défauts de fermeture du tube neural.', },
{ question: 'Quel est l’effet de l’inhibition de ROCK chez la souris ?', answer: 'Des défauts de fermeture du tube neural, d’élongation et un élargissement du plancher du tube neural.', },
{ question: 'Quel est l’effet de la surexpression d’un ARNm mutant de Dishevelled (Dsh) chez le Xénope ?', answer: 'Un défaut d’allongement, une absence de rapprochement des bourrelets et un défaut de fermeture du tube neural.', },
{ question: 'Quel phénotype présente un mutant Dsh-/- ?', answer: 'Un craniorachischisis.', },
{ question: 'Où Prickle est-il exprimé chez le Poulet ?', answer: 'Dans la NSB, zone de la neurulation jonctionnelle.', },
{ question: 'Quel est l’effet d’une perte de fonction de Prickle chez le Poulet ?', answer: 'Des défauts de fermeture du tube neural de type spina bifida.', },
{ question: 'Quelle zone est sensible pour le spina bifida chez l’Homme ?', answer: 'La zone de neurulation jonctionnelle.', },
{ question: 'Quels mouvements sont impliqués dans le développement normal du tube neural ?', answer: 'Les mouvements de convergence/extension du mésoderme axial, du mésoderme paraxial et de la plaque neurale.', },
{ question: 'Qu’induit la convergence-extension au niveau de la plaque neurale ?', answer: 'La formation de la charnière médiane et la fermeture du tube neural.', },
{ question: 'Quelles sont les conséquences d’une perturbation de la voie Wnt-PCP sur le mésoderme ?', answer: 'Une chorde élargie, une charnière médiane élargie et une fusion impossible des bourrelets.', },
{ question: 'Quelles sont les conséquences d’une perturbation de la voie Wnt-PCP sur la plaque neurale ?', answer: 'Absence d’allongement rostro-caudal, charnière élargie et fusion impossible des bourrelets.', },
{ question: 'Quels sont les axes de polarisation du tube neural ?', answer: 'L’axe dorso-ventral et l’axe rostro-caudal.', },
{ question: 'Quels morphogènes polarisent le tube neural dans l’axe dorso-ventral ?', answer: 'BMP dorsalement et SHH ventralement.', },
{ question: 'Quelle région du système nerveux est spécifiée par la polarité ventrale ?', answer: 'La région motrice.', },
{ question: 'Quelle région est spécifiée par la polarité dorsale ?', answer: 'La région sensorielle.', },
