{ question: 'Qui a identifié la crête neurale en 1868 ?', answer: 'Wilhelm His, en observant une structure entre l’ectoderme de surface et le tube neural appelée cordon intermédiaire.', },
{ question: 'Qui a identifié les premiers dérivés de la crête neurale en 1893 ?', answer: 'Julia Platt.', },
{ question: 'Quels dérivés de la crête neurale Julia Platt avait-elle mis en évidence ?', answer: 'Des cellules mésenchymateuses différenciées en tissu conjonctif, cartilagineux et osseux dans la région céphalique.', },
{ question: 'Quels travaux ont mis en évidence des cellules migrantes d’origine dorsale dans les arcs branchiaux chez le triton Necturus ?', answer: 'Les travaux de Julia Platt en 1893.', },
{ question: 'Qui a développé la technique caille/poule pour étudier la crête neurale ?', answer: 'Nicole Le Douarin en 1969.', },
{ question: 'Quel type de marquage naturel permet de distinguer les cellules de caille et de poule ?', answer: 'L’hétérochromatine compacte dans les cellules de caille et l’hétérochromatine diffuse dans les cellules de poule.', },
{ question: 'Quels tissus sont en contact avec le territoire présomptif des cellules de la crête neurale après la gastrulation ?', answer: 'Le neurectoderme, l’ectoderme de surface et le mésoderme paraxial.', },
{ question: 'Quelles protéines induisent les cellules de la crête neurale ?', answer: 'Wnt, BMP, acide rétinoïque et FGF.', },
{ question: 'Qu’est-ce que la spécification des cellules de la crête neurale ?', answer: 'L’engagement dans une voie de différenciation.', },
{ question: 'Quels facteurs de transcription sont exprimés lors de la spécification des cellules de la crête neurale ?', answer: 'Snail-2/Slug et ZEB-2.', },
{ question: 'Par quel processus les cellules de la crête neurale s’individualisent-elles ?', answer: 'Par une transition épithélio-mésenchymateuse (TEM).', },
{ question: 'Qu’est-ce que la délamination dans le contexte de la crête neurale ?', answer: 'Le mouvement morphogénétique où des cellules mésenchymateuses se forment à partir d’un épithélium.', },
{ question: 'Quelle molécule doit être réprimée pour permettre la délamination des cellules de la crête neurale ?', answer: 'La N-cadhérine.', },
{ question: 'Quel rôle joue la fibronectine et la laminine dans la migration des cellules de la crête neurale ?', answer: 'Elles servent de support via les intégrines.', },
{ question: 'Quelles structures cellulaires permettent aux cellules de la crête neurale de se déplacer ?', answer: 'Les lamellipodes.', },
{ question: 'Qu’est-ce que le chimiotactisme dans la migration des cellules de la crête neurale ?', answer: 'La direction du déplacement d’une cellule en réponse à une molécule chémoattractante.', },
{ question: 'Quels sont les quatre grands territoires de la crête neurale ?', answer: 'Crête céphalique, crête vagale, crête troncale, crête lombo-sacrée.', },
{ question: 'Quelle méthode permet d’étudier la migration des cellules de la crête neurale ?', answer: 'La technique de greffes caille-poule.', },
{ question: 'Que révèle la greffe homotopique de crête neurale vagale de caille chez la poule ?', answer: 'Les dérivés sont retrouvés dans l’aorte, les arcs branchiaux et le duodénum.', },
{ question: 'Que révèle la greffe homotopique de crête neurale céphalique de caille chez la poule ?', answer: 'Les dérivés sont retrouvés dans la vésicule optique et les arcs branchiaux.', },
{ question: 'Qu’indique une greffe hétérotopique de tube neural troncal en région vagale ?', answer: 'Les cellules de la crête répondent au micro-environnement et sont plastiques.', },
{ question: 'Vers quelles structures migrent les cellules de la crête neurale céphalique ?', answer: 'Vers la tête.', },
{ question: 'Vers quelles structures migrent les cellules de la crête neurale vagale ?', answer: 'Vers le tube digestif et le cœur.', },
{ question: 'Vers quelles structures migrent les cellules de la crête troncale ?', answer: 'Vers le tube digestif, la médullosurrénale, les ganglions spinaux et vertébraux.', },
{ question: 'Vers quelles structures migrent les cellules de la crête lombo-sacrée ?', answer: 'Vers l’intestin, la vessie et les organes génitaux.', },
{ question: 'Quels sont les dérivés principaux de la crête neurale céphalique ?', answer: 'Squelette crânio-facial, odontoblastes, péricytes, derme de la tête, stroma oculaire, ganglions sensitifs et parasympathiques.', },
{ question: 'Quels sont les exemples de neurocristopathies d’origine céphalique ?', answer: 'La fente labio-palatine et le syndrome de Treacher-Collins.', },
{ question: 'Qu’est-ce que la fente labio-palatine ?', answer: 'Une absence de soudure des bourgeons maxillaires entraînant une communication bucco-nasale.', },
{ question: 'Quels troubles fonctionnels peuvent être causés par une fente labio-palatine ?', answer: 'Troubles de succion, déglutition, phonation et préjudice esthétique.', },
{ question: 'À partir de quand peut-on diagnostiquer une fente labio-palatine ?', answer: 'À partir de la 16ème semaine de grossesse.', },
{ question: 'Quel est l’agent causal du syndrome de Treacher-Collins dans 60% des cas ?', answer: 'Une mutation survenue au cours du développement embryonnaire.', },
{ question: 'Quels gènes sont associés au syndrome de Treacher-Collins ?', answer: 'TCOF1, POLR1C et POLR1D.', },
{ question: 'Quel est le principal défaut pigmentaire dans le syndrome de Waardenburg ?', answer: 'Un défaut de migration ou de survie des mélanoblastes.', },
{ question: 'Quels symptômes sont caractéristiques du syndrome de Waardenburg ?', answer: 'Mèche blanche, hypopigmentations, hétérochromie, surdité neurosensorielle.', },
{ question: 'Quels gènes sont impliqués dans le syndrome de Waardenburg ?', answer: 'PAX3, MITF, SOX10, EDNRB, EDN3 et SNAI2.', },
{ question: 'Quels sont les dérivés endocrines issus des cellules de la crête neurale troncale ?', answer: 'Les cellules chromaffines de la médullosurrénale.', },
{ question: 'Quels sont les dérivés du système nerveux périphérique issus de la crête neurale troncale ?', answer: 'Les neurones sensoriels et la glie des ganglions spinaux, les cellules des capsules frontières et les cellules de Schwann.', },
{ question: 'Quelle est la contribution des cellules de la crête neurale lombo-sacrée ?', answer: 'Elles contribuent à la paroi du rectum et aux neurones ganglionnaires du système parasympathique sacré localisés dans la vessie et les organes génitaux.', },
{ question: 'Quel lien existe entre la TEM de la crête neurale et la fibrose ou les métastases cancéreuses ?', answer: 'Fibrose et métastases reposent sur des mécanismes de transition épithélio-mésenchymateuse similaires à ceux des cellules de la crête neurale.', },
{ question: 'Quelles protéines impliquées dans la migration des cellules de la crête neurale sont aussi impliquées dans la migration des cellules cancéreuses ?', answer: 'Les MMP et ADAM.', },
{ question: 'Quels sont les dérivés du neurectoderme ?', answer: 'Cerveau, moelle épinière, crêtes neurales, squelette de la face, ganglions et fibres des nerfs crâniens, cellules pigmentaires, médullosurrénales.', },
{ question: 'Quels sont les dérivés de l’épiderme ?', answer: 'Peau, dents, placodes.', },
{ question: 'Quels sont les dérivés du mésoderme axial ?', answer: 'Chorde et nucleus pulposus.', },
{ question: 'Quels sont les dérivés du dermatome ?', answer: 'Le derme.', },
{ question: 'Quels sont les dérivés du sclérotome ?', answer: 'Le squelette vertébral.', },
{ question: 'Quels sont les dérivés du syndétome ?', answer: 'Les tendons.', },
{ question: 'Quels sont les dérivés du myotome ?', answer: 'Les muscles.', },
{ question: 'Quels sont les dérivés du gononéphrotome ?', answer: 'Les reins et les gonades.', },
{ question: 'Quels sont les dérivés de la somatopleure ?', answer: 'Le péricarde, le derme latéral, les crêtes génitales, la charpente conjonctive des muscles.', },
{ question: 'Quels sont les dérivés de la splanchnopleure ?', answer: 'Muscles lisses, rate, cœur, appareil circulatoire, mésentère.', },
{ question: 'Quels sont les dérivés principaux de l’endoderme ?', answer: 'Trachée, poumons, thyroïde, tube digestif, foie, pancréas.', },
{ question: 'Qu’est-ce que la totipotence ?', answer: 'La capacité d’une cellule à donner un individu complet, exemple : blastomères.', },
{ question: 'Qu’est-ce que la pluripotence ?', answer: 'La capacité de donner un large spectre de cellules sans former un individu complet, exemple : masse cellulaire interne.', },
{ question: 'Qu’est-ce que la multipotence ?', answer: 'La capacité de donner plusieurs types cellulaires dans un seul type tissulaire.', },
{ question: 'Qu’est-ce que l’unipotence ?', answer: 'La capacité de donner un seul type cellulaire tout en pouvant s’auto-renouveler.', },
{ question: 'Quels sont les signaux extracellulaires impliqués dans la spécification cellulaire ?', answer: 'Les voies TGFβ, FGF et Wnt.', },
{ question: 'Quels changements génétiques accompagnent la différenciation ?', answer: 'Extinction des gènes de pluripotence et activation de gènes spécifiques via facteurs de transcription et modifications épigénétiques.', },
{ question: 'Que représente l’épigénèse selon Aristote ?', answer: 'La formation progressive des organes à partir d’un état indifférencié.', },
{ question: 'Que représente le paysage épigénétique de Waddington ?', answer: 'Le cheminement d’une cellule vers son destin contrôlé par l’expression génique et les modifications épigénétiques.', },
{ question: 'Qu’est-ce que l’épigénétique ?', answer: 'L’étude des modifications de l’ADN ou des histones modifiant l’expression des gènes sans changer la séquence.', },
{ question: 'Quel exemple illustre le contrôle épigénétique ?', answer: 'La métamorphose du Xénope contrôlée par les gènes cibles de l’hormone T3.', },
{ question: 'De quoi dérivent les muscles squelettiques ?', answer: 'Du mésoderme des somites.', },
{ question: 'Qu’est-ce qu’une cellule spécifiée dans la lignée musculaire ?', answer: 'Un progéniteur musculaire engagé de manière réversible.', },
{ question: 'Qu’est-ce qu’une cellule déterminée dans la lignée musculaire ?', answer: 'Un myoblaste engagé de manière irréversible.', },
{ question: 'Qu’est-ce qu’une fibre musculaire ?', answer: 'Une cellule différenciée plurinucléée.', },
{ question: 'Que devient le somite épithélial lors de sa maturation ?', answer: 'Il se subdivise en dermomyotome et sclérotome.', },
{ question: 'Dans quelle structure observe-t-on l’origine somite des muscles des membres ?', answer: 'Dans les expériences de greffes caille-poule.', },
{ question: 'Quels sont les Myogenic Regulatory Factors ?', answer: 'Myf5, MyoD, Myogénine, MRF4.', },
{ question: 'Quel est le rôle de Pax3 dans la spécification musculaire ?', answer: 'Il est exprimé précocement dans le dermomyotome et nécessaire à la migration myoblastique vers les bourgeons de membres.', },
{ question: 'Que provoque un mutant Pax3 chez la souris ?', answer: 'Des myocytes présents dans les somites mais absence de muscles dans les membres.', },
{ question: 'Que font les MRFs dans la différenciation musculaire ?', answer: 'Ils codent des facteurs bHLH capables de convertir d’autres types cellulaires en cellules musculaires.', },
{ question: 'Quelles étapes cellulaires expriment les MRF selon leur progression ?', answer: 'Selon le stade : Myf5 et MyoD précoces, Myogénine et MRF4 plus tardifs.', },
{ question: 'Comment se déroule la régénération musculaire adulte ?', answer: 'Grâce à l’activation des cellules satellites après lésion par notéxine.', },
{ question: 'Pourquoi les fibres musculaires régénérées peuvent-elles gêner le mouvement ?', answer: 'Elles n’ont pas de noyaux périphériques.', },
{ question: 'Qu’est-ce qu’une myopathie centronucléaire ?', answer: 'Une myopathie caractérisée par des noyaux placés au centre des fibres musculaires hors contexte de régénération.', },
{ question: 'Quels gènes sont associés aux myopathies centronucléaires ?', answer: 'MTM1 (45 %) et DNM2 (15 %).', },
{ question: 'Quel est l’autre nom de la forme liée à l’X des myopathies centronucléaires ?', answer: 'La myopathie myotubulaire (XLMTM).', },
{ question: 'Quels sont les symptômes de la XLMTM ?', answer: 'Hypotonie sévère, faiblesse musculaire généralisée et issue souvent fatale par insuffisance respiratoire.', },
{ question: 'Quel est le rôle du gène MTM1 ?', answer: 'Il code la myotubularine, une phosphoinositide phosphatase impliquée dans le trafic membranaire.', },
{ question: 'Quels sont les symptômes des formes autosomiques dominantes DNM2 ?', answer: 'Faiblesse musculaire progressive, retard moteur, ptosis, ophtalmoplégie, rétractions du tendon d’Achille.', },
{ question: 'Quel est le rôle de la dynamine 2 codée par DNM2 ?', answer: 'Une GTPase impliquée dans le trafic membranaire et la régulation des cytosquelettes.', },
{ question: 'Quel est le tableau histopathologique typique des myopathies centronucléaires ?', answer: 'Centralisation nucléaire, atrophie des fibres lentes et travées sarcoplasmiques en rayons de roue.', },
