{ question: 'Quelle est la seule cellule souche totipotente ?', answer: 'Le zygote.', },
{ question: 'Jusqu’à quel stade une cellule est-elle totipotente ?', answer: 'Jusqu’au stade 3 cellules.', },
{ question: 'Que peut donner une cellule totipotente ?', answer: 'Un individu complet, les trois feuillets embryonnaires et les structures extra-embryonnaires.', },
{ question: 'Quels sont les deux types de cellules du blastocyste ?', answer: 'La masse cellulaire interne et le trophectoderme.', },
{ question: 'Quel est le potentiel des cellules de la masse cellulaire interne ?', answer: 'Elles sont pluripotentes et donneront les trois feuillets primordiaux.', },
{ question: 'Quel est le rôle du trophectoderme ?', answer: 'Former les annexes embryonnaires.', },
{ question: 'Qu’est-ce qu’une cellule multipotente ?', answer: 'Une cellule capable de donner plusieurs types cellulaires dans un seul type tissulaire.', },
{ question: 'Quel est l’exemple classique de cellule multipotente ?', answer: 'La cellule souche hématopoïétique.', },
{ question: 'Quelles sont les cellules souches apparues dès le stade fœtal ?', answer: 'Les cellules souches unipotentes.', },
{ question: 'Quelles sont les deux propriétés des cellules souches ?', answer: 'L’auto-renouvellement et la différenciation.', },
{ question: 'Quelle division assure la différenciation des cellules souches ?', answer: 'La division asymétrique.', },
{ question: 'En quelle année apparaît l’expression “cellule souche” ?', answer: 'Entre 1860 et 1920.', },
{ question: 'Qui propose le concept de cellule souche sanguine ?', answer: 'Danchakoff en 1915.', },
{ question: 'Qu’est-ce qu’un tératocarcinome ?', answer: 'Une tumeur contenant des tissus différenciés et des cellules indifférenciées (EC).', },
{ question: 'Que démontre l’injection de cellules EC dans un blastocyste ?', answer: 'Qu’elles peuvent redevenir plastiques et intégrer un embryon normal.', },
{ question: 'Qui isole les premières cellules souches embryonnaires (ES) ?', answer: 'Martin Evans en 1981.', },
{ question: 'Qu’indique l’injection de cellules EC à une souris immunodéprimée ?', answer: 'La formation d’un tératome, preuve de pluripotence.', },
{ question: 'Quand obtient-on les premières souris transgéniques via cellules ES ?', answer: 'En 1986.', },
{ question: 'Quel modèle pathologique transgénique est créé en 1987 ?', answer: 'La souris Lesch-Nyhan.', },
{ question: 'Quelle enzyme est déficiente dans le syndrome de Lesch-Nyhan ?', answer: 'L’hypoxanthine-guanine phosphoribosyltransférase (HGPRT).', },
{ question: 'En quelle année les cellules souches embryonnaires humaines sont-elles mises en culture ?', answer: 'En 1998.', },
{ question: 'Quel scandale a marqué la recherche ES humaine ?', answer: 'Les jumelles génétiquement modifiées en Chine.', },
{ question: 'Qui reçoit le prix Nobel 2007 pour les cellules souches ?', answer: 'Mario Capecchi, Martin Evans et Oliver Smithies.', },
{ question: 'Que démontre John Gurdon en 1960 ?', answer: 'La reprogrammation nucléaire et la totipotence.', },
{ question: 'Quelle technique a permis la naissance de la brebis Dolly ?', answer: 'Le transfert nucléaire d’une cellule somatique.', },
{ question: 'Qu’est-ce que le clonage thérapeutique ?', answer: 'Créer des cellules compatibles pour greffe par transfert nucléaire, interdit chez l’homme en France.', },
{ question: 'Qui découvre les cellules iPS ?', answer: 'John Gurdon et Shinya Yamanaka.', },
{ question: 'En quelle année les iPS sont-elles créées ?', answer: 'En 2006.', },
{ question: 'Quels sont les quatre facteurs de Yamanaka ?', answer: 'cMyc, Klf4, Sox2 et Oct3/4.', },
{ question: 'Quel est le rôle des facteurs iPS ?', answer: 'Réprimer les gènes de spécialisation, effacer les modifications épigénétiques et activer les gènes de prolifération.', },
{ question: 'Quel est le rendement moyen de reprogrammation en iPS ?', answer: '0,5 à 1%.', },
{ question: 'Quelles cellules souches produisent les lignées myéloïdes et lymphoïdes ?', answer: 'Les cellules souches hématopoïétiques.', },
{ question: 'Où trouve-t-on les cellules souches hématopoïétiques ?', answer: 'Dans la moelle osseuse des os plats.', },
{ question: 'Qu’est-ce qu’une aplasie médullaire ?', answer: 'L’absence de cellules hématopoïétiques dans la moelle, remplacées par des adipocytes.', },
{ question: 'Que permet une greffe de moelle osseuse ?', answer: 'Reconstituer un système sanguin fonctionnel après destruction du système malade.', },
{ question: 'Qui réalise la première greffe de moelle humaine ?', answer: 'Edward Thomas en 1968.', },
{ question: 'Quel est le principe du traitement de la sclérose en plaques par cellules souches ?', answer: 'Réinitialiser le système immunitaire via autogreffe de cellules hématopoïétiques.', },
{ question: 'Comment obtient-on les cellules souches adipeuses hASC ?', answer: 'Par liposuccion puis isolement du tissu adipeux.', },
{ question: 'Quel est le potentiel des hASC ?', answer: 'Elles sont multipotentes.', },
{ question: 'Quels types de cellules peuvent dériver des hASC ?', answer: 'Adipocytes, chondrocytes, ostéoblastes, myocytes, cardiomyocytes, ténocytes, hépatocytes, cellules pancréatiques, cellules neurales.', },
{ question: 'Pourquoi utilise-t-on les hASC en arthrose ?', answer: 'Pour leurs cytokines pro-régénération et propriétés anti-inflammatoires.', },
{ question: 'Les hASC se différencient-elles spontanément en chondrocytes ?', answer: 'Non, elles ne se différencient pas spontanément en cartilage.', },
{ question: 'Pourquoi utilise-t-on des biomatériaux avec les hASC ?', answer: 'Pour les maintenir sur le site de la lésion et favoriser leur différenciation.', },
{ question: 'Quel essai clinique utilisant des ES a été arrêté en 2011 ?', answer: 'La thérapie cellulaire par oligodendrocytes dérivés de cellules ES pour lésions médullaires.', },
{ question: 'Quel risque principal est associé aux iPS ?', answer: 'Le risque tumoral lié à leur forte capacité proliférative.', },
{ question: 'Pourquoi les hASC sont-elles considérées comme moins risquées que les iPS ?', answer: 'Parce qu’elles sont naturelles, non transformées, mais peuvent néanmoins se différencier de façon aberrante.', },
{ question: 'Quel espoir représente les iPS en médecine ?', answer: 'La refabrication de structures oculaires et de cellules pancréatiques pour le diabète.', },
